module
public import Init
public import UorAtlas.Prelude.Algebra

/-!
Permutations of a finite set, and the finite-group machinery the group layer of
UOR-ATLAS-FORMAL-001 rests on.

`D20` and `D21` present the automorphism group as `Aut := < s_a : a in Sim >`,
a subgroup of the permutations of the `120` root classes of `D12`. Every
cardinality the document states about that layer -- `|Aut| = 348364800`
(`T28`, `T59`), `|Gauge(W)| = 4608` (`T29`, `T49`, `T60`), `|Ker| = 576`
(`T32`, `T51`), `|image(rho)| = 8` (`T31`, `T50`) -- is a statement about a
permutation group presented by generators, so this module supplies:

* permutations of `Fin n` with the group laws and decidable equality;
* the subgroup generated by a list of permutations, both as an inductive
  predicate `Perm.Gen` -- which *is* the `< ... >` of `D21` -- and as a
  computable saturation whose output is proved to be exactly that predicate's
  extension, in both directions;
* orbits, again both inductively (`Perm.Reach`) and computably;
* orbit-stabilizer, `|G| = |orbit| * |stabilizer|`.

Orbit-stabilizer is the route the document itself takes. `T43` is the orbit map
`Aut / Aut(W) -> Ob(Atl)` being a bijection; with `T24` and `T29` that is `T28`,
and `T60` reads the same identity inside `Aut(Gamma)`. The Atlas numbers are not
computed here -- this module is parametric in `n` and in the generators -- but
the identity they are read off is proved here.

The algebra keystone is re-exported rather than used: a module that imports
`Perm` and one that imports `Linear` must see the *same* `AddCommGroup` /
`CommRing` / `Field` hierarchy, because the later group-action modules mix the
permutation layer of `D21` with the lattice layer of `D10` in single statements.
-/

set_option autoImplicit false

namespace UorAtlas.Prelude

universe u v

/-! ## List auxiliaries

What the saturation and the counting argument need and `Init`'s `List` API does
not already carry: filtered deduplication with its membership and `Nodup`
characterisations, sums over a mapped list, and the two counting lemmas that
turn a partition into fibres into an arithmetic identity.

`Init` has `List.eraseDups`, but proves only `mem_eraseDups` and not the
`Nodup` of its result, and the saturation additionally has to discard
candidates already accumulated -- which `eraseDups` cannot express. One
function, `freshOf`, covers both, and plain deduplication is the case where
nothing has been accumulated yet. -/

namespace ListAux

variable {α : Type u} {β : Type v}

/-- Prepend `a` unless it is already accounted for, either in the reference
list `seen` or in the result accumulated so far, `acc`. -/
@[expose] public def consNew [DecidableEq α] (seen : List α) (a : α) (acc : List α) : List α :=
  if a ∈ seen then acc else if a ∈ acc then acc else a :: acc

/-- The members of `cands` that are absent from `seen`, each kept once. -/
@[expose] public def freshOf [DecidableEq α] (seen : List α) : List α → List α
  | [] => []
  | a :: as => consNew seen a (freshOf seen as)

public theorem mem_freshOf [DecidableEq α] {seen : List α} {a : α} :
    ∀ {cands : List α}, a ∈ freshOf seen cands ↔ a ∈ cands ∧ a ∉ seen := by
  intro cands
  induction cands with
  | nil => simp [freshOf]
  | cons c cs ih =>
    simp only [freshOf, consNew]
    split
    · next hc =>
      rw [ih, List.mem_cons]
      constructor
      · exact fun h => ⟨Or.inr h.1, h.2⟩
      · rintro ⟨rfl | hm, hs⟩
        · exact absurd hc hs
        · exact ⟨hm, hs⟩
    · next hc =>
      split
      · next hr =>
        rw [List.mem_cons]
        constructor
        · exact fun h => ⟨Or.inr (ih.mp h).1, (ih.mp h).2⟩
        · rintro ⟨rfl | hm, hs⟩
          · exact hr
          · exact ih.mpr ⟨hm, hs⟩
      · next hr =>
        rw [List.mem_cons, ih, List.mem_cons]
        constructor
        · rintro (rfl | ⟨hm, hs⟩)
          · exact ⟨Or.inl rfl, hc⟩
          · exact ⟨Or.inr hm, hs⟩
        · rintro ⟨rfl | hm, hs⟩
          · exact Or.inl rfl
          · exact Or.inr ⟨hm, hs⟩

public theorem nodup_freshOf [DecidableEq α] {seen : List α} :
    ∀ {cands : List α}, (freshOf seen cands).Nodup := by
  intro cands
  induction cands with
  | nil => exact List.nodup_nil
  | cons c cs ih =>
    simp only [freshOf, consNew]
    split
    · exact ih
    · split
      · exact ih
      · next _ hr => exact List.nodup_cons.mpr ⟨hr, ih⟩

/-- `freshOf []` is deduplication: nothing is ever `seen`. -/
@[expose] public def dedup [DecidableEq α] (l : List α) : List α := freshOf [] l

public theorem mem_dedup [DecidableEq α] {l : List α} {a : α} : a ∈ dedup l ↔ a ∈ l := by
  simp [dedup, mem_freshOf]

public theorem nodup_dedup [DecidableEq α] {l : List α} : (dedup l).Nodup := nodup_freshOf

public theorem sum_map_eq_zero {f : β → Nat} :
    ∀ {l : List β}, (∀ b ∈ l, f b = 0) → (l.map f).sum = 0 := by
  intro l
  induction l with
  | nil => intro _; rfl
  | cons b bs ih =>
    intro h
    simp only [List.map_cons, List.sum_cons, h b (List.mem_cons_self ..),
      ih (fun c hc => h c (List.mem_cons_of_mem _ hc))]

public theorem sum_map_const (c : Nat) :
    ∀ {l : List β}, (l.map (fun _ => c)).sum = l.length * c := by
  intro l
  induction l with
  | nil => simp
  | cons _ bs ih =>
    simp only [List.map_cons, List.sum_cons, ih, List.length_cons, Nat.succ_mul]
    exact Nat.add_comm _ _

public theorem sum_map_add (f g : β → Nat) :
    ∀ {l : List β}, (l.map (fun b => f b + g b)).sum = (l.map f).sum + (l.map g).sum := by
  intro l
  induction l with
  | nil => rfl
  | cons _ bs ih => simp only [List.map_cons, List.sum_cons, ih]; omega

/-- On a `Nodup` list the indicator of a member sums to `1`. This is the step
that turns "partition into fibres" into an arithmetic identity. -/
public theorem sum_map_indicator [DecidableEq β] {b : β} :
    ∀ {l : List β}, l.Nodup → b ∈ l → (l.map (fun y => if b = y then 1 else 0)).sum = 1 := by
  intro l
  induction l with
  | nil => intro _ h; exact absurd h (by simp)
  | cons c cs ih =>
    intro hnd hmem
    have hnd' := List.nodup_cons.mp hnd
    simp only [List.map_cons, List.sum_cons]
    by_cases hbc : b = c
    · subst hbc
      have hzero : ∀ y ∈ cs, (if b = y then 1 else 0) = 0 := by
        intro y hy
        refine if_neg ?_
        intro he
        exact hnd'.1 (by rw [← he] at hy; exact hy)
      simp [sum_map_eq_zero hzero]
    · simp only [if_neg hbc, Nat.zero_add]
      exact ih hnd'.2 ((List.mem_cons.mp hmem).resolve_left hbc)

/-- Two duplicate-free lists with the same members have the same length. The
counting characterisation of `List.Perm` is what makes this cheap; without it
every equinumerosity below would need an explicit bijection of positions. -/
public theorem length_eq_of_mem_iff [DecidableEq α] {l₁ l₂ : List α}
    (h₁ : l₁.Nodup) (h₂ : l₂.Nodup) (h : ∀ a, a ∈ l₁ ↔ a ∈ l₂) :
    l₁.length = l₂.length :=
  (List.perm_iff_count.mpr fun a => by
    rw [List.Nodup.count h₁, List.Nodup.count h₂]
    by_cases ha : a ∈ l₁
    · rw [if_pos ha, if_pos ((h a).mp ha)]
    · rw [if_neg ha, if_neg (fun hb => ha ((h a).mpr hb))]).length_eq

/-- Counting a list by the fibres of any map into a duplicate-free index list.
This is the combinatorial content of orbit-stabilizer. -/
public theorem length_eq_sum_fibres [DecidableEq β] (f : α → β) {ys : List β} (hy : ys.Nodup) :
    ∀ {l : List α}, (∀ a ∈ l, f a ∈ ys) →
      l.length = (ys.map (fun y => l.countP (fun a => decide (f a = y)))).sum := by
  intro l
  induction l with
  | nil => intro _; exact (sum_map_eq_zero (fun _ _ => rfl)).symm
  | cons a as ih =>
    intro hmem
    have hstep : ∀ y : β,
        (a :: as).countP (fun c => decide (f c = y))
          = as.countP (fun c => decide (f c = y)) + (if f a = y then 1 else 0) := by
      intro y; rw [List.countP_cons]; simp
    rw [List.map_congr_left (fun y _ => hstep y), sum_map_add,
      ← ih (fun c hc => hmem c (List.mem_cons_of_mem _ hc)),
      sum_map_indicator hy (hmem a (List.mem_cons_self ..))]
    simp [List.length_cons]

end ListAux

/-! ## Permutations

`Perm n` carries the forward map, its inverse, and the two round-trip
equations, in the style of an equivalence rather than of a table.

The alternative was a table-backed permutation -- a `List (Fin n)` or an
`Array (Fin n)` with a bijectivity proof -- and the choice was settled by
measurement, because the evaluator that matters here is the one that replays
the proofs. Timings below are `lean` user time on this machine, against an
empty file at `0.35 s`; `n = 120` is the size of `K` in `D12`, and each
closure is the saturation this module implements.

| workload                                    | function | `List` table | packed `Nat` |
| ------------------------------------------- | -------- | ------------ | ------------ |
| `n = 120`, `240` compositions then one `=`   | `8.0 s`  | `130 s`      | `7.0 s`      |
| `n = 120`, close the cyclic group of `120`   | `8.0 s`  | `> 107 s` *  | `7.0 s`      |
| `n = 6`, close `Sym(6)`, `720` elements      | `131 s`  | `126 s`      | `87 s`       |

`*` killed at a `600 s` wall-clock limit.

The table form loses badly wherever `n` is large, for the reason `Linear.lean`
gives for `Vec`: the kernel has no primitive `Array` or `List`, so a lookup
costs one recursor unfolding per index step and a composition costs `n` of
them, `O(n^2)` per product, while the function form composes in one beta step
and evaluates only the coordinates a proof actually inspects.

The third column packs the whole table into a single base-`256` `Nat`, so that
equality is one GMP comparison. It is recorded rather than adopted. The last
row is why: at `720` elements the `O(|G|^2)` membership scan, not the
representation, is what costs, and only the packed form makes an individual
test `O(1)` rather than `O(n)`. That is the representation to reach for if a
later module needs a group larger than a few thousand elements; here it would
have bought a factor of `1.5` in exchange for a body of digit-arithmetic
lemmas this module has no other use for.

Splitting the first row with `set_option debug.skipKernelTC true` puts `3.5 s`
in the elaborator and `4.6 s` in the kernel, so neither half is being hidden by
the other.

The price of the function form is that permutation equality is function
equality, so `Perm.ext` charges `Quot.sound` through `funext`. That is the
price `Vec` already pays, and `Quot.sound` is inside the permitted base. -/

/-- A permutation of `Fin n`, given by a map, its inverse, and the round-trip
equations. -/
public structure Perm (n : Nat) where
  toFun : Fin n → Fin n
  invFun : Fin n → Fin n
  left_inv : ∀ i : Fin n, invFun (toFun i) = i
  right_inv : ∀ i : Fin n, toFun (invFun i) = i

namespace Perm

variable {n : Nat}

/-- The inverse field is determined by the forward field, so permutations are
equal as soon as they agree pointwise. -/
public theorem ext {p q : Perm n} (h : ∀ i : Fin n, p.toFun i = q.toFun i) : p = q := by
  have hf : p.toFun = q.toFun := funext h
  have hg : p.invFun = q.invFun := by
    funext i
    have hi : p.invFun i = p.invFun (q.toFun (q.invFun i)) := by rw [q.right_inv]
    rw [hi, ← hf, p.left_inv]
  cases p
  cases q
  simp only at hf hg
  subst hf
  subst hg
  rfl

public theorem toFun_injective {p : Perm n} {i j : Fin n} (h : p.toFun i = p.toFun j) : i = j := by
  have := congrArg p.invFun h
  rwa [p.left_inv, p.left_inv] at this

/-- Pointwise equality as a `Bool`, tested along `List.finRange n`.

The obvious `decide (∀ i : Fin n, p.toFun i = q.toFun i)` is shorter and was
measured to be much worse: it routes through `Nat.decidableBallLT`, which
rewraps the predicate at every level and so costs `O(n^2)` reductions per test,
while walking `finRange` costs `O(n)`. On the closure of the cyclic group of
order `120` inside `Perm 120` that is `8.0 s` against `62 s`. Since every
saturation round tests each candidate against the whole accumulator, this
factor multiplies the cost of every group this module will ever close. -/
@[expose] public def beq (p q : Perm n) : Bool :=
  (List.finRange n).all fun i => decide (p.toFun i = q.toFun i)

public theorem beq_iff (p q : Perm n) : beq p q = true ↔ p = q := by
  rw [beq, List.all_eq_true]
  constructor
  · exact fun h => ext fun i => of_decide_eq_true (h i (List.mem_finRange i))
  · intro h i _
    exact decide_eq_true (by rw [h])

public instance instDecidableEq : DecidableEq (Perm n) := fun p q =>
  decidable_of_decidable_of_iff (beq_iff p q)

/-- The identity permutation. -/
@[expose] public def one (n : Nat) : Perm n where
  toFun i := i
  invFun i := i
  left_inv _ := rfl
  right_inv _ := rfl

/-- Composition, in the order `(p.comp q) i = p (q i)`. -/
@[expose] public def comp (p q : Perm n) : Perm n where
  toFun i := p.toFun (q.toFun i)
  invFun i := q.invFun (p.invFun i)
  left_inv i := by rw [p.left_inv, q.left_inv]
  right_inv i := by rw [q.right_inv, p.right_inv]

/-- The inverse permutation: the two maps swap roles, so this is free. -/
@[expose] public def inv (p : Perm n) : Perm n where
  toFun := p.invFun
  invFun := p.toFun
  left_inv := p.right_inv
  right_inv := p.left_inv

public theorem one_apply (i : Fin n) : (one n).toFun i = i := rfl

public theorem comp_apply (p q : Perm n) (i : Fin n) : (p.comp q).toFun i = p.toFun (q.toFun i) :=
  rfl

public theorem inv_apply (p : Perm n) (i : Fin n) : p.inv.toFun i = p.invFun i := rfl

/-! ### The group laws -/

public theorem comp_assoc (p q r : Perm n) : (p.comp q).comp r = p.comp (q.comp r) := rfl

public theorem one_comp (p : Perm n) : (one n).comp p = p := rfl

public theorem comp_one (p : Perm n) : p.comp (one n) = p := rfl

public theorem comp_inv (p : Perm n) : p.comp p.inv = one n := ext fun i => p.right_inv i

public theorem inv_comp (p : Perm n) : p.inv.comp p = one n := ext fun i => p.left_inv i

public theorem inv_inv (p : Perm n) : p.inv.inv = p := rfl

public theorem one_inv : (one n).inv = one n := rfl

public theorem inv_comp_distrib (p q : Perm n) : (p.comp q).inv = q.inv.comp p.inv := rfl

public theorem comp_left_cancel {t p q : Perm n} (h : t.comp p = t.comp q) : p = q :=
  ext fun i => toFun_injective (congrArg (fun r : Perm n => r.toFun i) h)

end Perm

/-! ## The generated subgroup

`Perm.Gen gens` is the `< ... >` of `D21`, written as the least predicate
containing the identity and closed under right multiplication by a generator
or by the inverse of a generator. Inverses are constructors rather than a
derived fact: in a finite permutation group the monoid generated by a set is
already the group, but that argument needs a pigeonhole and buys nothing --
`D21` means the subgroup, and this is the subgroup. -/

namespace Perm

variable {n : Nat}

/-- The subgroup generated by `gens`. -/
public inductive Gen (gens : List (Perm n)) : Perm n → Prop
  | one : Gen gens (Perm.one n)
  | step {g s : Perm n} : Gen gens g → s ∈ gens → Gen gens (g.comp s)
  | stepInv {g s : Perm n} : Gen gens g → s ∈ gens → Gen gens (g.comp s.inv)

public theorem Gen.mem_gen {gens : List (Perm n)} {s : Perm n} (hs : s ∈ gens) : Gen gens s :=
  Gen.step Gen.one hs

public theorem Gen.mem_gen_inv {gens : List (Perm n)} {s : Perm n} (hs : s ∈ gens) :
    Gen gens s.inv :=
  Gen.stepInv Gen.one hs

/-- Closure under products. The induction runs on the *second* factor, because
that is the side the constructors extend. -/
public theorem Gen.comp_mem {gens : List (Perm n)} {a b : Perm n}
    (ha : Gen gens a) (hb : Gen gens b) : Gen gens (a.comp b) := by
  induction hb with
  | one => exact ha
  -- The reassociation is definitional, but it has to be *stated*: matching the
  -- goal `a.comp (g.comp s)` against the constructor's `?g.comp ?s` would pick
  -- `?g := a` and leave the wrong subgoal.
  | @step g s _ hs ih =>
    have hstep : Gen gens ((a.comp g).comp s) := Gen.step ih hs
    exact hstep
  | @stepInv g s _ hs ih =>
    have hstep : Gen gens ((a.comp g).comp s.inv) := Gen.stepInv ih hs
    exact hstep

/-- Closure under inverses. -/
public theorem Gen.inv_mem {gens : List (Perm n)} {g : Perm n} (hg : Gen gens g) :
    Gen gens g.inv := by
  induction hg with
  | one => exact Gen.one
  | step _ hs ih => exact Gen.comp_mem (Gen.mem_gen_inv hs) ih
  | stepInv _ hs ih => exact Gen.comp_mem (Gen.mem_gen hs) ih

/-- A list closed under the identity and under right multiplication by the
generators and their inverses. -/
public abbrev ClosedUnder (gens L : List (Perm n)) : Prop :=
  Perm.one n ∈ L ∧ ∀ g ∈ L, ∀ s ∈ gens, g.comp s ∈ L ∧ g.comp s.inv ∈ L

/-- **Completeness of a closed list.** A closed list contains the whole
generated subgroup. This is the load-bearing half: a saturation that merely
stops proves nothing, whereas this says that once the closure condition holds
there is nothing left outside. -/
public theorem Gen.subset_of_closedUnder {gens L : List (Perm n)} (h : ClosedUnder gens L)
    {g : Perm n} (hg : Gen gens g) : g ∈ L := by
  induction hg with
  | one => exact h.1
  | step _ hs ih => exact (h.2 _ ih _ hs).1
  | stepInv _ hs ih => exact (h.2 _ ih _ hs).2

end Perm

/-! ## Computing the generated subgroup

Breadth-first saturation. `saturate` carries the elements already processed
(`old`) separately from the frontier (`fr`) and returns `some` only when the
frontier is empty, so a `some` result is by construction a *saturated* one:
exhaustion of the fuel returns `none` and proves nothing. That is what removes
the need for a separate closure certificate, which at Atlas size would cost
another `|L| * |gens| * |L|` membership tests to check. -/

namespace Perm

open ListAux

variable {n : Nat}

/-- One round of candidates: every frontier element times every generator and
every inverse generator. -/
@[expose] public def products (gens fr : List (Perm n)) : List (Perm n) :=
  fr.flatMap fun g => gens.flatMap fun s => [g.comp s, g.comp s.inv]

public theorem mem_products {gens fr : List (Perm n)} {c : Perm n} :
    c ∈ products gens fr ↔ ∃ g ∈ fr, ∃ s ∈ gens, c = g.comp s ∨ c = g.comp s.inv := by
  constructor
  · intro hc
    obtain ⟨g, hg, hc⟩ := List.mem_flatMap.mp hc
    obtain ⟨s, hs, hc⟩ := List.mem_flatMap.mp hc
    refine ⟨g, hg, s, hs, ?_⟩
    rcases List.mem_cons.mp hc with hc | hc
    · exact Or.inl hc
    · exact Or.inr (List.mem_singleton.mp hc)
  · rintro ⟨g, hg, s, hs, hc | hc⟩ <;>
      exact List.mem_flatMap.mpr ⟨g, hg, List.mem_flatMap.mpr ⟨s, hs, by simp [hc]⟩⟩

/-- Saturate the frontier. `some L` is returned only when the frontier has been
exhausted; running out of fuel is `none`. -/
@[expose] public def saturate (gens : List (Perm n)) :
    Nat → List (Perm n) → List (Perm n) → Option (List (Perm n))
  | 0, _, _ => none
  | _ + 1, old, [] => some old
  | fuel + 1, old, a :: fr =>
      saturate gens fuel (old ++ a :: fr)
        (freshOf (old ++ a :: fr) (products gens (a :: fr)))

/-- The generated subgroup as a list, when the fuel suffices. -/
@[expose] public def closure (gens : List (Perm n)) (fuel : Nat) : Option (List (Perm n)) :=
  saturate gens fuel [] [Perm.one n]

/-- The saturation invariant, proved by induction on the fuel. `old` is
processed, `fr` is the frontier, and the accumulated set is `old ++ fr`. -/
public theorem saturate_spec (gens : List (Perm n)) :
    ∀ (fuel : Nat) (old fr L : List (Perm n)),
      (old ++ fr).Nodup →
      Perm.one n ∈ old ++ fr →
      (∀ g ∈ old ++ fr, Gen gens g) →
      (∀ g ∈ old, ∀ s ∈ gens, g.comp s ∈ old ++ fr ∧ g.comp s.inv ∈ old ++ fr) →
      saturate gens fuel old fr = some L →
      L.Nodup ∧ (∀ g ∈ L, Gen gens g) ∧ ClosedUnder gens L := by
  intro fuel
  induction fuel with
  | zero => intro old fr L _ _ _ _ h; exact absurd h (by simp [saturate])
  | succ fuel ih =>
    intro old fr L hnd hone hgen hcl h
    cases fr with
    | nil =>
      simp only [saturate, Option.some.injEq] at h
      subst h
      rw [List.append_nil] at hnd hone hgen hcl
      exact ⟨hnd, hgen, hone, hcl⟩
    | cons a fr =>
      simp only [saturate] at h
      refine ih (old ++ a :: fr) (freshOf (old ++ a :: fr) (products gens (a :: fr))) L
        ?_ ?_ ?_ ?_ h
      · refine List.nodup_append.mpr ⟨hnd, nodup_freshOf, ?_⟩
        intro b hb c hc he
        exact (mem_freshOf.mp hc).2 (he ▸ hb)
      · exact List.mem_append_left _ hone
      · intro g hg
        rcases List.mem_append.mp hg with hg | hg
        · exact hgen g hg
        · obtain ⟨u, hu, s, hs, hus⟩ := mem_products.mp (mem_freshOf.mp hg).1
          have hu' : Gen gens u := hgen u (List.mem_append_right _ hu)
          rcases hus with rfl | rfl
          · exact Gen.step hu' hs
          · exact Gen.stepInv hu' hs
      · intro g hg s hs
        have key : ∀ c : Perm n, c ∈ products gens (a :: fr) →
            c ∈ old ++ a :: fr ++ freshOf (old ++ a :: fr) (products gens (a :: fr)) := by
          intro c hc
          by_cases hin : c ∈ old ++ a :: fr
          · exact List.mem_append_left _ hin
          · exact List.mem_append_right _ (mem_freshOf.mpr ⟨hc, hin⟩)
        rcases List.mem_append.mp hg with hg | hg
        · exact ⟨List.mem_append_left _ (hcl g hg s hs).1,
            List.mem_append_left _ (hcl g hg s hs).2⟩
        · exact ⟨key _ (mem_products.mpr ⟨g, hg, s, hs, Or.inl rfl⟩),
            key _ (mem_products.mpr ⟨g, hg, s, hs, Or.inr rfl⟩)⟩

/-- **The closure is exactly the generated subgroup.** Soundness and
completeness together: membership in the computed list and membership in
`Gen gens` are the same predicate. -/
public theorem closure_spec {gens : List (Perm n)} {fuel : Nat} {L : List (Perm n)}
    (h : closure gens fuel = some L) :
    L.Nodup ∧ ClosedUnder gens L ∧ ∀ g : Perm n, g ∈ L ↔ Gen gens g := by
  have hgen : ∀ g ∈ ([] : List (Perm n)) ++ [Perm.one n], Gen gens g := by
    intro g hg
    rw [List.nil_append, List.mem_singleton] at hg
    exact hg ▸ Gen.one
  have hcl : ∀ g ∈ ([] : List (Perm n)), ∀ s ∈ gens,
      g.comp s ∈ ([] : List (Perm n)) ++ [Perm.one n] ∧
        g.comp s.inv ∈ ([] : List (Perm n)) ++ [Perm.one n] := by
    intro g hg
    exact absurd hg (by simp)
  have hs := saturate_spec gens fuel [] [Perm.one n] L (by simp) (by simp) hgen hcl h
  exact ⟨hs.1, hs.2.2, fun g =>
    Iff.intro (fun hg => hs.2.1 g hg) (fun hg => Gen.subset_of_closedUnder hs.2.2 hg)⟩

end Perm

/-! ## Finite permutation groups as lists

`Subgroup` is a list carrying the group axioms. It is what the closure
produces and what orbit-stabilizer consumes; `order` is `|G|`. -/

namespace Perm

open ListAux

variable {n : Nat}

/-- A finite subgroup of `Perm n`, presented as a duplicate-free list. -/
public structure Subgroup (n : Nat) where
  carrier : List (Perm n)
  nodup : carrier.Nodup
  one_mem : Perm.one n ∈ carrier
  comp_mem : ∀ g ∈ carrier, ∀ h ∈ carrier, g.comp h ∈ carrier
  inv_mem : ∀ g ∈ carrier, g.inv ∈ carrier

namespace Subgroup

/-- `|G|`. -/
@[expose] public def order (G : Subgroup n) : Nat := G.carrier.length

/-- The subgroup `< gens >` of `D21`, once a saturation has succeeded. -/
@[expose] public def ofClosure (gens : List (Perm n)) (fuel : Nat) (L : List (Perm n))
    (h : closure gens fuel = some L) : Subgroup n where
  carrier := L
  nodup := (closure_spec h).1
  one_mem := (closure_spec h).2.1.1
  comp_mem g hg k hk :=
    ((closure_spec h).2.2 _).mpr
      (Gen.comp_mem (((closure_spec h).2.2 g).mp hg) (((closure_spec h).2.2 k).mp hk))
  inv_mem g hg :=
    ((closure_spec h).2.2 _).mpr (Gen.inv_mem (((closure_spec h).2.2 g).mp hg))

public theorem mem_ofClosure {gens : List (Perm n)} {fuel : Nat} {L : List (Perm n)}
    (h : closure gens fuel = some L) (g : Perm n) :
    g ∈ (ofClosure gens fuel L h).carrier ↔ Gen gens g := (closure_spec h).2.2 g

public theorem order_ofClosure {gens : List (Perm n)} {fuel : Nat} {L : List (Perm n)}
    (h : closure gens fuel = some L) : (ofClosure gens fuel L h).order = L.length := rfl

end Subgroup

end Perm

/-! ## Orbits

The orbit of a point, first as the least reachability predicate and then as the
same breadth-first saturation used for the group. Both are needed: the
predicate is what the orbit-stabilizer proof quantifies over, the saturation is
what a later module evaluates. `Reach` is stated in terms of the generators, not
of the whole group, because at `|Aut| = 348364800` the group is not a list any
kernel will hold, while its orbit on `120` classes is. -/

namespace Perm

open ListAux

variable {n : Nat}

/-- The orbit of `x` under `< gens >`, as a predicate. -/
public inductive Reach (gens : List (Perm n)) (x : Fin n) : Fin n → Prop
  | base : Reach gens x x
  | step {y : Fin n} {s : Perm n} : Reach gens x y → s ∈ gens → Reach gens x (s.toFun y)
  | stepInv {y : Fin n} {s : Perm n} : Reach gens x y → s ∈ gens → Reach gens x (s.invFun y)

/-- Every element of the generated group moves a reachable point to a
reachable point. -/
public theorem Reach.apply_gen {gens : List (Perm n)} {x : Fin n} {g : Perm n} (hg : Gen gens g) :
    ∀ {y : Fin n}, Reach gens x y → Reach gens x (g.toFun y) := by
  induction hg with
  | one => intro y hy; exact hy
  | step _ hs ih => intro y hy; exact ih (Reach.step hy hs)
  | stepInv _ hs ih => intro y hy; exact ih (Reach.stepInv hy hs)

/-- Reachability is exactly the orbit of the generated group. -/
public theorem Reach.iff_exists_gen {gens : List (Perm n)} {x y : Fin n} :
    Reach gens x y ↔ ∃ g : Perm n, Gen gens g ∧ g.toFun x = y := by
  refine Iff.intro (fun h => ?_) (fun ⟨g, hg, hgx⟩ => hgx ▸ Reach.apply_gen hg Reach.base)
  induction h with
  | base => exact ⟨Perm.one n, Gen.one, rfl⟩
  | @step z s _ hs ih =>
    obtain ⟨g, hg, hgx⟩ := ih
    exact ⟨s.comp g, Gen.comp_mem (Gen.mem_gen hs) hg, by rw [comp_apply, hgx]⟩
  | @stepInv z s _ hs ih =>
    obtain ⟨g, hg, hgx⟩ := ih
    exact ⟨s.inv.comp g, Gen.comp_mem (Gen.mem_gen_inv hs) hg, by rw [comp_apply, hgx, inv_apply]⟩

/-- One round of orbit candidates. -/
@[expose] public def images (gens : List (Perm n)) (fr : List (Fin n)) : List (Fin n) :=
  fr.flatMap fun y => gens.flatMap fun s => [s.toFun y, s.invFun y]

public theorem mem_images {gens : List (Perm n)} {fr : List (Fin n)} {z : Fin n} :
    z ∈ images gens fr ↔ ∃ y ∈ fr, ∃ s ∈ gens, z = s.toFun y ∨ z = s.invFun y := by
  constructor
  · intro hz
    obtain ⟨y, hy, hz⟩ := List.mem_flatMap.mp hz
    obtain ⟨s, hs, hz⟩ := List.mem_flatMap.mp hz
    refine ⟨y, hy, s, hs, ?_⟩
    rcases List.mem_cons.mp hz with hz | hz
    · exact Or.inl hz
    · exact Or.inr (List.mem_singleton.mp hz)
  · rintro ⟨y, hy, s, hs, hz | hz⟩ <;>
      exact List.mem_flatMap.mpr ⟨y, hy, List.mem_flatMap.mpr ⟨s, hs, by simp [hz]⟩⟩

/-- Breadth-first orbit saturation; `some` only on an exhausted frontier. -/
@[expose] public def orbitSat (gens : List (Perm n)) :
    Nat → List (Fin n) → List (Fin n) → Option (List (Fin n))
  | 0, _, _ => none
  | _ + 1, old, [] => some old
  | fuel + 1, old, a :: fr =>
      orbitSat gens fuel (old ++ a :: fr)
        (freshOf (old ++ a :: fr) (images gens (a :: fr)))

/-- The orbit of `x` as a list, when the fuel suffices. -/
@[expose] public def orbitOf (gens : List (Perm n)) (x : Fin n) (fuel : Nat) :
    Option (List (Fin n)) :=
  orbitSat gens fuel [] [x]

public theorem orbitSat_spec (gens : List (Perm n)) (x : Fin n) :
    ∀ (fuel : Nat) (old fr L : List (Fin n)),
      (old ++ fr).Nodup →
      x ∈ old ++ fr →
      (∀ y ∈ old ++ fr, Reach gens x y) →
      (∀ y ∈ old, ∀ s ∈ gens, s.toFun y ∈ old ++ fr ∧ s.invFun y ∈ old ++ fr) →
      orbitSat gens fuel old fr = some L →
      L.Nodup ∧ x ∈ L ∧ (∀ y ∈ L, Reach gens x y) ∧
        (∀ y ∈ L, ∀ s ∈ gens, s.toFun y ∈ L ∧ s.invFun y ∈ L) := by
  intro fuel
  induction fuel with
  | zero => intro old fr L _ _ _ _ h; exact absurd h (by simp [orbitSat])
  | succ fuel ih =>
    intro old fr L hnd hx hre hcl h
    cases fr with
    | nil =>
      simp only [orbitSat, Option.some.injEq] at h
      subst h
      rw [List.append_nil] at hnd hx hre hcl
      exact ⟨hnd, hx, hre, hcl⟩
    | cons a fr =>
      simp only [orbitSat] at h
      refine ih (old ++ a :: fr) (freshOf (old ++ a :: fr) (images gens (a :: fr))) L
        ?_ ?_ ?_ ?_ h
      · refine List.nodup_append.mpr ⟨hnd, nodup_freshOf, ?_⟩
        intro b hb c hc he
        exact (mem_freshOf.mp hc).2 (he ▸ hb)
      · exact List.mem_append_left _ hx
      · intro y hy
        rcases List.mem_append.mp hy with hy | hy
        · exact hre y hy
        · obtain ⟨u, hu, s, hs, hus⟩ := mem_images.mp (mem_freshOf.mp hy).1
          have hu' : Reach gens x u := hre u (List.mem_append_right _ hu)
          rcases hus with rfl | rfl
          · exact Reach.step hu' hs
          · exact Reach.stepInv hu' hs
      · intro y hy s hs
        have key : ∀ z : Fin n, z ∈ images gens (a :: fr) →
            z ∈ old ++ a :: fr ++ freshOf (old ++ a :: fr) (images gens (a :: fr)) := by
          intro z hz
          by_cases hin : z ∈ old ++ a :: fr
          · exact List.mem_append_left _ hin
          · exact List.mem_append_right _ (mem_freshOf.mpr ⟨hz, hin⟩)
        rcases List.mem_append.mp hy with hy | hy
        · exact ⟨List.mem_append_left _ (hcl y hy s hs).1,
            List.mem_append_left _ (hcl y hy s hs).2⟩
        · exact ⟨key _ (mem_images.mpr ⟨y, hy, s, hs, Or.inl rfl⟩),
            key _ (mem_images.mpr ⟨y, hy, s, hs, Or.inr rfl⟩)⟩

/-- **The computed orbit is exactly the reachable set.** -/
public theorem orbitOf_spec {gens : List (Perm n)} {x : Fin n} {fuel : Nat} {L : List (Fin n)}
    (h : orbitOf gens x fuel = some L) :
    L.Nodup ∧ ∀ y : Fin n, y ∈ L ↔ Reach gens x y := by
  have hre : ∀ y ∈ ([] : List (Fin n)) ++ [x], Reach gens x y := by
    intro y hy
    rw [List.nil_append, List.mem_singleton] at hy
    exact hy ▸ Reach.base
  have hcl : ∀ y ∈ ([] : List (Fin n)), ∀ s ∈ gens,
      s.toFun y ∈ ([] : List (Fin n)) ++ [x] ∧ s.invFun y ∈ ([] : List (Fin n)) ++ [x] := by
    intro y hy
    exact absurd hy (by simp)
  have hs := orbitSat_spec gens x fuel [] [x] L (by simp) (by simp) hre hcl h
  refine ⟨hs.1, fun y => Iff.intro (fun hy => hs.2.2.1 y hy) (fun hy => ?_)⟩
  induction hy with
  | base => exact hs.2.1
  | step _ hs' ih => exact (hs.2.2.2 _ ih _ hs').1
  | stepInv _ hs' ih => exact (hs.2.2.2 _ ih _ hs').2

end Perm

/-! ## Orbit-stabilizer

`|G| = |orbit| * |stabilizer|`. This is the identity behind `T43`, where the
orbit map `Aut / Aut(W) -> Ob(Atl)` is a bijection, and hence behind `T28`,
`T49` and `T60`. The proof partitions `G` into the fibres of `g |-> g x`: the
fibre over `y` is the translate of the stabilizer by any element carrying `x`
to `y`, and the orbit indexes those fibres without repetition. -/

namespace Perm

namespace Subgroup

open ListAux

variable {n : Nat}

/-- The orbit of `x` under `G`, deduplicated so that it indexes the fibres. -/
@[expose] public def orbit (G : Subgroup n) (x : Fin n) : List (Fin n) :=
  dedup (G.carrier.map fun g => g.toFun x)

/-- The stabilizer of `x` in `G`. -/
@[expose] public def stabilizer (G : Subgroup n) (x : Fin n) : List (Perm n) :=
  G.carrier.filter fun g => decide (g.toFun x = x)

public theorem nodup_orbit (G : Subgroup n) (x : Fin n) : (G.orbit x).Nodup := nodup_dedup

public theorem mem_orbit {G : Subgroup n} {x y : Fin n} :
    y ∈ G.orbit x ↔ ∃ g ∈ G.carrier, g.toFun x = y := by
  rw [orbit, mem_dedup, List.mem_map]

public theorem mem_stabilizer {G : Subgroup n} {x : Fin n} {g : Perm n} :
    g ∈ G.stabilizer x ↔ g ∈ G.carrier ∧ g.toFun x = x := by
  rw [stabilizer, List.mem_filter]
  constructor
  · exact fun h => ⟨h.1, of_decide_eq_true h.2⟩
  · exact fun h => ⟨h.1, decide_eq_true h.2⟩

public theorem nodup_stabilizer (G : Subgroup n) (x : Fin n) : (G.stabilizer x).Nodup :=
  List.Pairwise.filter _ G.nodup

/-- Each fibre of the orbit map has exactly the size of the stabilizer:
translation by a chosen `t` with `t x = y` carries the stabilizer onto the
fibre over `y`, injectively because left translation cancels. -/
public theorem countP_fibre_eq (G : Subgroup n) (x y : Fin n) (hy : y ∈ G.orbit x) :
    G.carrier.countP (fun g => decide (g.toFun x = y)) = (G.stabilizer x).length := by
  obtain ⟨t, ht, hty⟩ := mem_orbit.mp hy
  have hlen : ((G.stabilizer x).map fun s => t.comp s).length = (G.stabilizer x).length := by
    simp
  rw [List.countP_eq_length_filter, ← hlen]
  refine length_eq_of_mem_iff (List.Pairwise.filter _ G.nodup) ?_ ?_
  · exact List.Pairwise.map _ (fun a b hab he => hab (comp_left_cancel he)) (nodup_stabilizer G x)
  · intro g
    rw [List.mem_filter, List.mem_map]
    constructor
    · rintro ⟨hg, hgy⟩
      refine ⟨t.inv.comp g, mem_stabilizer.mpr ⟨G.comp_mem _ (G.inv_mem t ht) _ hg, ?_⟩, ?_⟩
      · rw [comp_apply, inv_apply, of_decide_eq_true hgy, ← hty, t.left_inv]
      · rw [← comp_assoc, comp_inv, one_comp]
    · rintro ⟨s, hs, rfl⟩
      obtain ⟨hsc, hsx⟩ := mem_stabilizer.mp hs
      exact ⟨G.comp_mem _ ht _ hsc, decide_eq_true (by rw [comp_apply, hsx, hty])⟩

/-- **Orbit-stabilizer.** -/
public theorem orbit_stabilizer (G : Subgroup n) (x : Fin n) :
    G.order = (G.orbit x).length * (G.stabilizer x).length := by
  have hcov : ∀ g ∈ G.carrier, g.toFun x ∈ G.orbit x := fun g hg => mem_orbit.mpr ⟨g, hg, rfl⟩
  rw [order, length_eq_sum_fibres (fun g : Perm n => g.toFun x) (nodup_orbit G x) hcov,
    List.map_congr_left (fun y hy => countP_fibre_eq G x y hy), sum_map_const]

/-- The computed orbit of the generators and the orbit of the closed-up group
are the same set, so the cheap breadth-first list may be substituted for the
expensive one in `orbit_stabilizer`. -/
public theorem length_orbitOf_eq {gens : List (Perm n)} {fuel fuelOrb : Nat}
    {L : List (Perm n)} {O : List (Fin n)} {x : Fin n} {G : Subgroup n}
    (hG : G.carrier = L) (hc : closure gens fuel = some L)
    (ho : orbitOf gens x fuelOrb = some O) :
    O.length = (G.orbit x).length := by
  refine length_eq_of_mem_iff (orbitOf_spec ho).1 (nodup_orbit _ x) fun y => ?_
  rw [(orbitOf_spec ho).2 y, Reach.iff_exists_gen, mem_orbit]
  constructor
  · rintro ⟨g, hg, hgx⟩
    refine ⟨g, ?_, hgx⟩
    rw [hG]
    exact ((closure_spec hc).2.2 g).mpr hg
  · rintro ⟨g, hg, hgx⟩
    rw [hG] at hg
    exact ⟨g, ((closure_spec hc).2.2 g).mp hg, hgx⟩

/-- Orbit-stabilizer in the form a later module can evaluate: the group order
is read off a breadth-first orbit and the stabilizer of one point, neither of
which needs the group listed twice. -/
public theorem order_eq_orbitOf_mul_stabilizer {gens : List (Perm n)} {fuel fuelOrb : Nat}
    {L : List (Perm n)} {O : List (Fin n)} {x : Fin n} {G : Subgroup n}
    (hG : G.carrier = L) (hc : closure gens fuel = some L)
    (ho : orbitOf gens x fuelOrb = some O) :
    G.order = O.length * (G.stabilizer x).length := by
  rw [length_orbitOf_eq hG hc ho]
  exact orbit_stabilizer G x

end Subgroup

end Perm

/-! ## Worked example

The module's own falsification check. `Sym(3)`, presented by a `3`-cycle and a
transposition exactly as `D21` presents `Aut` by reflections, is closed in the
kernel and its orbit-stabilizer identity `6 = 3 * 2` is *evaluated*. A
saturation that stopped early and returned a proper subgroup, a `ClosedUnder`
that was not closed, or an orbit that missed a point would fail here rather
than pass silently; without it every theorem above would be vacuously safe. -/

namespace Perm

/-- The `3`-cycle `i |-> i + 1`. -/
@[expose] public def cycleThree : Perm 3 where
  toFun i := ⟨(i.val + 1) % 3, Nat.mod_lt _ (by decide)⟩
  invFun i := ⟨(i.val + 2) % 3, Nat.mod_lt _ (by decide)⟩
  left_inv := by decide
  right_inv := by decide

/-- The transposition exchanging `0` and `1`. -/
@[expose] public def swapThree : Perm 3 where
  toFun i := if i.val = 0 then ⟨1, by decide⟩ else if i.val = 1 then ⟨0, by decide⟩ else i
  invFun i := if i.val = 0 then ⟨1, by decide⟩ else if i.val = 1 then ⟨0, by decide⟩ else i
  left_inv := by decide
  right_inv := by decide

@[expose] public def symThreeGens : List (Perm 3) := [cycleThree, swapThree]

/-- Naming the closure's output without transcribing it. The `getD` default is
never reached, and `symThree_closure` is what says so: if the saturation ran out
of fuel this would be `[]`, `none = some []` would not be `rfl`, and the check
would fail rather than quietly build a group out of the default. -/
@[expose] public def symThreeList : List (Perm 3) := (closure symThreeGens 8).getD []

public theorem symThree_closure : closure symThreeGens 8 = some symThreeList := rfl

@[expose] public def symThree : Subgroup 3 :=
  Subgroup.ofClosure symThreeGens 8 symThreeList symThree_closure

/-- The orbit of `0` reached from the generators alone, without listing the
group. -/
@[expose] public def symThreeOrbit : List (Fin 3) := (orbitOf symThreeGens (0 : Fin 3) 8).getD []

public theorem symThree_orbitOf : orbitOf symThreeGens (0 : Fin 3) 8 = some symThreeOrbit := rfl

public theorem symThree_order : symThree.order = 6 := by decide

public theorem symThree_orbit_length : symThreeOrbit.length = 3 := by decide

public theorem symThree_stabilizer_length : (symThree.stabilizer 0).length = 2 := by decide

/-- `6 = 3 * 2` read off the general theorem applied to computed data, not
evaluated a second time. -/
public theorem symThree_orbit_stabilizer : symThree.order = 3 * 2 := by
  have h := Subgroup.order_eq_orbitOf_mul_stabilizer (G := symThree) rfl symThree_closure
    symThree_orbitOf
  rwa [symThree_orbit_length, symThree_stabilizer_length] at h

end Perm

end UorAtlas.Prelude
