module
import LexLeanExample.Prelude.Algebra
#print axioms UorAtlas.LexLeanInternal.decl1096
#print axioms UorAtlas.LexLeanInternal.decl1187
#print axioms UorAtlas.LexLeanInternal.decl1591
#print axioms UorAtlas.LexLeanInternal.decl243
#print axioms UorAtlas.LexLeanInternal.decl812
#print axioms UorAtlas.LexLeanInternal.decl970
#print axioms UorAtlas.Prelude.AddCommGroup
#print axioms UorAtlas.Prelude.AddCommGroup.add
#print axioms UorAtlas.Prelude.AddCommGroup.add_assoc
#print axioms UorAtlas.Prelude.AddCommGroup.add_comm
#print axioms UorAtlas.Prelude.AddCommGroup.add_neg
#print axioms UorAtlas.Prelude.AddCommGroup.add_zero
#print axioms UorAtlas.Prelude.AddCommGroup.casesOn
#print axioms UorAtlas.Prelude.AddCommGroup.ctorIdx
#print axioms UorAtlas.Prelude.AddCommGroup.mk
#print axioms UorAtlas.Prelude.AddCommGroup.mk.noConfusion
#print axioms UorAtlas.Prelude.AddCommGroup.neg
#print axioms UorAtlas.Prelude.AddCommGroup.noConfusion
#print axioms UorAtlas.Prelude.AddCommGroup.noConfusionType
#print axioms UorAtlas.Prelude.AddCommGroup.rec
#print axioms UorAtlas.Prelude.AddCommGroup.recOn
#print axioms UorAtlas.Prelude.AddCommGroup.zero
#print axioms UorAtlas.Prelude.CommRing
#print axioms UorAtlas.Prelude.CommRing.casesOn
#print axioms UorAtlas.Prelude.CommRing.ctorIdx
#print axioms UorAtlas.Prelude.CommRing.left_distrib
#print axioms UorAtlas.Prelude.CommRing.mk
#print axioms UorAtlas.Prelude.CommRing.mk.noConfusion
#print axioms UorAtlas.Prelude.CommRing.mul
#print axioms UorAtlas.Prelude.CommRing.mul_assoc
#print axioms UorAtlas.Prelude.CommRing.mul_comm
#print axioms UorAtlas.Prelude.CommRing.noConfusion
#print axioms UorAtlas.Prelude.CommRing.noConfusionType
#print axioms UorAtlas.Prelude.CommRing.one
#print axioms UorAtlas.Prelude.CommRing.one_mul
#print axioms UorAtlas.Prelude.CommRing.rec
#print axioms UorAtlas.Prelude.CommRing.recOn
#print axioms UorAtlas.Prelude.CommRing.toAddCommGroup
#print axioms UorAtlas.Prelude.Field
#print axioms UorAtlas.Prelude.Field.casesOn
#print axioms UorAtlas.Prelude.Field.ctorIdx
#print axioms UorAtlas.Prelude.Field.inv
#print axioms UorAtlas.Prelude.Field.mk
#print axioms UorAtlas.Prelude.Field.mk.noConfusion
#print axioms UorAtlas.Prelude.Field.mul_inv_cancel
#print axioms UorAtlas.Prelude.Field.noConfusion
#print axioms UorAtlas.Prelude.Field.noConfusionType
#print axioms UorAtlas.Prelude.Field.one_ne_zero
#print axioms UorAtlas.Prelude.Field.rec
#print axioms UorAtlas.Prelude.Field.recOn
#print axioms UorAtlas.Prelude.Field.toCommRing
#print axioms UorAtlas.Prelude.RingHom
#print axioms UorAtlas.Prelude.RingHom.casesOn
#print axioms UorAtlas.Prelude.RingHom.ctorIdx
#print axioms UorAtlas.Prelude.RingHom.map_add
#print axioms UorAtlas.Prelude.RingHom.map_mul
#print axioms UorAtlas.Prelude.RingHom.map_one
#print axioms UorAtlas.Prelude.RingHom.mk
#print axioms UorAtlas.Prelude.RingHom.mk.inj
#print axioms UorAtlas.Prelude.RingHom.mk.injEq
#print axioms UorAtlas.Prelude.RingHom.mk.noConfusion
#print axioms UorAtlas.Prelude.RingHom.mk.sizeOf_spec
#print axioms UorAtlas.Prelude.RingHom.noConfusion
#print axioms UorAtlas.Prelude.RingHom.noConfusionType
#print axioms UorAtlas.Prelude.RingHom.rec
#print axioms UorAtlas.Prelude.RingHom.recOn
#print axioms UorAtlas.Prelude.RingHom.toFun
#print axioms UorAtlas.Prelude.add_left_cancel
#print axioms UorAtlas.Prelude.mul_one
#print axioms UorAtlas.Prelude.mul_zero
#print axioms UorAtlas.Prelude.neg_add_cancel
#print axioms UorAtlas.Prelude.neg_neg
#print axioms UorAtlas.Prelude.zero_add
#print axioms UorAtlas.Prelude.zero_mul
