module
import LexLeanExample.Census
#print axioms UorAtlas.Census.above
#print axioms UorAtlas.Census.adjMask
#print axioms UorAtlas.Census.adjMask.eq_1
#print axioms UorAtlas.Census.adjN_of_dot
#print axioms UorAtlas.Census.allRange
#print axioms UorAtlas.Census.allRange_true
#print axioms UorAtlas.Census.bessel
#print axioms UorAtlas.Census.bitsFrom
#print axioms UorAtlas.Census.bitsFrom.match_1
#print axioms UorAtlas.Census.bitsOf
#print axioms UorAtlas.Census.blkA
#print axioms UorAtlas.Census.blkAll
#print axioms UorAtlas.Census.blkAt
#print axioms UorAtlas.Census.blkB
#print axioms UorAtlas.Census.blkC
#print axioms UorAtlas.Census.blkCode
#print axioms UorAtlas.Census.blkCount
#print axioms UorAtlas.Census.blkCountFrom
#print axioms UorAtlas.Census.blkCountRange
#print axioms UorAtlas.Census.blkCountUpTo
#print axioms UorAtlas.Census.blkCountUpTo.match_1
#print axioms UorAtlas.Census.blkCountUpTo_add
#print axioms UorAtlas.Census.blkD
#print axioms UorAtlas.Census.blkD16
#print axioms UorAtlas.Census.blkEntryOK
#print axioms UorAtlas.Census.blkEntryOK.eq_1
#print axioms UorAtlas.Census.blkEntry_true
#print axioms UorAtlas.Census.blkExhibit
#print axioms UorAtlas.Census.blkFind
#print axioms UorAtlas.Census.blkIdx
#print axioms UorAtlas.Census.blkInj
#print axioms UorAtlas.Census.blkLt
#print axioms UorAtlas.Census.blkMono
#print axioms UorAtlas.Census.blkPack
#print axioms UorAtlas.Census.blkRange
#print axioms UorAtlas.Census.blkRange0
#print axioms UorAtlas.Census.blkRange1
#print axioms UorAtlas.Census.blkRange10
#print axioms UorAtlas.Census.blkRange11
#print axioms UorAtlas.Census.blkRange12
#print axioms UorAtlas.Census.blkRange13
#print axioms UorAtlas.Census.blkRange14
#print axioms UorAtlas.Census.blkRange15
#print axioms UorAtlas.Census.blkRange16
#print axioms UorAtlas.Census.blkRange17
#print axioms UorAtlas.Census.blkRange18
#print axioms UorAtlas.Census.blkRange19
#print axioms UorAtlas.Census.blkRange2
#print axioms UorAtlas.Census.blkRange20
#print axioms UorAtlas.Census.blkRange21
#print axioms UorAtlas.Census.blkRange22
#print axioms UorAtlas.Census.blkRange23
#print axioms UorAtlas.Census.blkRange3
#print axioms UorAtlas.Census.blkRange4
#print axioms UorAtlas.Census.blkRange5
#print axioms UorAtlas.Census.blkRange6
#print axioms UorAtlas.Census.blkRange7
#print axioms UorAtlas.Census.blkRange8
#print axioms UorAtlas.Census.blkRange9
#print axioms UorAtlas.Census.blkUpTo
#print axioms UorAtlas.Census.blkUpTo_add
#print axioms UorAtlas.Census.blkUpTo_true
#print axioms UorAtlas.Census.blkWin0
#print axioms UorAtlas.Census.blkWin1
#print axioms UorAtlas.Census.blkWin10
#print axioms UorAtlas.Census.blkWin11
#print axioms UorAtlas.Census.blkWin12
#print axioms UorAtlas.Census.blkWin13
#print axioms UorAtlas.Census.blkWin14
#print axioms UorAtlas.Census.blkWin15
#print axioms UorAtlas.Census.blkWin16
#print axioms UorAtlas.Census.blkWin17
#print axioms UorAtlas.Census.blkWin18
#print axioms UorAtlas.Census.blkWin19
#print axioms UorAtlas.Census.blkWin2
#print axioms UorAtlas.Census.blkWin20
#print axioms UorAtlas.Census.blkWin3
#print axioms UorAtlas.Census.blkWin4
#print axioms UorAtlas.Census.blkWin5
#print axioms UorAtlas.Census.blkWin6
#print axioms UorAtlas.Census.blkWin7
#print axioms UorAtlas.Census.blkWin8
#print axioms UorAtlas.Census.blkWin9
#print axioms UorAtlas.Census.blkWords
#print axioms UorAtlas.Census.block_of_quad
#print axioms UorAtlas.Census.block_of_quadOK
#print axioms UorAtlas.Census.classSet_quadSet
#print axioms UorAtlas.Census.classSet_singleton
#print axioms UorAtlas.Census.comb4
#print axioms UorAtlas.Census.commonAdj
#print axioms UorAtlas.Census.commonAdj.eq_1
#print axioms UorAtlas.Census.countB
#print axioms UorAtlas.Census.countC
#print axioms UorAtlas.Census.countD
#print axioms UorAtlas.Census.countD.match_1
#print axioms UorAtlas.Census.covered
#print axioms UorAtlas.Census.covered.eq_1
#print axioms UorAtlas.Census.dot_bessel_left
#print axioms UorAtlas.Census.dot_comb4_left
#print axioms UorAtlas.Census.dot_comb4_right
#print axioms UorAtlas.Census.dot_of_adjN
#print axioms UorAtlas.Census.dot_of_mem_arow
#print axioms UorAtlas.Census.dot_self_zero
#print axioms UorAtlas.Census.dot_tri
#print axioms UorAtlas.Census.fin4
#print axioms UorAtlas.Census.fullMask
#print axioms UorAtlas.Census.inTable
#print axioms UorAtlas.Census.inTable.eq_1
#print axioms UorAtlas.Census.isLeastQuad
#print axioms UorAtlas.Census.mem_arow_of_dot
#print axioms UorAtlas.Census.mem_quadSet
#print axioms UorAtlas.Census.mem_quadSet_iff_inSpan
#print axioms UorAtlas.Census.mem_quadSet_of_inSpan
#print axioms UorAtlas.Census.orthMask
#print axioms UorAtlas.Census.parseval_of_inSpan
#print axioms UorAtlas.Census.quadBasis
#print axioms UorAtlas.Census.quadClosure
#print axioms UorAtlas.Census.quadClosure.eq_1
#print axioms UorAtlas.Census.quadIdx
#print axioms UorAtlas.Census.quadIdx.match_1
#print axioms UorAtlas.Census.quadOK
#print axioms UorAtlas.Census.quadOK.eq_1
#print axioms UorAtlas.Census.quadSet
#print axioms UorAtlas.Census.quadSet.eq_1
#print axioms UorAtlas.Census.quadSet_eq
#print axioms UorAtlas.Census.quad_gram
#print axioms UorAtlas.Census.quad_in_table
#print axioms UorAtlas.Census.recon_of_mem_quadSet
#print axioms UorAtlas.Census.recon_of_parseval
#print axioms UorAtlas.Census.rowBit
#print axioms UorAtlas.Census.rowBit_zero
#print axioms UorAtlas.Census.shiftOne_eq
#print axioms UorAtlas.Census.sq_of_adj
#print axioms UorAtlas.Census.sumInt4
#print axioms UorAtlas.Census.sweepA
#print axioms UorAtlas.Census.sweepAll
#print axioms UorAtlas.Census.sweepB
#print axioms UorAtlas.Census.sweepC
#print axioms UorAtlas.Census.sweepD
#print axioms UorAtlas.Census.sweepRange
#print axioms UorAtlas.Census.sweepUpTo
#print axioms UorAtlas.Census.sweepUpTo_add
#print axioms UorAtlas.Census.sweepUpTo_true
#print axioms UorAtlas.Census.sweepWin0
#print axioms UorAtlas.Census.sweepWin1
#print axioms UorAtlas.Census.sweepWin10
#print axioms UorAtlas.Census.sweepWin11
#print axioms UorAtlas.Census.sweepWin12
#print axioms UorAtlas.Census.sweepWin13
#print axioms UorAtlas.Census.sweepWin14
#print axioms UorAtlas.Census.sweepWin15
#print axioms UorAtlas.Census.sweepWin16
#print axioms UorAtlas.Census.sweepWin17
#print axioms UorAtlas.Census.sweepWin18
#print axioms UorAtlas.Census.sweepWin19
#print axioms UorAtlas.Census.sweepWin2
#print axioms UorAtlas.Census.sweepWin20
#print axioms UorAtlas.Census.sweepWin21
#print axioms UorAtlas.Census.sweepWin3
#print axioms UorAtlas.Census.sweepWin4
#print axioms UorAtlas.Census.sweepWin5
#print axioms UorAtlas.Census.sweepWin6
#print axioms UorAtlas.Census.sweepWin7
#print axioms UorAtlas.Census.sweepWin8
#print axioms UorAtlas.Census.sweepWin9
#print axioms UorAtlas.Group.arow.eq_1
#print axioms UorAtlas.LexLeanInternal.decl1019
#print axioms UorAtlas.LexLeanInternal.decl1050
#print axioms UorAtlas.LexLeanInternal.decl1078
#print axioms UorAtlas.LexLeanInternal.decl1081
#print axioms UorAtlas.LexLeanInternal.decl109
#print axioms UorAtlas.LexLeanInternal.decl1095
#print axioms UorAtlas.LexLeanInternal.decl1098
#print axioms UorAtlas.LexLeanInternal.decl1116
#print axioms UorAtlas.LexLeanInternal.decl1118
#print axioms UorAtlas.LexLeanInternal.decl1132
#print axioms UorAtlas.LexLeanInternal.decl1141
#print axioms UorAtlas.LexLeanInternal.decl1167
#print axioms UorAtlas.LexLeanInternal.decl1178
#print axioms UorAtlas.LexLeanInternal.decl1203
#print axioms UorAtlas.LexLeanInternal.decl1204
#print axioms UorAtlas.LexLeanInternal.decl1209
#print axioms UorAtlas.LexLeanInternal.decl1216
#print axioms UorAtlas.LexLeanInternal.decl1230
#print axioms UorAtlas.LexLeanInternal.decl1241
#print axioms UorAtlas.LexLeanInternal.decl1242
#print axioms UorAtlas.LexLeanInternal.decl1243
#print axioms UorAtlas.LexLeanInternal.decl1244
#print axioms UorAtlas.LexLeanInternal.decl1248
#print axioms UorAtlas.LexLeanInternal.decl1311
#print axioms UorAtlas.LexLeanInternal.decl1318
#print axioms UorAtlas.LexLeanInternal.decl132
#print axioms UorAtlas.LexLeanInternal.decl1326
#print axioms UorAtlas.LexLeanInternal.decl1328
#print axioms UorAtlas.LexLeanInternal.decl1366
#print axioms UorAtlas.LexLeanInternal.decl1378
#print axioms UorAtlas.LexLeanInternal.decl1385
#print axioms UorAtlas.LexLeanInternal.decl1388
#print axioms UorAtlas.LexLeanInternal.decl1392
#print axioms UorAtlas.LexLeanInternal.decl1409
#print axioms UorAtlas.LexLeanInternal.decl1449
#print axioms UorAtlas.LexLeanInternal.decl1459
#print axioms UorAtlas.LexLeanInternal.decl1483
#print axioms UorAtlas.LexLeanInternal.decl1487
#print axioms UorAtlas.LexLeanInternal.decl1490
#print axioms UorAtlas.LexLeanInternal.decl1503
#print axioms UorAtlas.LexLeanInternal.decl1508
#print axioms UorAtlas.LexLeanInternal.decl1521
#print axioms UorAtlas.LexLeanInternal.decl1525
#print axioms UorAtlas.LexLeanInternal.decl1530
#print axioms UorAtlas.LexLeanInternal.decl1540
#print axioms UorAtlas.LexLeanInternal.decl1571
#print axioms UorAtlas.LexLeanInternal.decl1574
#print axioms UorAtlas.LexLeanInternal.decl1595
#print axioms UorAtlas.LexLeanInternal.decl1601
#print axioms UorAtlas.LexLeanInternal.decl1635
#print axioms UorAtlas.LexLeanInternal.decl1636
#print axioms UorAtlas.LexLeanInternal.decl1688
#print axioms UorAtlas.LexLeanInternal.decl1704
#print axioms UorAtlas.LexLeanInternal.decl1709
#print axioms UorAtlas.LexLeanInternal.decl1711
#print axioms UorAtlas.LexLeanInternal.decl1712
#print axioms UorAtlas.LexLeanInternal.decl182
#print axioms UorAtlas.LexLeanInternal.decl189
#print axioms UorAtlas.LexLeanInternal.decl210
#print axioms UorAtlas.LexLeanInternal.decl220
#print axioms UorAtlas.LexLeanInternal.decl225
#print axioms UorAtlas.LexLeanInternal.decl230
#print axioms UorAtlas.LexLeanInternal.decl248
#print axioms UorAtlas.LexLeanInternal.decl26
#print axioms UorAtlas.LexLeanInternal.decl263
#print axioms UorAtlas.LexLeanInternal.decl264
#print axioms UorAtlas.LexLeanInternal.decl266
#print axioms UorAtlas.LexLeanInternal.decl29
#print axioms UorAtlas.LexLeanInternal.decl30
#print axioms UorAtlas.LexLeanInternal.decl307
#print axioms UorAtlas.LexLeanInternal.decl321
#print axioms UorAtlas.LexLeanInternal.decl325
#print axioms UorAtlas.LexLeanInternal.decl359
#print axioms UorAtlas.LexLeanInternal.decl376
#print axioms UorAtlas.LexLeanInternal.decl387
#print axioms UorAtlas.LexLeanInternal.decl392
#print axioms UorAtlas.LexLeanInternal.decl393
#print axioms UorAtlas.LexLeanInternal.decl399
#print axioms UorAtlas.LexLeanInternal.decl401
#print axioms UorAtlas.LexLeanInternal.decl402
#print axioms UorAtlas.LexLeanInternal.decl407
#print axioms UorAtlas.LexLeanInternal.decl410
#print axioms UorAtlas.LexLeanInternal.decl425
#print axioms UorAtlas.LexLeanInternal.decl443
#print axioms UorAtlas.LexLeanInternal.decl471
#print axioms UorAtlas.LexLeanInternal.decl474
#print axioms UorAtlas.LexLeanInternal.decl478
#print axioms UorAtlas.LexLeanInternal.decl486
#print axioms UorAtlas.LexLeanInternal.decl493
#print axioms UorAtlas.LexLeanInternal.decl51
#print axioms UorAtlas.LexLeanInternal.decl512
#print axioms UorAtlas.LexLeanInternal.decl522
#print axioms UorAtlas.LexLeanInternal.decl54
#print axioms UorAtlas.LexLeanInternal.decl540
#print axioms UorAtlas.LexLeanInternal.decl546
#print axioms UorAtlas.LexLeanInternal.decl547
#print axioms UorAtlas.LexLeanInternal.decl575
#print axioms UorAtlas.LexLeanInternal.decl578
#print axioms UorAtlas.LexLeanInternal.decl582
#print axioms UorAtlas.LexLeanInternal.decl623
#print axioms UorAtlas.LexLeanInternal.decl668
#print axioms UorAtlas.LexLeanInternal.decl672
#print axioms UorAtlas.LexLeanInternal.decl675
#print axioms UorAtlas.LexLeanInternal.decl676
#print axioms UorAtlas.LexLeanInternal.decl683
#print axioms UorAtlas.LexLeanInternal.decl692
#print axioms UorAtlas.LexLeanInternal.decl706
#print axioms UorAtlas.LexLeanInternal.decl726
#print axioms UorAtlas.LexLeanInternal.decl736
#print axioms UorAtlas.LexLeanInternal.decl747
#print axioms UorAtlas.LexLeanInternal.decl755
#print axioms UorAtlas.LexLeanInternal.decl764
#print axioms UorAtlas.LexLeanInternal.decl771
#print axioms UorAtlas.LexLeanInternal.decl776
#print axioms UorAtlas.LexLeanInternal.decl79
#print axioms UorAtlas.LexLeanInternal.decl832
#print axioms UorAtlas.LexLeanInternal.decl850
#print axioms UorAtlas.LexLeanInternal.decl860
#print axioms UorAtlas.LexLeanInternal.decl88
#print axioms UorAtlas.LexLeanInternal.decl893
#print axioms UorAtlas.LexLeanInternal.decl904
#print axioms UorAtlas.LexLeanInternal.decl908
#print axioms UorAtlas.LexLeanInternal.decl915
#print axioms UorAtlas.LexLeanInternal.decl920
#print axioms UorAtlas.LexLeanInternal.decl93
#print axioms UorAtlas.LexLeanInternal.decl933
#print axioms UorAtlas.LexLeanInternal.decl952
#print axioms UorAtlas.LexLeanInternal.decl97
#print axioms UorAtlas.LexLeanInternal.decl981
#print axioms UorAtlas.LexLeanInternal.decl997
#print axioms UorAtlas.Prelude.Bitset.inter.eq_1
#print axioms UorAtlas.Prelude.Bitset.ofNat.eq_1
#print axioms UorAtlas.Prelude.Bitset.toNat.eq_1
#print axioms UorAtlas.Prelude.Bitset.union.eq_1
