module
import LexLeanExample.Closure
#print axioms UorAtlas.Closure.T22a
#print axioms UorAtlas.Closure.T23
#print axioms UorAtlas.Closure.bitset_eq_of_subset_card
#print axioms UorAtlas.Closure.frameId_frm
#print axioms UorAtlas.Closure.frameIds
#print axioms UorAtlas.Closure.frameIds.eq_1
#print axioms UorAtlas.Closure.frameIds_length
#print axioms UorAtlas.Closure.frameIds_nodup
#print axioms UorAtlas.Closure.frameSupport
#print axioms UorAtlas.Closure.frame_census_complete
#print axioms UorAtlas.Closure.frm_orthTo
#print axioms UorAtlas.Closure.mateAll
#print axioms UorAtlas.Closure.mateEntryOK
#print axioms UorAtlas.Closure.mateEntryOK.eq_1
#print axioms UorAtlas.Closure.mateEntry_true
#print axioms UorAtlas.Closure.mateIndex
#print axioms UorAtlas.Closure.mateIndex_involutive
#print axioms UorAtlas.Closure.mateIndex_lt
#print axioms UorAtlas.Closure.mateIndex_ne
#print axioms UorAtlas.Closure.mateRange
#print axioms UorAtlas.Closure.mateRange.eq_1
#print axioms UorAtlas.Closure.mateRange.eq_2
#print axioms UorAtlas.Closure.mateRange.eq_def
#print axioms UorAtlas.Closure.mateRange_true
#print axioms UorAtlas.Closure.mem_frameIds
#print axioms UorAtlas.Closure.mem_fullMask
#print axioms UorAtlas.Closure.mem_orthFold
#print axioms UorAtlas.Closure.mem_orthTo
#print axioms UorAtlas.Closure.modGramAll
#print axioms UorAtlas.Closure.modGramOK
#print axioms UorAtlas.Closure.modGramOK.eq_1
#print axioms UorAtlas.Closure.modGram_true
#print axioms UorAtlas.Closure.orthFold
#print axioms UorAtlas.Closure.orthFold.eq_1
#print axioms UorAtlas.Closure.orthFold.eq_2
#print axioms UorAtlas.Closure.orthFold.eq_def
#print axioms UorAtlas.Closure.orthFold.match_1
#print axioms UorAtlas.Closure.orthTo
#print axioms UorAtlas.Closure.orthTo.eq_1
#print axioms UorAtlas.Closure.orthTo_blkAt
#print axioms UorAtlas.Closure.orthTo_block
#print axioms UorAtlas.Closure.orthTo_eq_of_frm
#print axioms UorAtlas.Closure.orthTo_involutive
#print axioms UorAtlas.Closure.orthTo_ne
#print axioms UorAtlas.Closure.prime4099
#print axioms UorAtlas.Closure.prime4099Check
#print axioms UorAtlas.Closure.prime4099Check_true
#print axioms UorAtlas.LexLeanInternal.decl1026
#print axioms UorAtlas.LexLeanInternal.decl1082
#print axioms UorAtlas.LexLeanInternal.decl1099
#print axioms UorAtlas.LexLeanInternal.decl1140
#print axioms UorAtlas.LexLeanInternal.decl1291
#print axioms UorAtlas.LexLeanInternal.decl1402
#print axioms UorAtlas.LexLeanInternal.decl1565
#print axioms UorAtlas.LexLeanInternal.decl233
#print axioms UorAtlas.LexLeanInternal.decl4
#print axioms UorAtlas.LexLeanInternal.decl506
#print axioms UorAtlas.LexLeanInternal.decl659
#print axioms UorAtlas.LexLeanInternal.decl670
#print axioms UorAtlas.LexLeanInternal.decl7
#print axioms UorAtlas.LexLeanInternal.decl704
#print axioms UorAtlas.LexLeanInternal.decl709
#print axioms UorAtlas.LexLeanInternal.decl753
#print axioms UorAtlas.LexLeanInternal.decl784
#print axioms UorAtlas.LexLeanInternal.decl912
#print axioms UorAtlas.LexLeanInternal.decl939
