module
import LexLeanExample.Functor
#print axioms UorAtlas.Functor.Across
#print axioms UorAtlas.Functor.Across.app
#print axioms UorAtlas.Functor.Across.casesOn
#print axioms UorAtlas.Functor.Across.ctorIdx
#print axioms UorAtlas.Functor.Across.mk
#print axioms UorAtlas.Functor.Across.mk.inj
#print axioms UorAtlas.Functor.Across.mk.injEq
#print axioms UorAtlas.Functor.Across.mk.noConfusion
#print axioms UorAtlas.Functor.Across.mk.sizeOf_spec
#print axioms UorAtlas.Functor.Across.noConfusion
#print axioms UorAtlas.Functor.Across.noConfusionType
#print axioms UorAtlas.Functor.Across.ofFamily
#print axioms UorAtlas.Functor.Across.rec
#print axioms UorAtlas.Functor.Across.recOn
#print axioms UorAtlas.Functor.Across.same
#print axioms UorAtlas.Functor.Addr
#print axioms UorAtlas.Functor.Assignments
#print axioms UorAtlas.Functor.Assignments.aMap
#print axioms UorAtlas.Functor.Assignments.aObj
#print axioms UorAtlas.Functor.Assignments.casesOn
#print axioms UorAtlas.Functor.Assignments.ctorIdx
#print axioms UorAtlas.Functor.Assignments.kMap
#print axioms UorAtlas.Functor.Assignments.kObj
#print axioms UorAtlas.Functor.Assignments.mk
#print axioms UorAtlas.Functor.Assignments.mk.inj
#print axioms UorAtlas.Functor.Assignments.mk.injEq
#print axioms UorAtlas.Functor.Assignments.mk.noConfusion
#print axioms UorAtlas.Functor.Assignments.mk.sizeOf_spec
#print axioms UorAtlas.Functor.Assignments.noConfusion
#print axioms UorAtlas.Functor.Assignments.noConfusionType
#print axioms UorAtlas.Functor.Assignments.pMap
#print axioms UorAtlas.Functor.Assignments.pObj
#print axioms UorAtlas.Functor.Assignments.qMap
#print axioms UorAtlas.Functor.Assignments.qObj
#print axioms UorAtlas.Functor.Assignments.rec
#print axioms UorAtlas.Functor.Assignments.recOn
#print axioms UorAtlas.Functor.Assignments.vMap
#print axioms UorAtlas.Functor.Assignments.vObj
#print axioms UorAtlas.Functor.ComponentFamily
#print axioms UorAtlas.Functor.D62
#print axioms UorAtlas.Functor.D63
#print axioms UorAtlas.Functor.D64
#print axioms UorAtlas.Functor.D64.Kf
#print axioms UorAtlas.Functor.D64.Pf
#print axioms UorAtlas.Functor.D64.RAddr
#print axioms UorAtlas.Functor.D64.RQ
#print axioms UorAtlas.Functor.D64.Rv
#print axioms UorAtlas.Functor.D64.casesOn
#print axioms UorAtlas.Functor.D64.ctorIdx
#print axioms UorAtlas.Functor.D64.mk
#print axioms UorAtlas.Functor.D64.mk.inj
#print axioms UorAtlas.Functor.D64.mk.injEq
#print axioms UorAtlas.Functor.D64.mk.noConfusion
#print axioms UorAtlas.Functor.D64.mk.sizeOf_spec
#print axioms UorAtlas.Functor.D64.noConfusion
#print axioms UorAtlas.Functor.D64.noConfusionType
#print axioms UorAtlas.Functor.D64.rec
#print axioms UorAtlas.Functor.D64.recOn
#print axioms UorAtlas.Functor.D65
#print axioms UorAtlas.Functor.D65_aMap_apply
#print axioms UorAtlas.Functor.D66
#print axioms UorAtlas.Functor.D67
#print axioms UorAtlas.Functor.D67.apex
#print axioms UorAtlas.Functor.D67.casesOn
#print axioms UorAtlas.Functor.D67.ctorIdx
#print axioms UorAtlas.Functor.D67.diag
#print axioms UorAtlas.Functor.D67.leg
#print axioms UorAtlas.Functor.D67.mk
#print axioms UorAtlas.Functor.D67.mk.inj
#print axioms UorAtlas.Functor.D67.mk.injEq
#print axioms UorAtlas.Functor.D67.mk.noConfusion
#print axioms UorAtlas.Functor.D67.mk.sizeOf_spec
#print axioms UorAtlas.Functor.D67.noConfusion
#print axioms UorAtlas.Functor.D67.noConfusionType
#print axioms UorAtlas.Functor.D67.rec
#print axioms UorAtlas.Functor.D67.recOn
#print axioms UorAtlas.Functor.Delta
#print axioms UorAtlas.Functor.DeltaK
#print axioms UorAtlas.Functor.F1
#print axioms UorAtlas.Functor.F12
#print axioms UorAtlas.Functor.F13
#print axioms UorAtlas.Functor.F14
#print axioms UorAtlas.Functor.F15
#print axioms UorAtlas.Functor.F15a
#print axioms UorAtlas.Functor.F15p
#print axioms UorAtlas.Functor.F16
#print axioms UorAtlas.Functor.F17
#print axioms UorAtlas.Functor.F18
#print axioms UorAtlas.Functor.F19
#print axioms UorAtlas.Functor.F19a
#print axioms UorAtlas.Functor.F2
#print axioms UorAtlas.Functor.F20
#print axioms UorAtlas.Functor.F21
#print axioms UorAtlas.Functor.F22
#print axioms UorAtlas.Functor.F3
#print axioms UorAtlas.Functor.F4
#print axioms UorAtlas.Functor.F5
#print axioms UorAtlas.Functor.F6
#print axioms UorAtlas.Functor.F6p
#print axioms UorAtlas.Functor.F7
#print axioms UorAtlas.Functor.GrpData
#print axioms UorAtlas.Functor.GrpData.El
#print axioms UorAtlas.Functor.GrpData.casesOn
#print axioms UorAtlas.Functor.GrpData.ctorIdx
#print axioms UorAtlas.Functor.GrpData.eq_inv_of_mul_eq_one
#print axioms UorAtlas.Functor.GrpData.eq_one_of_self_mul
#print axioms UorAtlas.Functor.GrpData.inv
#print axioms UorAtlas.Functor.GrpData.inv_mul
#print axioms UorAtlas.Functor.GrpData.mk
#print axioms UorAtlas.Functor.GrpData.mk.inj
#print axioms UorAtlas.Functor.GrpData.mk.injEq
#print axioms UorAtlas.Functor.GrpData.mk.noConfusion
#print axioms UorAtlas.Functor.GrpData.mk.sizeOf_spec
#print axioms UorAtlas.Functor.GrpData.mul
#print axioms UorAtlas.Functor.GrpData.mul_assoc
#print axioms UorAtlas.Functor.GrpData.mul_inv
#print axioms UorAtlas.Functor.GrpData.mul_one
#print axioms UorAtlas.Functor.GrpData.noConfusion
#print axioms UorAtlas.Functor.GrpData.noConfusionType
#print axioms UorAtlas.Functor.GrpData.one
#print axioms UorAtlas.Functor.GrpData.one_mul
#print axioms UorAtlas.Functor.GrpData.rec
#print axioms UorAtlas.Functor.GrpData.recOn
#print axioms UorAtlas.Functor.Kf
#print axioms UorAtlas.Functor.LinModel
#print axioms UorAtlas.Functor.LinModel.casesOn
#print axioms UorAtlas.Functor.LinModel.commutant
#print axioms UorAtlas.Functor.LinModel.ctorIdx
#print axioms UorAtlas.Functor.LinModel.liftLinear
#print axioms UorAtlas.Functor.LinModel.mk
#print axioms UorAtlas.Functor.LinModel.mk.inj
#print axioms UorAtlas.Functor.LinModel.mk.injEq
#print axioms UorAtlas.Functor.LinModel.mk.noConfusion
#print axioms UorAtlas.Functor.LinModel.mk.sizeOf_spec
#print axioms UorAtlas.Functor.LinModel.noConfusion
#print axioms UorAtlas.Functor.LinModel.noConfusionType
#print axioms UorAtlas.Functor.LinModel.rec
#print axioms UorAtlas.Functor.LinModel.recOn
#print axioms UorAtlas.Functor.LinModel.sym2Rep
#print axioms UorAtlas.Functor.LocData
#print axioms UorAtlas.Functor.LocData.Adr
#print axioms UorAtlas.Functor.LocData.KSet
#print axioms UorAtlas.Functor.LocData.Place
#print axioms UorAtlas.Functor.LocData.Qv
#print axioms UorAtlas.Functor.LocData.aut
#print axioms UorAtlas.Functor.LocData.casesOn
#print axioms UorAtlas.Functor.LocData.ctorIdx
#print axioms UorAtlas.Functor.LocData.kact
#print axioms UorAtlas.Functor.LocData.kact_mul
#print axioms UorAtlas.Functor.LocData.kact_one
#print axioms UorAtlas.Functor.LocData.ker_pi
#print axioms UorAtlas.Functor.LocData.krep
#print axioms UorAtlas.Functor.LocData.krep_act
#print axioms UorAtlas.Functor.LocData.lift
#print axioms UorAtlas.Functor.LocData.mk
#print axioms UorAtlas.Functor.LocData.mk.inj
#print axioms UorAtlas.Functor.LocData.mk.injEq
#print axioms UorAtlas.Functor.LocData.mk.noConfusion
#print axioms UorAtlas.Functor.LocData.mk.sizeOf_spec
#print axioms UorAtlas.Functor.LocData.noConfusion
#print axioms UorAtlas.Functor.LocData.noConfusionType
#print axioms UorAtlas.Functor.LocData.pi
#print axioms UorAtlas.Functor.LocData.pi_lift
#print axioms UorAtlas.Functor.LocData.pi_mul
#print axioms UorAtlas.Functor.LocData.pi_one
#print axioms UorAtlas.Functor.LocData.proj
#print axioms UorAtlas.Functor.LocData.proj_str
#print axioms UorAtlas.Functor.LocData.rank
#print axioms UorAtlas.Functor.LocData.rec
#print axioms UorAtlas.Functor.LocData.recOn
#print axioms UorAtlas.Functor.LocData.wlin
#print axioms UorAtlas.Functor.MatGroup
#print axioms UorAtlas.Functor.MatGroup.El
#print axioms UorAtlas.Functor.MatGroup.Mem
#print axioms UorAtlas.Functor.MatGroup.casesOn
#print axioms UorAtlas.Functor.MatGroup.ctorIdx
#print axioms UorAtlas.Functor.MatGroup.grp
#print axioms UorAtlas.Functor.MatGroup.id_mem
#print axioms UorAtlas.Functor.MatGroup.invOf
#print axioms UorAtlas.Functor.MatGroup.invOf_mem
#print axioms UorAtlas.Functor.MatGroup.invOf_mul
#print axioms UorAtlas.Functor.MatGroup.mk
#print axioms UorAtlas.Functor.MatGroup.mk.inj
#print axioms UorAtlas.Functor.MatGroup.mk.injEq
#print axioms UorAtlas.Functor.MatGroup.mk.noConfusion
#print axioms UorAtlas.Functor.MatGroup.mk.sizeOf_spec
#print axioms UorAtlas.Functor.MatGroup.mul_invOf
#print axioms UorAtlas.Functor.MatGroup.mul_mem
#print axioms UorAtlas.Functor.MatGroup.noConfusion
#print axioms UorAtlas.Functor.MatGroup.noConfusionType
#print axioms UorAtlas.Functor.MatGroup.rec
#print axioms UorAtlas.Functor.MatGroup.recOn
#print axioms UorAtlas.Functor.NatTrans
#print axioms UorAtlas.Functor.NatTrans.app
#print axioms UorAtlas.Functor.NatTrans.casesOn
#print axioms UorAtlas.Functor.NatTrans.ctorIdx
#print axioms UorAtlas.Functor.NatTrans.ext
#print axioms UorAtlas.Functor.NatTrans.idt
#print axioms UorAtlas.Functor.NatTrans.mk
#print axioms UorAtlas.Functor.NatTrans.mk.inj
#print axioms UorAtlas.Functor.NatTrans.mk.injEq
#print axioms UorAtlas.Functor.NatTrans.mk.noConfusion
#print axioms UorAtlas.Functor.NatTrans.mk.sizeOf_spec
#print axioms UorAtlas.Functor.NatTrans.naturality
#print axioms UorAtlas.Functor.NatTrans.noConfusion
#print axioms UorAtlas.Functor.NatTrans.noConfusionType
#print axioms UorAtlas.Functor.NatTrans.rec
#print axioms UorAtlas.Functor.NatTrans.recOn
#print axioms UorAtlas.Functor.NatTrans.vcomp
#print axioms UorAtlas.Functor.PAddr
#print axioms UorAtlas.Functor.Pf
#print axioms UorAtlas.Functor.QAlg
#print axioms UorAtlas.Functor.QAlg.Car
#print axioms UorAtlas.Functor.QAlg.casesOn
#print axioms UorAtlas.Functor.QAlg.ctorIdx
#print axioms UorAtlas.Functor.QAlg.mk
#print axioms UorAtlas.Functor.QAlg.mk.inj
#print axioms UorAtlas.Functor.QAlg.mk.injEq
#print axioms UorAtlas.Functor.QAlg.mk.noConfusion
#print axioms UorAtlas.Functor.QAlg.mk.sizeOf_spec
#print axioms UorAtlas.Functor.QAlg.noConfusion
#print axioms UorAtlas.Functor.QAlg.noConfusionType
#print axioms UorAtlas.Functor.QAlg.one_ne_zero
#print axioms UorAtlas.Functor.QAlg.rat
#print axioms UorAtlas.Functor.QAlg.rec
#print axioms UorAtlas.Functor.QAlg.recOn
#print axioms UorAtlas.Functor.QAlg.ring
#print axioms UorAtlas.Functor.QAlg.str
#print axioms UorAtlas.Functor.QAlg.str_injective
#print axioms UorAtlas.Functor.QCar
#print axioms UorAtlas.Functor.QIx
#print axioms UorAtlas.Functor.QIx.address
#print axioms UorAtlas.Functor.QIx.address.elim
#print axioms UorAtlas.Functor.QIx.address.sizeOf_spec
#print axioms UorAtlas.Functor.QIx.alg
#print axioms UorAtlas.Functor.QIx.alg.match_1
#print axioms UorAtlas.Functor.QIx.casesOn
#print axioms UorAtlas.Functor.QIx.ctorElim
#print axioms UorAtlas.Functor.QIx.ctorElimType
#print axioms UorAtlas.Functor.QIx.ctorIdx
#print axioms UorAtlas.Functor.QIx.localAt
#print axioms UorAtlas.Functor.QIx.localAt.elim
#print axioms UorAtlas.Functor.QIx.localAt.inj
#print axioms UorAtlas.Functor.QIx.localAt.injEq
#print axioms UorAtlas.Functor.QIx.localAt.noConfusion
#print axioms UorAtlas.Functor.QIx.localAt.sizeOf_spec
#print axioms UorAtlas.Functor.QIx.noConfusion
#print axioms UorAtlas.Functor.QIx.noConfusionType
#print axioms UorAtlas.Functor.QIx.rational
#print axioms UorAtlas.Functor.QIx.rational.elim
#print axioms UorAtlas.Functor.QIx.rational.sizeOf_spec
#print axioms UorAtlas.Functor.QIx.rec
#print axioms UorAtlas.Functor.QIx.recOn
#print axioms UorAtlas.Functor.QLin
#print axioms UorAtlas.Functor.QLin.casesOn
#print axioms UorAtlas.Functor.QLin.comp
#print axioms UorAtlas.Functor.QLin.ctorIdx
#print axioms UorAtlas.Functor.QLin.ext
#print axioms UorAtlas.Functor.QLin.id
#print axioms UorAtlas.Functor.QLin.map_add
#print axioms UorAtlas.Functor.QLin.map_smul
#print axioms UorAtlas.Functor.QLin.mk
#print axioms UorAtlas.Functor.QLin.mk.inj
#print axioms UorAtlas.Functor.QLin.mk.injEq
#print axioms UorAtlas.Functor.QLin.mk.noConfusion
#print axioms UorAtlas.Functor.QLin.mk.sizeOf_spec
#print axioms UorAtlas.Functor.QLin.noConfusion
#print axioms UorAtlas.Functor.QLin.noConfusionType
#print axioms UorAtlas.Functor.QLin.rec
#print axioms UorAtlas.Functor.QLin.recOn
#print axioms UorAtlas.Functor.QLin.toFun
#print axioms UorAtlas.Functor.QMod
#print axioms UorAtlas.Functor.RAddr
#print axioms UorAtlas.Functor.RQ
#print axioms UorAtlas.Functor.Rv
#print axioms UorAtlas.Functor.SCar
#print axioms UorAtlas.Functor.SCar.match_1
#print axioms UorAtlas.Functor.SIx
#print axioms UorAtlas.Functor.SIx.casesOn
#print axioms UorAtlas.Functor.SIx.classes
#print axioms UorAtlas.Functor.SIx.classes.elim
#print axioms UorAtlas.Functor.SIx.classes.sizeOf_spec
#print axioms UorAtlas.Functor.SIx.ctorElim
#print axioms UorAtlas.Functor.SIx.ctorElimType
#print axioms UorAtlas.Functor.SIx.ctorIdx
#print axioms UorAtlas.Functor.SIx.noConfusion
#print axioms UorAtlas.Functor.SIx.noConfusionType
#print axioms UorAtlas.Functor.SIx.paddr
#print axioms UorAtlas.Functor.SIx.paddr.elim
#print axioms UorAtlas.Functor.SIx.paddr.sizeOf_spec
#print axioms UorAtlas.Functor.SIx.rec
#print axioms UorAtlas.Functor.SIx.recOn
#print axioms UorAtlas.Functor.SetCat
#print axioms UorAtlas.Functor.T76a
#print axioms UorAtlas.Functor.T79
#print axioms UorAtlas.Functor.T80
#print axioms UorAtlas.Functor.TwoPlace.Pair
#print axioms UorAtlas.Functor.TwoPlace.Pair.casesOn
#print axioms UorAtlas.Functor.TwoPlace.Pair.ctorIdx
#print axioms UorAtlas.Functor.TwoPlace.Pair.ext
#print axioms UorAtlas.Functor.TwoPlace.Pair.fst
#print axioms UorAtlas.Functor.TwoPlace.Pair.mk
#print axioms UorAtlas.Functor.TwoPlace.Pair.mk.inj
#print axioms UorAtlas.Functor.TwoPlace.Pair.mk.injEq
#print axioms UorAtlas.Functor.TwoPlace.Pair.mk.noConfusion
#print axioms UorAtlas.Functor.TwoPlace.Pair.mk.sizeOf_spec
#print axioms UorAtlas.Functor.TwoPlace.Pair.noConfusion
#print axioms UorAtlas.Functor.TwoPlace.Pair.noConfusionType
#print axioms UorAtlas.Functor.TwoPlace.Pair.rec
#print axioms UorAtlas.Functor.TwoPlace.Pair.recOn
#print axioms UorAtlas.Functor.TwoPlace.Pair.snd
#print axioms UorAtlas.Functor.TwoPlace.adr
#print axioms UorAtlas.Functor.TwoPlace.component
#print axioms UorAtlas.Functor.TwoPlace.component.match_1
#print axioms UorAtlas.Functor.TwoPlace.instAddCommGroupPair
#print axioms UorAtlas.Functor.TwoPlace.instCommRingPair
#print axioms UorAtlas.Functor.TwoPlace.lift_choice
#print axioms UorAtlas.Functor.TwoPlace.lift_independent
#print axioms UorAtlas.Functor.TwoPlace.mul_neg_neg
#print axioms UorAtlas.Functor.TwoPlace.proj
#print axioms UorAtlas.Functor.TwoPlace.signGroup
#print axioms UorAtlas.Functor.TwoPlace.trivialGrp
#print axioms UorAtlas.Functor.TwoPlace.witness
#print axioms UorAtlas.Functor.addrAct
#print axioms UorAtlas.Functor.addrAct_mul
#print axioms UorAtlas.Functor.addrAct_neg
#print axioms UorAtlas.Functor.addrAct_one
#print axioms UorAtlas.Functor.adelicCone
#print axioms UorAtlas.Functor.apply_add
#print axioms UorAtlas.Functor.apply_id
#print axioms UorAtlas.Functor.apply_mul
#print axioms UorAtlas.Functor.apply_neg
#print axioms UorAtlas.Functor.apply_smul
#print axioms UorAtlas.Functor.baseHom
#print axioms UorAtlas.Functor.deloop
#print axioms UorAtlas.Functor.deltaHom
#print axioms UorAtlas.Functor.deltaKNat
#print axioms UorAtlas.Functor.deltaNat
#print axioms UorAtlas.Functor.funCat
#print axioms UorAtlas.Functor.instQAlgRing
#print axioms UorAtlas.Functor.locHom
#print axioms UorAtlas.Functor.locMat
#print axioms UorAtlas.Functor.locNat
#print axioms UorAtlas.Functor.locv
#print axioms UorAtlas.Functor.locv_across
#print axioms UorAtlas.Functor.map_apply
#print axioms UorAtlas.Functor.map_neg_mat
#print axioms UorAtlas.Functor.map_neg_vec
#print axioms UorAtlas.Functor.matHom
#print axioms UorAtlas.Functor.matHom_id
#print axioms UorAtlas.Functor.matHom_mul
#print axioms UorAtlas.Functor.paddrMk
#print axioms UorAtlas.Functor.paddrMk_neg
#print axioms UorAtlas.Functor.pi_inv
#print axioms UorAtlas.Functor.projHom
#print axioms UorAtlas.Functor.projNat
#print axioms UorAtlas.Functor.qsmul
#print axioms UorAtlas.Functor.signatureTable
#print axioms UorAtlas.Functor.sym2Rep_mul
#print axioms UorAtlas.Functor.tauAddr
#print axioms UorAtlas.Functor.tauAddr_mk
#print axioms UorAtlas.LexLeanInternal.decl1027
#print axioms UorAtlas.LexLeanInternal.decl1033
#print axioms UorAtlas.LexLeanInternal.decl104
#print axioms UorAtlas.LexLeanInternal.decl1041
#print axioms UorAtlas.LexLeanInternal.decl1045
#print axioms UorAtlas.LexLeanInternal.decl1064
#print axioms UorAtlas.LexLeanInternal.decl1087
#print axioms UorAtlas.LexLeanInternal.decl1124
#print axioms UorAtlas.LexLeanInternal.decl1137
#print axioms UorAtlas.LexLeanInternal.decl1146
#print axioms UorAtlas.LexLeanInternal.decl1163
#print axioms UorAtlas.LexLeanInternal.decl1164
#print axioms UorAtlas.LexLeanInternal.decl1168
#print axioms UorAtlas.LexLeanInternal.decl1169
#print axioms UorAtlas.LexLeanInternal.decl1177
#print axioms UorAtlas.LexLeanInternal.decl1193
#print axioms UorAtlas.LexLeanInternal.decl1210
#print axioms UorAtlas.LexLeanInternal.decl1213
#print axioms UorAtlas.LexLeanInternal.decl1221
#print axioms UorAtlas.LexLeanInternal.decl1226
#print axioms UorAtlas.LexLeanInternal.decl1236
#print axioms UorAtlas.LexLeanInternal.decl1286
#print axioms UorAtlas.LexLeanInternal.decl1289
#print axioms UorAtlas.LexLeanInternal.decl1293
#print axioms UorAtlas.LexLeanInternal.decl1299
#print axioms UorAtlas.LexLeanInternal.decl1321
#print axioms UorAtlas.LexLeanInternal.decl1324
#print axioms UorAtlas.LexLeanInternal.decl1332
#print axioms UorAtlas.LexLeanInternal.decl135
#print axioms UorAtlas.LexLeanInternal.decl136
#print axioms UorAtlas.LexLeanInternal.decl1383
#print axioms UorAtlas.LexLeanInternal.decl1414
#print axioms UorAtlas.LexLeanInternal.decl1422
#print axioms UorAtlas.LexLeanInternal.decl1470
#print axioms UorAtlas.LexLeanInternal.decl1501
#print axioms UorAtlas.LexLeanInternal.decl151
#print axioms UorAtlas.LexLeanInternal.decl1516
#print axioms UorAtlas.LexLeanInternal.decl1523
#print axioms UorAtlas.LexLeanInternal.decl1524
#print axioms UorAtlas.LexLeanInternal.decl1536
#print axioms UorAtlas.LexLeanInternal.decl1548
#print axioms UorAtlas.LexLeanInternal.decl1568
#print axioms UorAtlas.LexLeanInternal.decl1583
#print axioms UorAtlas.LexLeanInternal.decl161
#print axioms UorAtlas.LexLeanInternal.decl1617
#print axioms UorAtlas.LexLeanInternal.decl1634
#print axioms UorAtlas.LexLeanInternal.decl1646
#print axioms UorAtlas.LexLeanInternal.decl166
#print axioms UorAtlas.LexLeanInternal.decl1671
#print axioms UorAtlas.LexLeanInternal.decl1695
#print axioms UorAtlas.LexLeanInternal.decl1699
#print axioms UorAtlas.LexLeanInternal.decl197
#print axioms UorAtlas.LexLeanInternal.decl205
#print axioms UorAtlas.LexLeanInternal.decl222
#print axioms UorAtlas.LexLeanInternal.decl227
#print axioms UorAtlas.LexLeanInternal.decl236
#print axioms UorAtlas.LexLeanInternal.decl247
#print axioms UorAtlas.LexLeanInternal.decl250
#print axioms UorAtlas.LexLeanInternal.decl293
#print axioms UorAtlas.LexLeanInternal.decl306
#print axioms UorAtlas.LexLeanInternal.decl337
#print axioms UorAtlas.LexLeanInternal.decl346
#print axioms UorAtlas.LexLeanInternal.decl361
#print axioms UorAtlas.LexLeanInternal.decl370
#print axioms UorAtlas.LexLeanInternal.decl372
#print axioms UorAtlas.LexLeanInternal.decl381
#print axioms UorAtlas.LexLeanInternal.decl384
#print axioms UorAtlas.LexLeanInternal.decl39
#print axioms UorAtlas.LexLeanInternal.decl41
#print axioms UorAtlas.LexLeanInternal.decl426
#print axioms UorAtlas.LexLeanInternal.decl485
#print axioms UorAtlas.LexLeanInternal.decl511
#print axioms UorAtlas.LexLeanInternal.decl524
#print axioms UorAtlas.LexLeanInternal.decl538
#print axioms UorAtlas.LexLeanInternal.decl543
#print axioms UorAtlas.LexLeanInternal.decl554
#print axioms UorAtlas.LexLeanInternal.decl558
#print axioms UorAtlas.LexLeanInternal.decl589
#print axioms UorAtlas.LexLeanInternal.decl59
#print axioms UorAtlas.LexLeanInternal.decl595
#print axioms UorAtlas.LexLeanInternal.decl598
#print axioms UorAtlas.LexLeanInternal.decl64
#print axioms UorAtlas.LexLeanInternal.decl640
#print axioms UorAtlas.LexLeanInternal.decl642
#print axioms UorAtlas.LexLeanInternal.decl67
#print axioms UorAtlas.LexLeanInternal.decl737
#print axioms UorAtlas.LexLeanInternal.decl745
#print axioms UorAtlas.LexLeanInternal.decl770
#print axioms UorAtlas.LexLeanInternal.decl779
#print axioms UorAtlas.LexLeanInternal.decl788
#print axioms UorAtlas.LexLeanInternal.decl793
#print axioms UorAtlas.LexLeanInternal.decl796
#print axioms UorAtlas.LexLeanInternal.decl80
#print axioms UorAtlas.LexLeanInternal.decl801
#print axioms UorAtlas.LexLeanInternal.decl819
#print axioms UorAtlas.LexLeanInternal.decl826
#print axioms UorAtlas.LexLeanInternal.decl83
#print axioms UorAtlas.LexLeanInternal.decl839
#print axioms UorAtlas.LexLeanInternal.decl842
#print axioms UorAtlas.LexLeanInternal.decl858
#print axioms UorAtlas.LexLeanInternal.decl86
#print axioms UorAtlas.LexLeanInternal.decl861
#print axioms UorAtlas.LexLeanInternal.decl884
#print axioms UorAtlas.LexLeanInternal.decl894
#print axioms UorAtlas.LexLeanInternal.decl909
#print axioms UorAtlas.LexLeanInternal.decl919
#print axioms UorAtlas.LexLeanInternal.decl930
#print axioms UorAtlas.LexLeanInternal.decl951
#print axioms UorAtlas.LexLeanInternal.decl954
#print axioms UorAtlas.LexLeanInternal.decl972
#print axioms UorAtlas.LexLeanInternal.decl974
#print axioms UorAtlas.LexLeanInternal.decl99
#print axioms UorAtlas.LexLeanInternal.decl992
#print axioms UorAtlas.LexLeanInternal.decl996
