module
import LexLeanExample.Prelude.RingLemmas
#print axioms UorAtlas.LexLeanInternal.decl121
#print axioms UorAtlas.LexLeanInternal.decl1379
#print axioms UorAtlas.LexLeanInternal.decl143
#print axioms UorAtlas.LexLeanInternal.decl1477
#print axioms UorAtlas.LexLeanInternal.decl1538
#print axioms UorAtlas.LexLeanInternal.decl1625
#print axioms UorAtlas.LexLeanInternal.decl341
#print axioms UorAtlas.LexLeanInternal.decl430
#print axioms UorAtlas.LexLeanInternal.decl441
#print axioms UorAtlas.LexLeanInternal.decl652
#print axioms UorAtlas.LexLeanInternal.decl714
#print axioms UorAtlas.LexLeanInternal.decl95
#print axioms UorAtlas.Prelude.RingLemmas.BC1
#print axioms UorAtlas.Prelude.RingLemmas.DV1
#print axioms UorAtlas.Prelude.RingLemmas.FR1
#print axioms UorAtlas.Prelude.RingLemmas.GLGen
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.below
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.below.casesOn
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.below.gen
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.below.inv
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.below.mul
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.below.one
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.below.rec
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.brecOn
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.casesOn
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.gen
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.inv
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.mul
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.one
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.rec
#print axioms UorAtlas.Prelude.RingLemmas.GLGen.recOn
#print axioms UorAtlas.Prelude.RingLemmas.IG1
#print axioms UorAtlas.Prelude.RingLemmas.InDual
#print axioms UorAtlas.Prelude.RingLemmas.InGL
#print axioms UorAtlas.Prelude.RingLemmas.InGL_inv
#print axioms UorAtlas.Prelude.RingLemmas.InGL_map
#print axioms UorAtlas.Prelude.RingLemmas.InGL_mul
#print axioms UorAtlas.Prelude.RingLemmas.InGL_one
#print axioms UorAtlas.Prelude.RingLemmas.InImage
#print axioms UorAtlas.Prelude.RingLemmas.InImage.add
#print axioms UorAtlas.Prelude.RingLemmas.InImage.mul
#print axioms UorAtlas.Prelude.RingLemmas.InImage.sum
#print axioms UorAtlas.Prelude.RingLemmas.InImage.zero
#print axioms UorAtlas.Prelude.RingLemmas.InLattice
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.add
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.add.elim
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.add.inj
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.add.injEq
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.add.noConfusion
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.add.sizeOf_spec
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.below
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.brecOn
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.brecOn.eq
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.brecOn.go
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.casesOn
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.ctorElim
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.ctorElimType
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.ctorIdx
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.eval
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.eval.match_1
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.eval_congr
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.eval_sumPoly
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.mul
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.mul.elim
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.mul.inj
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.mul.injEq
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.mul.noConfusion
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.mul.sizeOf_spec
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.neg
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.neg.elim
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.neg.inj
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.neg.injEq
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.neg.noConfusion
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.neg.sizeOf_spec
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.noConfusion
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.noConfusionType
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.one
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.one.elim
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.one.sizeOf_spec
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.rec
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.recOn
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.sumPoly
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.sumPoly.match_1
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.var
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.var.elim
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.var.inj
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.var.injEq
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.var.noConfusion
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.var.sizeOf_spec
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.zero
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.zero.elim
#print axioms UorAtlas.Prelude.RingLemmas.IntPoly.zero.sizeOf_spec
#print axioms UorAtlas.Prelude.RingLemmas.IntegralAt
#print axioms UorAtlas.Prelude.RingLemmas.IsFinite
#print axioms UorAtlas.Prelude.RingLemmas.IsPrime
#print axioms UorAtlas.Prelude.RingLemmas.LI1
#print axioms UorAtlas.Prelude.RingLemmas.OrbitRel
#print axioms UorAtlas.Prelude.RingLemmas.QL1
#print axioms UorAtlas.Prelude.RingLemmas.QL1.descend
#print axioms UorAtlas.Prelude.RingLemmas.QL1.descend_mk
#print axioms UorAtlas.Prelude.RingLemmas.QL1_sign
#print axioms UorAtlas.Prelude.RingLemmas.RH1
#print axioms UorAtlas.Prelude.RingLemmas.RH1_apply
#print axioms UorAtlas.Prelude.RingLemmas.RH1_mul_entry
#print axioms UorAtlas.Prelude.RingLemmas.SD1
#print axioms UorAtlas.Prelude.RingLemmas.TI1
#print axioms UorAtlas.Prelude.RingLemmas.basisVec
#print axioms UorAtlas.Prelude.RingLemmas.den_dvd_of_scale
#print axioms UorAtlas.Prelude.RingLemmas.den_mul_eq_num
#print axioms UorAtlas.Prelude.RingLemmas.eval_mulEntryPoly
#print axioms UorAtlas.Prelude.RingLemmas.exists_common_denominator
#print axioms UorAtlas.Prelude.RingLemmas.gramForm
#print axioms UorAtlas.Prelude.RingLemmas.gramForm_basisVec
#print axioms UorAtlas.Prelude.RingLemmas.inDual_of_inLattice
#print axioms UorAtlas.Prelude.RingLemmas.inLattice_basisVec
#print axioms UorAtlas.Prelude.RingLemmas.inLattice_of_inDual
#print axioms UorAtlas.Prelude.RingLemmas.map_id
#print axioms UorAtlas.Prelude.RingLemmas.map_id_apply
#print axioms UorAtlas.Prelude.RingLemmas.mulEntryPoly
#print axioms UorAtlas.Prelude.RingLemmas.mulEntryPoly.eq_1
#print axioms UorAtlas.Prelude.RingLemmas.mulVars
#print axioms UorAtlas.Prelude.RingLemmas.mulVars.match_1
#print axioms UorAtlas.Prelude.RingLemmas.signAct
#print axioms UorAtlas.Prelude.RingLemmas.signAct.match_1
