module
import LexLeanExample.Glue
#print axioms UorAtlas.Glue.Closed
#print axioms UorAtlas.Glue.Even
#print axioms UorAtlas.Glue.Integral
#print axioms UorAtlas.Glue.MemD
#print axioms UorAtlas.Glue.MemDCongr
#print axioms UorAtlas.Glue.MemD_iff
#print axioms UorAtlas.Glue.MemGlue
#print axioms UorAtlas.Glue.MemGlueCongr
#print axioms UorAtlas.Glue.MemGlue_iff
#print axioms UorAtlas.Glue.MemL
#print axioms UorAtlas.Glue.MemL_ones
#print axioms UorAtlas.Glue.P1
#print axioms UorAtlas.Glue.P2
#print axioms UorAtlas.Glue.T57a
#print axioms UorAtlas.Glue.T57b
#print axioms UorAtlas.Glue.T57c
#print axioms UorAtlas.Glue.T84
#print axioms UorAtlas.Glue.T85
#print axioms UorAtlas.Glue.add_apply_int
#print axioms UorAtlas.Glue.dot_def
#print axioms UorAtlas.Glue.dot_of_even_even
#print axioms UorAtlas.Glue.dot_of_even_odd
#print axioms UorAtlas.Glue.dot_of_odd_odd
#print axioms UorAtlas.Glue.dot_self_even
#print axioms UorAtlas.Glue.edgeNorm
#print axioms UorAtlas.Glue.instDecidableMemD
#print axioms UorAtlas.Glue.instDecidableMemDCongr
#print axioms UorAtlas.Glue.instDecidableMemGlue
#print axioms UorAtlas.Glue.instDecidableMemGlueCongr
#print axioms UorAtlas.Glue.instDecidableMemL
#print axioms UorAtlas.Glue.one_le_mul_self
#print axioms UorAtlas.Glue.ones
#print axioms UorAtlas.Glue.rootNorm
#print axioms UorAtlas.Glue.sumInt_add
#print axioms UorAtlas.Glue.sumInt_congr
#print axioms UorAtlas.Glue.sumInt_const
#print axioms UorAtlas.Glue.sumInt_dvd
#print axioms UorAtlas.Glue.sumInt_ge_card
#print axioms UorAtlas.Glue.sumInt_mul_left
#print axioms UorAtlas.Glue.sumInt_ones
#print axioms UorAtlas.LexLeanInternal.decl1065
#print axioms UorAtlas.LexLeanInternal.decl11
#print axioms UorAtlas.LexLeanInternal.decl1159
#print axioms UorAtlas.LexLeanInternal.decl1182
#print axioms UorAtlas.LexLeanInternal.decl1192
#print axioms UorAtlas.LexLeanInternal.decl120
#print axioms UorAtlas.LexLeanInternal.decl1215
#print axioms UorAtlas.LexLeanInternal.decl1278
#print axioms UorAtlas.LexLeanInternal.decl1290
#print axioms UorAtlas.LexLeanInternal.decl1370
#print axioms UorAtlas.LexLeanInternal.decl1431
#print axioms UorAtlas.LexLeanInternal.decl1489
#print axioms UorAtlas.LexLeanInternal.decl1576
#print axioms UorAtlas.LexLeanInternal.decl1588
#print axioms UorAtlas.LexLeanInternal.decl1608
#print axioms UorAtlas.LexLeanInternal.decl1620
#print axioms UorAtlas.LexLeanInternal.decl1658
#print axioms UorAtlas.LexLeanInternal.decl1668
#print axioms UorAtlas.LexLeanInternal.decl168
#print axioms UorAtlas.LexLeanInternal.decl1691
#print axioms UorAtlas.LexLeanInternal.decl200
#print axioms UorAtlas.LexLeanInternal.decl22
#print axioms UorAtlas.LexLeanInternal.decl255
#print axioms UorAtlas.LexLeanInternal.decl279
#print axioms UorAtlas.LexLeanInternal.decl284
#print axioms UorAtlas.LexLeanInternal.decl33
#print axioms UorAtlas.LexLeanInternal.decl437
#print axioms UorAtlas.LexLeanInternal.decl465
#print axioms UorAtlas.LexLeanInternal.decl542
#print axioms UorAtlas.LexLeanInternal.decl545
#print axioms UorAtlas.LexLeanInternal.decl58
#print axioms UorAtlas.LexLeanInternal.decl606
#print axioms UorAtlas.LexLeanInternal.decl61
#print axioms UorAtlas.LexLeanInternal.decl655
#print axioms UorAtlas.LexLeanInternal.decl685
#print axioms UorAtlas.LexLeanInternal.decl688
#print axioms UorAtlas.LexLeanInternal.decl742
#print axioms UorAtlas.LexLeanInternal.decl750
#print axioms UorAtlas.LexLeanInternal.decl774
#print axioms UorAtlas.LexLeanInternal.decl786
#print axioms UorAtlas.LexLeanInternal.decl807
#print axioms UorAtlas.LexLeanInternal.decl853
#print axioms UorAtlas.LexLeanInternal.decl863
#print axioms UorAtlas.LexLeanInternal.decl87
#print axioms UorAtlas.LexLeanInternal.decl879
#print axioms UorAtlas.LexLeanInternal.decl882
#print axioms UorAtlas.LexLeanInternal.decl891
#print axioms UorAtlas.LexLeanInternal.decl929
#print axioms UorAtlas.LexLeanInternal.decl941
#print axioms UorAtlas.LexLeanInternal.decl942
#print axioms UorAtlas.LexLeanInternal.decl978
