module
import LexLeanExample.Parameters
#print axioms UorAtlas.LexLeanInternal.decl1036
#print axioms UorAtlas.LexLeanInternal.decl1214
#print axioms UorAtlas.LexLeanInternal.decl1282
#print axioms UorAtlas.LexLeanInternal.decl1329
#print axioms UorAtlas.LexLeanInternal.decl242
#print axioms UorAtlas.LexLeanInternal.decl245
#print axioms UorAtlas.LexLeanInternal.decl618
#print axioms UorAtlas.LexLeanInternal.decl665
#print axioms UorAtlas.Parameters.D1
#print axioms UorAtlas.Parameters.D1_eight
#print axioms UorAtlas.Parameters.D1_exists
#print axioms UorAtlas.Parameters.D1_lt_eight
#print axioms UorAtlas.Parameters.D2
#print axioms UorAtlas.Parameters.D2_admissible
#print axioms UorAtlas.Parameters.D2_least
#print axioms UorAtlas.Parameters.D3
#print axioms UorAtlas.Parameters.D4
#print axioms UorAtlas.Parameters.D4_value
#print axioms UorAtlas.Parameters.D5
#print axioms UorAtlas.Parameters.D5_value
#print axioms UorAtlas.Parameters.D6
#print axioms UorAtlas.Parameters.D6_value
#print axioms UorAtlas.Parameters.D7
#print axioms UorAtlas.Parameters.D7_value
#print axioms UorAtlas.Parameters.D8
#print axioms UorAtlas.Parameters.D8_value
#print axioms UorAtlas.Parameters.Step
#print axioms UorAtlas.Parameters.T1
#print axioms UorAtlas.Parameters.T2
#print axioms UorAtlas.Parameters.T3
#print axioms UorAtlas.Parameters.T30
#print axioms UorAtlas.Parameters.T4
#print axioms UorAtlas.Parameters.findX
#print axioms UorAtlas.Parameters.instDecidableD1
#print axioms UorAtlas.Parameters.least
#print axioms UorAtlas.Parameters.least_holds
#print axioms UorAtlas.Parameters.least_le
#print axioms UorAtlas.Parameters.least_min
#print axioms UorAtlas.Parameters.stepWf
