module
import LexLeanExample.Prelude.Bitset
#print axioms UorAtlas.LexLeanInternal.decl1029
#print axioms UorAtlas.LexLeanInternal.decl1037
#print axioms UorAtlas.LexLeanInternal.decl1038
#print axioms UorAtlas.LexLeanInternal.decl1049
#print axioms UorAtlas.LexLeanInternal.decl108
#print axioms UorAtlas.LexLeanInternal.decl1092
#print axioms UorAtlas.LexLeanInternal.decl1151
#print axioms UorAtlas.LexLeanInternal.decl1211
#print axioms UorAtlas.LexLeanInternal.decl1267
#print axioms UorAtlas.LexLeanInternal.decl1281
#print axioms UorAtlas.LexLeanInternal.decl1303
#print axioms UorAtlas.LexLeanInternal.decl1307
#print axioms UorAtlas.LexLeanInternal.decl1327
#print axioms UorAtlas.LexLeanInternal.decl1333
#print axioms UorAtlas.LexLeanInternal.decl1389
#print axioms UorAtlas.LexLeanInternal.decl1412
#print axioms UorAtlas.LexLeanInternal.decl1424
#print axioms UorAtlas.LexLeanInternal.decl1528
#print axioms UorAtlas.LexLeanInternal.decl1560
#print axioms UorAtlas.LexLeanInternal.decl1578
#print axioms UorAtlas.LexLeanInternal.decl1664
#print axioms UorAtlas.LexLeanInternal.decl1670
#print axioms UorAtlas.LexLeanInternal.decl1678
#print axioms UorAtlas.LexLeanInternal.decl1697
#print axioms UorAtlas.LexLeanInternal.decl1707
#print axioms UorAtlas.LexLeanInternal.decl1713
#print axioms UorAtlas.LexLeanInternal.decl203
#print axioms UorAtlas.LexLeanInternal.decl206
#print axioms UorAtlas.LexLeanInternal.decl294
#print axioms UorAtlas.LexLeanInternal.decl326
#print axioms UorAtlas.LexLeanInternal.decl329
#print axioms UorAtlas.LexLeanInternal.decl360
#print axioms UorAtlas.LexLeanInternal.decl363
#print axioms UorAtlas.LexLeanInternal.decl45
#print axioms UorAtlas.LexLeanInternal.decl470
#print axioms UorAtlas.LexLeanInternal.decl505
#print axioms UorAtlas.LexLeanInternal.decl514
#print axioms UorAtlas.LexLeanInternal.decl567
#print axioms UorAtlas.LexLeanInternal.decl696
#print axioms UorAtlas.LexLeanInternal.decl856
#print axioms UorAtlas.LexLeanInternal.decl870
#print axioms UorAtlas.LexLeanInternal.decl872
#print axioms UorAtlas.LexLeanInternal.decl922
#print axioms UorAtlas.Prelude.Bitset
#print axioms UorAtlas.Prelude.Bitset.bitInduction
#print axioms UorAtlas.Prelude.Bitset.card
#print axioms UorAtlas.Prelude.Bitset.cardAux
#print axioms UorAtlas.Prelude.Bitset.cardAux_eq
#print axioms UorAtlas.Prelude.Bitset.cardAux_succ
#print axioms UorAtlas.Prelude.Bitset.cardBit
#print axioms UorAtlas.Prelude.Bitset.cardBitAux
#print axioms UorAtlas.Prelude.Bitset.cardBitAux_irrel
#print axioms UorAtlas.Prelude.Bitset.cardBitAux_succ
#print axioms UorAtlas.Prelude.Bitset.cardBitAux_zero_arg
#print axioms UorAtlas.Prelude.Bitset.cardBit_step
#print axioms UorAtlas.Prelude.Bitset.cardBit_step_byte
#print axioms UorAtlas.Prelude.Bitset.cardBit_zero
#print axioms UorAtlas.Prelude.Bitset.cardByte
#print axioms UorAtlas.Prelude.Bitset.cardByteSpec
#print axioms UorAtlas.Prelude.Bitset.cardByteSpec.eq_1
#print axioms UorAtlas.Prelude.Bitset.cardByteTable
#print axioms UorAtlas.Prelude.Bitset.cardByte_eq_spec
#print axioms UorAtlas.Prelude.Bitset.card_empty
#print axioms UorAtlas.Prelude.Bitset.card_eq_cardBit
#print axioms UorAtlas.Prelude.Bitset.card_eq_zero
#print axioms UorAtlas.Prelude.Bitset.card_erase_of_mem
#print axioms UorAtlas.Prelude.Bitset.card_insert_of_notMem
#print axioms UorAtlas.Prelude.Bitset.card_le_of_subset
#print axioms UorAtlas.Prelude.Bitset.card_lor_two_pow
#print axioms UorAtlas.Prelude.Bitset.card_singleton
#print axioms UorAtlas.Prelude.Bitset.card_step
#print axioms UorAtlas.Prelude.Bitset.card_union_add_card_inter
#print axioms UorAtlas.Prelude.Bitset.diff
#print axioms UorAtlas.Prelude.Bitset.empty
#print axioms UorAtlas.Prelude.Bitset.erase
#print axioms UorAtlas.Prelude.Bitset.erase.eq_1
#print axioms UorAtlas.Prelude.Bitset.ext
#print axioms UorAtlas.Prelude.Bitset.insert
#print axioms UorAtlas.Prelude.Bitset.insert_erase_of_mem
#print axioms UorAtlas.Prelude.Bitset.instAddCommGroup
#print axioms UorAtlas.Prelude.Bitset.instDecidableEq
#print axioms UorAtlas.Prelude.Bitset.instDecidableMem
#print axioms UorAtlas.Prelude.Bitset.instMembership
#print axioms UorAtlas.Prelude.Bitset.inter
#print axioms UorAtlas.Prelude.Bitset.le_of_mem_toListFrom
#print axioms UorAtlas.Prelude.Bitset.length_toList
#print axioms UorAtlas.Prelude.Bitset.length_toListFrom
#print axioms UorAtlas.Prelude.Bitset.mem
#print axioms UorAtlas.Prelude.Bitset.mem_def
#print axioms UorAtlas.Prelude.Bitset.mem_diff
#print axioms UorAtlas.Prelude.Bitset.mem_erase
#print axioms UorAtlas.Prelude.Bitset.mem_insert
#print axioms UorAtlas.Prelude.Bitset.mem_inter
#print axioms UorAtlas.Prelude.Bitset.mem_singleton
#print axioms UorAtlas.Prelude.Bitset.mem_symmDiff
#print axioms UorAtlas.Prelude.Bitset.mem_toList
#print axioms UorAtlas.Prelude.Bitset.mem_toListFrom
#print axioms UorAtlas.Prelude.Bitset.mem_union
#print axioms UorAtlas.Prelude.Bitset.notMem_empty
#print axioms UorAtlas.Prelude.Bitset.ofNat
#print axioms UorAtlas.Prelude.Bitset.singleton
#print axioms UorAtlas.Prelude.Bitset.singleton_toNat
#print axioms UorAtlas.Prelude.Bitset.subset
#print axioms UorAtlas.Prelude.Bitset.subset_iff
#print axioms UorAtlas.Prelude.Bitset.symmDiff
#print axioms UorAtlas.Prelude.Bitset.toList
#print axioms UorAtlas.Prelude.Bitset.toListAux
#print axioms UorAtlas.Prelude.Bitset.toListAux_irrel
#print axioms UorAtlas.Prelude.Bitset.toListAux_succ
#print axioms UorAtlas.Prelude.Bitset.toListAux_zero_arg
#print axioms UorAtlas.Prelude.Bitset.toListFrom
#print axioms UorAtlas.Prelude.Bitset.toListFrom_step
#print axioms UorAtlas.Prelude.Bitset.toNat
#print axioms UorAtlas.Prelude.Bitset.union
