module
import LexLeanExample.GroupSeries
#print axioms UorAtlas.Closure.CommClosure
#print axioms UorAtlas.Closure.CommClosure.below
#print axioms UorAtlas.Closure.CommClosure.below.casesOn
#print axioms UorAtlas.Closure.CommClosure.below.comm
#print axioms UorAtlas.Closure.CommClosure.below.comp
#print axioms UorAtlas.Closure.CommClosure.below.inv
#print axioms UorAtlas.Closure.CommClosure.below.one
#print axioms UorAtlas.Closure.CommClosure.below.rec
#print axioms UorAtlas.Closure.CommClosure.brecOn
#print axioms UorAtlas.Closure.CommClosure.casesOn
#print axioms UorAtlas.Closure.CommClosure.comm
#print axioms UorAtlas.Closure.CommClosure.comp
#print axioms UorAtlas.Closure.CommClosure.inv
#print axioms UorAtlas.Closure.CommClosure.one
#print axioms UorAtlas.Closure.CommClosure.rec
#print axioms UorAtlas.Closure.CommClosure.recOn
#print axioms UorAtlas.Closure.DerivedOf
#print axioms UorAtlas.Closure.GaugeCenter
#print axioms UorAtlas.Closure.GeneratedCenter
#print axioms UorAtlas.Closure.HasIndexEight
#print axioms UorAtlas.Closure.LowerCentral
#print axioms UorAtlas.Closure.LowerCentral.match_1
#print axioms UorAtlas.Closure.LowerCentralStep
#print axioms UorAtlas.Closure.NilpotentPred
#print axioms UorAtlas.Closure.NormalIn
#print axioms UorAtlas.Closure.SolvablePred
#print axioms UorAtlas.Closure.SubgroupPred
#print axioms UorAtlas.Closure.T31
#print axioms UorAtlas.Closure.T50
#print axioms UorAtlas.Closure.T54
#print axioms UorAtlas.Closure.T55
#print axioms UorAtlas.Closure.T56
#print axioms UorAtlas.Closure.abelianDistinctCert
#print axioms UorAtlas.Closure.abelianDistinctCheck
#print axioms UorAtlas.Closure.abelianJ
#print axioms UorAtlas.Closure.abelianJAt
#print axioms UorAtlas.Closure.abelianK
#print axioms UorAtlas.Closure.abelianKAt
#print axioms UorAtlas.Closure.abelianRepGt
#print axioms UorAtlas.Closure.abelianRepGt_ok
#print axioms UorAtlas.Closure.abelianRepList
#print axioms UorAtlas.Closure.abelianRepList.eq_1
#print axioms UorAtlas.Closure.abelianRepList_length
#print axioms UorAtlas.Closure.abelianRepList_nodup
#print axioms UorAtlas.Closure.abelianRepP
#print axioms UorAtlas.Closure.abelianRepQ
#print axioms UorAtlas.Closure.abelianRepQ_ok
#print axioms UorAtlas.Closure.abelianRepSeven
#print axioms UorAtlas.Closure.abelianRepWords
#print axioms UorAtlas.Closure.abelianStepCert
#print axioms UorAtlas.Closure.abelianStepCheck
#print axioms UorAtlas.Closure.abelianStepCheck.eq_1
#print axioms UorAtlas.Closure.abelian_coset
#print axioms UorAtlas.Closure.abelian_cosets_distinct
#print axioms UorAtlas.Closure.abelian_step
#print axioms UorAtlas.Closure.centerElement
#print axioms UorAtlas.Closure.centerElement.eq_1
#print axioms UorAtlas.Closure.centerElementCert
#print axioms UorAtlas.Closure.centerElement_center
#print axioms UorAtlas.Closure.centerElement_gen
#print axioms UorAtlas.Closure.centerPointCert
#print axioms UorAtlas.Closure.centerPointGt
#print axioms UorAtlas.Closure.centerPointGt_ok
#print axioms UorAtlas.Closure.centerPointOK
#print axioms UorAtlas.Closure.centerPointOK.eq_1
#print axioms UorAtlas.Closure.centerPointWords
#print axioms UorAtlas.Closure.centerQ
#print axioms UorAtlas.Closure.centerQ.eq_1
#print axioms UorAtlas.Closure.centerReachBases
#print axioms UorAtlas.Closure.centerReachBases.eq_1
#print axioms UorAtlas.Closure.centerReachCert
#print axioms UorAtlas.Closure.centerReachWord
#print axioms UorAtlas.Closure.centerWord
#print axioms UorAtlas.Closure.center_exact
#print axioms UorAtlas.Closure.center_image_candidates
#print axioms UorAtlas.Closure.central_fix_zero
#print axioms UorAtlas.Closure.central_fixes_reached
#print axioms UorAtlas.Closure.chainMemberCheck
#print axioms UorAtlas.Closure.chainMember_of_check
#print axioms UorAtlas.Closure.commClosure_mono_right
#print axioms UorAtlas.Closure.commClosure_of_gen
#print axioms UorAtlas.Closure.commClosure_subgroup
#print axioms UorAtlas.Closure.commOneAll
#print axioms UorAtlas.Closure.commSeriesCert
#print axioms UorAtlas.Closure.commThreeAll
#print axioms UorAtlas.Closure.commTwoAll
#print axioms UorAtlas.Closure.commutator
#print axioms UorAtlas.Closure.commutator.eq_1
#print axioms UorAtlas.Closure.commutator_comp_left
#print axioms UorAtlas.Closure.commutator_comp_right
#print axioms UorAtlas.Closure.commutator_inv_left
#print axioms UorAtlas.Closure.commutator_inv_right
#print axioms UorAtlas.Closure.commutator_one_left
#print axioms UorAtlas.Closure.commutator_one_right
#print axioms UorAtlas.Closure.commute_inverse_right
#print axioms UorAtlas.Closure.commutes_with_generated
#print axioms UorAtlas.Closure.conjugate
#print axioms UorAtlas.Closure.conjugate.eq_1
#print axioms UorAtlas.Closure.conjugate_comp
#print axioms UorAtlas.Closure.conjugate_group_inv
#print axioms UorAtlas.Closure.conjugate_inj
#print axioms UorAtlas.Closure.conjugate_inv
#print axioms UorAtlas.Closure.conjugate_one
#print axioms UorAtlas.Closure.conjugate_outer_comp
#print axioms UorAtlas.Closure.cosActionDistinct
#print axioms UorAtlas.Closure.cosActionDistinctCert
#print axioms UorAtlas.Closure.cosActionDistinctOK
#print axioms UorAtlas.Closure.cosIndex
#print axioms UorAtlas.Closure.cosInvOK
#print axioms UorAtlas.Closure.cosInvOK.eq_1
#print axioms UorAtlas.Closure.cosList
#print axioms UorAtlas.Closure.cosList.eq_1
#print axioms UorAtlas.Closure.cosList_gauge
#print axioms UorAtlas.Closure.cosList_inv
#print axioms UorAtlas.Closure.cosList_length
#print axioms UorAtlas.Closure.cosList_mul
#print axioms UorAtlas.Closure.cosList_nodup
#print axioms UorAtlas.Closure.cosList_one
#print axioms UorAtlas.Closure.cosMulOK
#print axioms UorAtlas.Closure.cosMulOK.eq_1
#print axioms UorAtlas.Closure.cosP_gauge
#print axioms UorAtlas.Closure.cosP_gen
#print axioms UorAtlas.Closure.cosSubgroupCert
#print axioms UorAtlas.Closure.d8Reflection
#print axioms UorAtlas.Closure.d8Rotation
#print axioms UorAtlas.Closure.derivedChainLengths
#print axioms UorAtlas.Closure.derivedFourAll
#print axioms UorAtlas.Closure.derivedFourExact
#print axioms UorAtlas.Closure.derivedIndexEight
#print axioms UorAtlas.Closure.derivedOneChain
#print axioms UorAtlas.Closure.derivedOneExact
#print axioms UorAtlas.Closure.derivedOneGeneratorsComm
#print axioms UorAtlas.Closure.derivedOneGt
#print axioms UorAtlas.Closure.derivedOneGt_ok
#print axioms UorAtlas.Closure.derivedOneOrder
#print axioms UorAtlas.Closure.derivedOneSpec
#print axioms UorAtlas.Closure.derivedOneWords
#print axioms UorAtlas.Closure.derivedOne_sub
#print axioms UorAtlas.Closure.derivedThreeChain
#print axioms UorAtlas.Closure.derivedThreeExact
#print axioms UorAtlas.Closure.derivedThreeGeneratorsAbelian
#print axioms UorAtlas.Closure.derivedThreeGeneratorsComm
#print axioms UorAtlas.Closure.derivedThreeGt
#print axioms UorAtlas.Closure.derivedThreeGt_ok
#print axioms UorAtlas.Closure.derivedThreeOrder
#print axioms UorAtlas.Closure.derivedThreeSpec
#print axioms UorAtlas.Closure.derivedThreeWords
#print axioms UorAtlas.Closure.derivedThree_sub_two
#print axioms UorAtlas.Closure.derivedTwoChain
#print axioms UorAtlas.Closure.derivedTwoExact
#print axioms UorAtlas.Closure.derivedTwoGeneratorsComm
#print axioms UorAtlas.Closure.derivedTwoGt
#print axioms UorAtlas.Closure.derivedTwoGt.eq_1
#print axioms UorAtlas.Closure.derivedTwoGt_ok
#print axioms UorAtlas.Closure.derivedTwoOrder
#print axioms UorAtlas.Closure.derivedTwoSpec
#print axioms UorAtlas.Closure.derivedTwoWords
#print axioms UorAtlas.Closure.derivedTwoWords.eq_1
#print axioms UorAtlas.Closure.derivedTwo_in_every_lower
#print axioms UorAtlas.Closure.derivedTwo_sub
#print axioms UorAtlas.Closure.derivedTwo_sub_one
#print axioms UorAtlas.Closure.exact_commClosure_of_generators
#print axioms UorAtlas.Closure.gaugeCenterList
#print axioms UorAtlas.Closure.gaugeCenterList.eq_1
#print axioms UorAtlas.Closure.gaugeCenterList_nodup
#print axioms UorAtlas.Closure.gaugeCenterOrder
#print axioms UorAtlas.Closure.gaugeOrderW0
#print axioms UorAtlas.Closure.gauge_fix_bases_trivial
#print axioms UorAtlas.Closure.gauge_not_nilpotent
#print axioms UorAtlas.Closure.gauge_solvable
#print axioms UorAtlas.Closure.gen_subgroupPred
#print axioms UorAtlas.Closure.generatedCenter_iff
#print axioms UorAtlas.Closure.generatedCenter_subgroup
#print axioms UorAtlas.Closure.generated_mixed_commutators_of_letters
#print axioms UorAtlas.Closure.generated_normal_of_letters
#print axioms UorAtlas.Closure.getD_tabOK
#print axioms UorAtlas.Closure.kernel_inter_cosList
#print axioms UorAtlas.Closure.lowerThreeAll
#print axioms UorAtlas.Closure.lowerThreeExact
#print axioms UorAtlas.Closure.lowerThreeGt
#print axioms UorAtlas.Closure.lowerThreeWitnessWords
#print axioms UorAtlas.Closure.lowerThreeWitnesses
#print axioms UorAtlas.Closure.lowerTwoAll
#print axioms UorAtlas.Closure.lowerTwoExact
#print axioms UorAtlas.Closure.lowerTwoGt
#print axioms UorAtlas.Closure.lowerTwoWitnessWords
#print axioms UorAtlas.Closure.lowerTwoWitnesses
#print axioms UorAtlas.Closure.lowerWitness
#print axioms UorAtlas.Closure.lowerWitness_mem
#print axioms UorAtlas.Closure.lowerWitness_ne
#print axioms UorAtlas.Closure.mem_cosList
#print axioms UorAtlas.Closure.mixedCommCheck
#print axioms UorAtlas.Closure.mixedCommutatorGt
#print axioms UorAtlas.Closure.mixedCommutatorGt_ok
#print axioms UorAtlas.Closure.mixedGeneratorClosure
#print axioms UorAtlas.Closure.mixed_comm_of_check
#print axioms UorAtlas.Closure.nodup_map_inj
#print axioms UorAtlas.Closure.normalCheck
#print axioms UorAtlas.Closure.normalDerivedOne
#print axioms UorAtlas.Closure.normalDerivedThreeInTwo
#print axioms UorAtlas.Closure.normalDerivedTwo
#print axioms UorAtlas.Closure.normalDerivedTwoInOne
#print axioms UorAtlas.Closure.normalSeriesCert
#print axioms UorAtlas.Closure.normal_of_check
#print axioms UorAtlas.Closure.pairCommutator
#print axioms UorAtlas.Closure.pairCommutator_perm
#print axioms UorAtlas.Closure.pairConjugate
#print axioms UorAtlas.Closure.pairConjugate_perm
#print axioms UorAtlas.Closure.pairInv
#print axioms UorAtlas.Closure.pairInv_perm
#print axioms UorAtlas.Closure.pairMul
#print axioms UorAtlas.Closure.pairMul_perm
#print axioms UorAtlas.Closure.trivial_normal
#print axioms UorAtlas.Closure.witness_factorisation
#print axioms UorAtlas.Closure.witness_factorisation_unique
#print axioms UorAtlas.Closure.witness_kernel_normal
#print axioms UorAtlas.Group.stabSpec.eq_1
#print axioms UorAtlas.LexLeanInternal.decl1101
#print axioms UorAtlas.LexLeanInternal.decl1125
#print axioms UorAtlas.LexLeanInternal.decl114
#print axioms UorAtlas.LexLeanInternal.decl1144
#print axioms UorAtlas.LexLeanInternal.decl1185
#print axioms UorAtlas.LexLeanInternal.decl1273
#print axioms UorAtlas.LexLeanInternal.decl1279
#print axioms UorAtlas.LexLeanInternal.decl1340
#print axioms UorAtlas.LexLeanInternal.decl1423
#print axioms UorAtlas.LexLeanInternal.decl1453
#print axioms UorAtlas.LexLeanInternal.decl1474
#print axioms UorAtlas.LexLeanInternal.decl149
#print axioms UorAtlas.LexLeanInternal.decl1505
#print axioms UorAtlas.LexLeanInternal.decl1606
#print axioms UorAtlas.LexLeanInternal.decl1656
#print axioms UorAtlas.LexLeanInternal.decl1675
#print axioms UorAtlas.LexLeanInternal.decl1684
#print axioms UorAtlas.LexLeanInternal.decl211
#print axioms UorAtlas.LexLeanInternal.decl241
#print axioms UorAtlas.LexLeanInternal.decl267
#print axioms UorAtlas.LexLeanInternal.decl27
#print axioms UorAtlas.LexLeanInternal.decl274
#print axioms UorAtlas.LexLeanInternal.decl322
#print axioms UorAtlas.LexLeanInternal.decl358
#print axioms UorAtlas.LexLeanInternal.decl405
#print axioms UorAtlas.LexLeanInternal.decl417
#print axioms UorAtlas.LexLeanInternal.decl418
#print axioms UorAtlas.LexLeanInternal.decl44
#print axioms UorAtlas.LexLeanInternal.decl475
#print axioms UorAtlas.LexLeanInternal.decl571
#print axioms UorAtlas.LexLeanInternal.decl610
#print axioms UorAtlas.LexLeanInternal.decl899
#print axioms UorAtlas.LexLeanInternal.decl907
#print axioms UorAtlas.LexLeanInternal.decl976
