module
import LexLeanExample.Category
#print axioms UorAtlas.Category.ActionData
#print axioms UorAtlas.Category.ActionData.Grp
#print axioms UorAtlas.Category.ActionData.IsOb
#print axioms UorAtlas.Category.ActionData.Obj
#print axioms UorAtlas.Category.ActionData.act
#print axioms UorAtlas.Category.ActionData.act_comp
#print axioms UorAtlas.Category.ActionData.act_one
#print axioms UorAtlas.Category.ActionData.base
#print axioms UorAtlas.Category.ActionData.base_isOb
#print axioms UorAtlas.Category.ActionData.casesOn
#print axioms UorAtlas.Category.ActionData.comp_mem
#print axioms UorAtlas.Category.ActionData.ctorIdx
#print axioms UorAtlas.Category.ActionData.inv_mem
#print axioms UorAtlas.Category.ActionData.mk
#print axioms UorAtlas.Category.ActionData.mk.inj
#print axioms UorAtlas.Category.ActionData.mk.injEq
#print axioms UorAtlas.Category.ActionData.mk.noConfusion
#print axioms UorAtlas.Category.ActionData.mk.sizeOf_spec
#print axioms UorAtlas.Category.ActionData.noConfusion
#print axioms UorAtlas.Category.ActionData.noConfusionType
#print axioms UorAtlas.Category.ActionData.one_mem
#print axioms UorAtlas.Category.ActionData.rec
#print axioms UorAtlas.Category.ActionData.recOn
#print axioms UorAtlas.Category.ActionData.stable
#print axioms UorAtlas.Category.ActionData.transitive
#print axioms UorAtlas.Category.Atl.Hom
#print axioms UorAtlas.Category.Atl.Ob
#print axioms UorAtlas.Category.Atl.basePt
#print axioms UorAtlas.Category.Atl.compHom
#print axioms UorAtlas.Category.Atl.idHom
#print axioms UorAtlas.Category.Atl.invHom
#print axioms UorAtlas.Category.AtlasAction
#print axioms UorAtlas.Category.AtlasAction.casesOn
#print axioms UorAtlas.Category.AtlasAction.ctorIdx
#print axioms UorAtlas.Category.AtlasAction.mk
#print axioms UorAtlas.Category.AtlasAction.mk.inj
#print axioms UorAtlas.Category.AtlasAction.mk.injEq
#print axioms UorAtlas.Category.AtlasAction.mk.noConfusion
#print axioms UorAtlas.Category.AtlasAction.mk.sizeOf_spec
#print axioms UorAtlas.Category.AtlasAction.noConfusion
#print axioms UorAtlas.Category.AtlasAction.noConfusionType
#print axioms UorAtlas.Category.AtlasAction.rec
#print axioms UorAtlas.Category.AtlasAction.recOn
#print axioms UorAtlas.Category.AtlasAction.stab_card
#print axioms UorAtlas.Category.AtlasAction.toActionData
#print axioms UorAtlas.Category.Cat
#print axioms UorAtlas.Category.Cat.Hom
#print axioms UorAtlas.Category.Cat.Ob
#print axioms UorAtlas.Category.Cat.assoc
#print axioms UorAtlas.Category.Cat.casesOn
#print axioms UorAtlas.Category.Cat.comp
#print axioms UorAtlas.Category.Cat.comp_id
#print axioms UorAtlas.Category.Cat.ctorIdx
#print axioms UorAtlas.Category.Cat.id_comp
#print axioms UorAtlas.Category.Cat.idm
#print axioms UorAtlas.Category.Cat.mk
#print axioms UorAtlas.Category.Cat.mk.inj
#print axioms UorAtlas.Category.Cat.mk.injEq
#print axioms UorAtlas.Category.Cat.mk.noConfusion
#print axioms UorAtlas.Category.Cat.mk.sizeOf_spec
#print axioms UorAtlas.Category.Cat.noConfusion
#print axioms UorAtlas.Category.Cat.noConfusionType
#print axioms UorAtlas.Category.Cat.rec
#print axioms UorAtlas.Category.Cat.recOn
#print axioms UorAtlas.Category.CatFunctor
#print axioms UorAtlas.Category.CatFunctor.casesOn
#print axioms UorAtlas.Category.CatFunctor.ctorIdx
#print axioms UorAtlas.Category.CatFunctor.map
#print axioms UorAtlas.Category.CatFunctor.map_comp
#print axioms UorAtlas.Category.CatFunctor.map_id
#print axioms UorAtlas.Category.CatFunctor.mk
#print axioms UorAtlas.Category.CatFunctor.mk.inj
#print axioms UorAtlas.Category.CatFunctor.mk.injEq
#print axioms UorAtlas.Category.CatFunctor.mk.noConfusion
#print axioms UorAtlas.Category.CatFunctor.mk.sizeOf_spec
#print axioms UorAtlas.Category.CatFunctor.noConfusion
#print axioms UorAtlas.Category.CatFunctor.noConfusionType
#print axioms UorAtlas.Category.CatFunctor.obj
#print axioms UorAtlas.Category.CatFunctor.rec
#print axioms UorAtlas.Category.CatFunctor.recOn
#print axioms UorAtlas.Category.CosetRel
#print axioms UorAtlas.Category.Cosets
#print axioms UorAtlas.Category.D23
#print axioms UorAtlas.Category.D24
#print axioms UorAtlas.Category.D25
#print axioms UorAtlas.Category.D25.inv
#print axioms UorAtlas.Category.D25.inv_mul
#print axioms UorAtlas.Category.D25.mul
#print axioms UorAtlas.Category.D25.mul_assoc
#print axioms UorAtlas.Category.D25.mul_inv
#print axioms UorAtlas.Category.D25.mul_one
#print axioms UorAtlas.Category.D25.one
#print axioms UorAtlas.Category.D25.one_mul
#print axioms UorAtlas.Category.D26
#print axioms UorAtlas.Category.D27
#print axioms UorAtlas.Category.D59
#print axioms UorAtlas.Category.D59_spec
#print axioms UorAtlas.Category.GrpEl
#print axioms UorAtlas.Category.HasCard
#print axioms UorAtlas.Category.HasCard.exists_ne
#print axioms UorAtlas.Category.HasCard.ofBij
#print axioms UorAtlas.Category.HasCard.one_of_unique
#print axioms UorAtlas.Category.IsCatEquivalence
#print axioms UorAtlas.Category.IsStrictInitial
#print axioms UorAtlas.Category.IsTerminal
#print axioms UorAtlas.Category.IsZero
#print axioms UorAtlas.Category.Isoc
#print axioms UorAtlas.Category.SkelOb
#print axioms UorAtlas.Category.SymThree.action
#print axioms UorAtlas.Category.SymThree.fixZero
#print axioms UorAtlas.Category.SymThree.fixZero_gen
#print axioms UorAtlas.Category.SymThree.hom_card
#print axioms UorAtlas.Category.SymThree.not_initial
#print axioms UorAtlas.Category.SymThree.stab_card
#print axioms UorAtlas.Category.T33
#print axioms UorAtlas.Category.T34
#print axioms UorAtlas.Category.T35
#print axioms UorAtlas.Category.T36
#print axioms UorAtlas.Category.T37
#print axioms UorAtlas.Category.T38
#print axioms UorAtlas.Category.T40
#print axioms UorAtlas.Category.T41
#print axioms UorAtlas.Category.T42
#print axioms UorAtlas.Category.T43
#print axioms UorAtlas.Category.T44
#print axioms UorAtlas.Category.T45
#print axioms UorAtlas.Category.T46
#print axioms UorAtlas.Category.T47
#print axioms UorAtlas.Category.T63
#print axioms UorAtlas.Category.T63a
#print axioms UorAtlas.Category.T64
#print axioms UorAtlas.Category.ThinHom
#print axioms UorAtlas.Category.ThinRel
#print axioms UorAtlas.Category.autGroupoid
#print axioms UorAtlas.Category.card_aut_of_card_base
#print axioms UorAtlas.Category.card_end_one_of_initial
#print axioms UorAtlas.Category.card_hom_of_card_aut
#print axioms UorAtlas.Category.cosetRel_equivalence
#print axioms UorAtlas.Category.deloopFunctor
#print axioms UorAtlas.Category.homFromBase
#print axioms UorAtlas.Category.orbitMap
#print axioms UorAtlas.Category.orbitMap_mk
#print axioms UorAtlas.Category.rAct
#print axioms UorAtlas.Category.skelRep
#print axioms UorAtlas.Category.skelRep_section
#print axioms UorAtlas.Category.skelThin
#print axioms UorAtlas.Category.skel_unique
#print axioms UorAtlas.Category.thinComp
#print axioms UorAtlas.Category.thin_unique
#print axioms UorAtlas.LexLeanInternal.decl100
#print axioms UorAtlas.LexLeanInternal.decl1084
#print axioms UorAtlas.LexLeanInternal.decl1135
#print axioms UorAtlas.LexLeanInternal.decl1138
#print axioms UorAtlas.LexLeanInternal.decl1172
#print axioms UorAtlas.LexLeanInternal.decl1173
#print axioms UorAtlas.LexLeanInternal.decl124
#print axioms UorAtlas.LexLeanInternal.decl1245
#print axioms UorAtlas.LexLeanInternal.decl1249
#print axioms UorAtlas.LexLeanInternal.decl1263
#print axioms UorAtlas.LexLeanInternal.decl1266
#print axioms UorAtlas.LexLeanInternal.decl1325
#print axioms UorAtlas.LexLeanInternal.decl1371
#print axioms UorAtlas.LexLeanInternal.decl1375
#print axioms UorAtlas.LexLeanInternal.decl140
#print axioms UorAtlas.LexLeanInternal.decl1433
#print axioms UorAtlas.LexLeanInternal.decl1441
#print axioms UorAtlas.LexLeanInternal.decl1454
#print axioms UorAtlas.LexLeanInternal.decl1478
#print axioms UorAtlas.LexLeanInternal.decl1485
#print axioms UorAtlas.LexLeanInternal.decl1486
#print axioms UorAtlas.LexLeanInternal.decl1497
#print axioms UorAtlas.LexLeanInternal.decl1499
#print axioms UorAtlas.LexLeanInternal.decl1522
#print axioms UorAtlas.LexLeanInternal.decl1564
#print axioms UorAtlas.LexLeanInternal.decl1590
#print axioms UorAtlas.LexLeanInternal.decl162
#print axioms UorAtlas.LexLeanInternal.decl1654
#print axioms UorAtlas.LexLeanInternal.decl1657
#print axioms UorAtlas.LexLeanInternal.decl1694
#print axioms UorAtlas.LexLeanInternal.decl178
#print axioms UorAtlas.LexLeanInternal.decl202
#print axioms UorAtlas.LexLeanInternal.decl209
#print axioms UorAtlas.LexLeanInternal.decl223
#print axioms UorAtlas.LexLeanInternal.decl281
#print axioms UorAtlas.LexLeanInternal.decl489
#print axioms UorAtlas.LexLeanInternal.decl495
#print axioms UorAtlas.LexLeanInternal.decl592
#print axioms UorAtlas.LexLeanInternal.decl637
#print axioms UorAtlas.LexLeanInternal.decl662
#print axioms UorAtlas.LexLeanInternal.decl68
#print axioms UorAtlas.LexLeanInternal.decl701
#print axioms UorAtlas.LexLeanInternal.decl713
#print axioms UorAtlas.LexLeanInternal.decl728
#print axioms UorAtlas.LexLeanInternal.decl741
#print axioms UorAtlas.LexLeanInternal.decl790
#print axioms UorAtlas.LexLeanInternal.decl89
#print axioms UorAtlas.LexLeanInternal.decl914
#print axioms UorAtlas.LexLeanInternal.decl961
