module
import LexLeanExample.Group
#print axioms UorAtlas.Blocks.union4.eq_1
#print axioms UorAtlas.Group.A_eq_one_iff
#print axioms UorAtlas.Group.A_le_one
#print axioms UorAtlas.Group.Agree
#print axioms UorAtlas.Group.AutA
#print axioms UorAtlas.Group.ClSet
#print axioms UorAtlas.Group.Cos
#print axioms UorAtlas.Group.Cos.casesOn
#print axioms UorAtlas.Group.Cos.ctorIdx
#print axioms UorAtlas.Group.Cos.mk
#print axioms UorAtlas.Group.Cos.mk.inj
#print axioms UorAtlas.Group.Cos.mk.injEq
#print axioms UorAtlas.Group.Cos.mk.noConfusion
#print axioms UorAtlas.Group.Cos.mk.sizeOf_spec
#print axioms UorAtlas.Group.Cos.noConfusion
#print axioms UorAtlas.Group.Cos.noConfusionType
#print axioms UorAtlas.Group.Cos.pt
#print axioms UorAtlas.Group.Cos.rec
#print axioms UorAtlas.Group.Cos.recOn
#print axioms UorAtlas.Group.Cos.tb
#print axioms UorAtlas.Group.Cos.wd
#print axioms UorAtlas.Group.D20
#print axioms UorAtlas.Group.D20.eq_1
#print axioms UorAtlas.Group.D20_adj
#print axioms UorAtlas.Group.D20_apply
#print axioms UorAtlas.Group.D20_inv
#print axioms UorAtlas.Group.D20fold
#print axioms UorAtlas.Group.D20fold.match_1
#print axioms UorAtlas.Group.D20fold_neg
#print axioms UorAtlas.Group.D20fold_root
#print axioms UorAtlas.Group.D20fold_simple
#print axioms UorAtlas.Group.D20idx
#print axioms UorAtlas.Group.D20idx_lt
#print axioms UorAtlas.Group.D20lit
#print axioms UorAtlas.Group.D20litOK
#print axioms UorAtlas.Group.D20lit_eq
#print axioms UorAtlas.Group.D20perm
#print axioms UorAtlas.Group.D20tab
#print axioms UorAtlas.Group.D20tabOK
#print axioms UorAtlas.Group.D20tab_mem
#print axioms UorAtlas.Group.D20vec
#print axioms UorAtlas.Group.D20vec_neg
#print axioms UorAtlas.Group.D20vec_rep_cases
#print axioms UorAtlas.Group.D21
#print axioms UorAtlas.Group.D21.eq_1
#print axioms UorAtlas.Group.D21_iff
#print axioms UorAtlas.Group.D21_subgroup
#print axioms UorAtlas.Group.D21a
#print axioms UorAtlas.Group.D21a_commute
#print axioms UorAtlas.Group.D28
#print axioms UorAtlas.Group.D28_group
#print axioms UorAtlas.Group.D28a
#print axioms UorAtlas.Group.D28a_action
#print axioms UorAtlas.Group.D29
#print axioms UorAtlas.Group.D29_iff
#print axioms UorAtlas.Group.D30
#print axioms UorAtlas.Group.D30_comp
#print axioms UorAtlas.Group.D30_id
#print axioms UorAtlas.Group.D30_neg
#print axioms UorAtlas.Group.HasOrder
#print axioms UorAtlas.Group.HasOrderP
#print axioms UorAtlas.Group.Level
#print axioms UorAtlas.Group.Level.Formed
#print axioms UorAtlas.Group.Level.basePt
#print axioms UorAtlas.Group.Level.bp
#print axioms UorAtlas.Group.Level.casesOn
#print axioms UorAtlas.Group.Level.ctorIdx
#print axioms UorAtlas.Group.Level.gt
#print axioms UorAtlas.Group.Level.mk
#print axioms UorAtlas.Group.Level.mk.inj
#print axioms UorAtlas.Group.Level.mk.injEq
#print axioms UorAtlas.Group.Level.mk.noConfusion
#print axioms UorAtlas.Group.Level.mk.sizeOf_spec
#print axioms UorAtlas.Group.Level.msk
#print axioms UorAtlas.Group.Level.nextGt
#print axioms UorAtlas.Group.Level.noConfusion
#print axioms UorAtlas.Group.Level.noConfusionType
#print axioms UorAtlas.Group.Level.nw
#print axioms UorAtlas.Group.Level.orb
#print axioms UorAtlas.Group.Level.orbFin
#print axioms UorAtlas.Group.Level.orbFin.eq_1
#print axioms UorAtlas.Group.Level.rec
#print axioms UorAtlas.Group.Level.recOn
#print axioms UorAtlas.Group.Level.trP
#print axioms UorAtlas.Group.Level.trQ
#print axioms UorAtlas.Group.Level.trQ.eq_1
#print axioms UorAtlas.Group.Level.trQ.match_1
#print axioms UorAtlas.Group.SpanOf
#print axioms UorAtlas.Group.SpanOf.add
#print axioms UorAtlas.Group.SpanOf.below
#print axioms UorAtlas.Group.SpanOf.below.add
#print axioms UorAtlas.Group.SpanOf.below.casesOn
#print axioms UorAtlas.Group.SpanOf.below.neg
#print axioms UorAtlas.Group.SpanOf.below.rec
#print axioms UorAtlas.Group.SpanOf.below.root
#print axioms UorAtlas.Group.SpanOf.below.zero
#print axioms UorAtlas.Group.SpanOf.brecOn
#print axioms UorAtlas.Group.SpanOf.casesOn
#print axioms UorAtlas.Group.SpanOf.neg
#print axioms UorAtlas.Group.SpanOf.rec
#print axioms UorAtlas.Group.SpanOf.recOn
#print axioms UorAtlas.Group.SpanOf.root
#print axioms UorAtlas.Group.SpanOf.zero
#print axioms UorAtlas.Group.T28
#print axioms UorAtlas.Group.T39p
#print axioms UorAtlas.Group.T59
#print axioms UorAtlas.Group.T59a
#print axioms UorAtlas.Group.T59p
#print axioms UorAtlas.Group.T59p0
#print axioms UorAtlas.Group.TabsOK
#print axioms UorAtlas.Group.V66a
#print axioms UorAtlas.Group.V66b
#print axioms UorAtlas.Group.V66c
#print axioms UorAtlas.Group.V66comp
#print axioms UorAtlas.Group.V66comp_at
#print axioms UorAtlas.Group.V67
#print axioms UorAtlas.Group.V68a
#print axioms UorAtlas.Group.V68b
#print axioms UorAtlas.Group.V76
#print axioms UorAtlas.Group.V77
#print axioms UorAtlas.Group.W0
#print axioms UorAtlas.Group.W0_eq
#print axioms UorAtlas.Group.W0comp
#print axioms UorAtlas.Group.aOf
#print axioms UorAtlas.Group.aOf_apply
#print axioms UorAtlas.Group.aOf_gen
#print axioms UorAtlas.Group.actP
#print axioms UorAtlas.Group.actP.eq_1
#print axioms UorAtlas.Group.actP_comp
#print axioms UorAtlas.Group.actP_inj
#print axioms UorAtlas.Group.actP_inv
#print axioms UorAtlas.Group.actP_one
#print axioms UorAtlas.Group.actP_swap
#print axioms UorAtlas.Group.actPres
#print axioms UorAtlas.Group.actPres_comp
#print axioms UorAtlas.Group.actT
#print axioms UorAtlas.Group.actT_eq
#print axioms UorAtlas.Group.adjBase
#print axioms UorAtlas.Group.adjBase_eq
#print axioms UorAtlas.Group.adjBit
#print axioms UorAtlas.Group.adjBit_eq
#print axioms UorAtlas.Group.adjN_image
#print axioms UorAtlas.Group.adjN_imageA
#print axioms UorAtlas.Group.adjN_image_of_pres
#print axioms UorAtlas.Group.adjN_lt
#print axioms UorAtlas.Group.adjPack
#print axioms UorAtlas.Group.adjRaw_lt
#print axioms UorAtlas.Group.adjRow
#print axioms UorAtlas.Group.adjRow_eq
#print axioms UorAtlas.Group.adjRow_lt
#print axioms UorAtlas.Group.agree_one_iff
#print axioms UorAtlas.Group.agree_push
#print axioms UorAtlas.Group.allLt_of
#print axioms UorAtlas.Group.ap
#print axioms UorAtlas.Group.ap_D20tab
#print axioms UorAtlas.Group.ap_eq
#print axioms UorAtlas.Group.ap_idT
#print axioms UorAtlas.Group.ap_lt
#print axioms UorAtlas.Group.ap_mulT
#print axioms UorAtlas.Group.ap_pak
#print axioms UorAtlas.Group.apply_neg_id
#print axioms UorAtlas.Group.arow
#print axioms UorAtlas.Group.autA_autGamma
#print axioms UorAtlas.Group.autA_comp
#print axioms UorAtlas.Group.autA_gen
#print axioms UorAtlas.Group.autA_inv
#print axioms UorAtlas.Group.autA_of_D21
#print axioms UorAtlas.Group.autA_one
#print axioms UorAtlas.Group.autA_trivial
#print axioms UorAtlas.Group.autChain
#print axioms UorAtlas.Group.autChainLen
#print axioms UorAtlas.Group.autGamma_perm
#print axioms UorAtlas.Group.autGen_of_D21
#print axioms UorAtlas.Group.autGens_eq
#print axioms UorAtlas.Group.autGt
#print axioms UorAtlas.Group.autGt_ok
#print axioms UorAtlas.Group.autSpec
#print axioms UorAtlas.Group.aut_fix_trivial
#print axioms UorAtlas.Group.badBlk
#print axioms UorAtlas.Group.baseFix
#print axioms UorAtlas.Group.bfs
#print axioms UorAtlas.Group.bfsGo
#print axioms UorAtlas.Group.bfsGo.match_1
#print axioms UorAtlas.Group.bfsGo.match_3
#print axioms UorAtlas.Group.bfsStep
#print axioms UorAtlas.Group.bfsStep.match_1
#print axioms UorAtlas.Group.bitOn
#print axioms UorAtlas.Group.blkOf
#print axioms UorAtlas.Group.blkOf_blkSet
#print axioms UorAtlas.Group.blkPermT
#print axioms UorAtlas.Group.cert0
#print axioms UorAtlas.Group.cert1
#print axioms UorAtlas.Group.cert2
#print axioms UorAtlas.Group.cert3
#print axioms UorAtlas.Group.cert4
#print axioms UorAtlas.Group.cert5
#print axioms UorAtlas.Group.cert6
#print axioms UorAtlas.Group.certG0
#print axioms UorAtlas.Group.certG1
#print axioms UorAtlas.Group.certG2
#print axioms UorAtlas.Group.certG3
#print axioms UorAtlas.Group.certG4
#print axioms UorAtlas.Group.certG5
#print axioms UorAtlas.Group.certG6
#print axioms UorAtlas.Group.chainCheck
#print axioms UorAtlas.Group.chainCheck.match_1
#print axioms UorAtlas.Group.chainLen
#print axioms UorAtlas.Group.chainLen.match_1
#print axioms UorAtlas.Group.chain_step
#print axioms UorAtlas.Group.classSet_W0
#print axioms UorAtlas.Group.classSet_actP
#print axioms UorAtlas.Group.classSet_arow
#print axioms UorAtlas.Group.classSet_inter
#print axioms UorAtlas.Group.classSet_ofNat
#print axioms UorAtlas.Group.cnt2
#print axioms UorAtlas.Group.cnt2_inv
#print axioms UorAtlas.Group.cnt2b
#print axioms UorAtlas.Group.cnt2b_eq
#print axioms UorAtlas.Group.cnt2t
#print axioms UorAtlas.Group.cnt2t_inv
#print axioms UorAtlas.Group.cnt2tb
#print axioms UorAtlas.Group.cnt2tb_eq
#print axioms UorAtlas.Group.cnt2tb_image
#print axioms UorAtlas.Group.cnt3
#print axioms UorAtlas.Group.cnt3_inv
#print axioms UorAtlas.Group.cnt3b
#print axioms UorAtlas.Group.cnt3b_eq
#print axioms UorAtlas.Group.cnt3b_image
#print axioms UorAtlas.Group.cosAt
#print axioms UorAtlas.Group.cosAt.eq_1
#print axioms UorAtlas.Group.cosAt.eq_2
#print axioms UorAtlas.Group.cosAt.eq_def
#print axioms UorAtlas.Group.cosAt.match_1
#print axioms UorAtlas.Group.cosAt_none
#print axioms UorAtlas.Group.cosAt_of_mem
#print axioms UorAtlas.Group.cosAt_some
#print axioms UorAtlas.Group.cosJ
#print axioms UorAtlas.Group.cosK
#print axioms UorAtlas.Group.cosMove
#print axioms UorAtlas.Group.cosP
#print axioms UorAtlas.Group.cosP_zero
#print axioms UorAtlas.Group.cosQ
#print axioms UorAtlas.Group.cosQ_ok
#print axioms UorAtlas.Group.cosRow
#print axioms UorAtlas.Group.cosRow0
#print axioms UorAtlas.Group.cosRow1
#print axioms UorAtlas.Group.cosRow2
#print axioms UorAtlas.Group.cosRow3
#print axioms UorAtlas.Group.cosRow4
#print axioms UorAtlas.Group.cosRow5
#print axioms UorAtlas.Group.cosRow6
#print axioms UorAtlas.Group.cosRow7
#print axioms UorAtlas.Group.cosRowAll
#print axioms UorAtlas.Group.cosWords
#print axioms UorAtlas.Group.cos_fix_zero
#print axioms UorAtlas.Group.cos_step
#print axioms UorAtlas.Group.descendG
#print axioms UorAtlas.Group.descendG_of
#print axioms UorAtlas.Group.descend_of
#print axioms UorAtlas.Group.descend_step
#print axioms UorAtlas.Group.dot_reflect
#print axioms UorAtlas.Group.dvd_dot_repN
#print axioms UorAtlas.Group.dvd_dot_root
#print axioms UorAtlas.Group.emb_matWord
#print axioms UorAtlas.Group.emb_reflMat
#print axioms UorAtlas.Group.evalP
#print axioms UorAtlas.Group.evalP_permsOf
#print axioms UorAtlas.Group.evalT
#print axioms UorAtlas.Group.evalT.match_1
#print axioms UorAtlas.Group.evalT_cons
#print axioms UorAtlas.Group.fin120
#print axioms UorAtlas.Group.fin120_val
#print axioms UorAtlas.Group.fin4_cases
#print axioms UorAtlas.Group.fixed_fin
#print axioms UorAtlas.Group.foldSign
#print axioms UorAtlas.Group.foldSign.match_1
#print axioms UorAtlas.Group.foldSign_spec
#print axioms UorAtlas.Group.gL0
#print axioms UorAtlas.Group.gL1
#print axioms UorAtlas.Group.gL2
#print axioms UorAtlas.Group.gL3
#print axioms UorAtlas.Group.gL4
#print axioms UorAtlas.Group.gL5
#print axioms UorAtlas.Group.gL6
#print axioms UorAtlas.Group.gaugeGammaWitness
#print axioms UorAtlas.Group.gaugeOrderWitness
#print axioms UorAtlas.Group.gauge_blocks
#print axioms UorAtlas.Group.gauge_coset
#print axioms UorAtlas.Group.gauge_eq
#print axioms UorAtlas.Group.genP
#print axioms UorAtlas.Group.genP.eq_1
#print axioms UorAtlas.Group.genP_permsOf
#print axioms UorAtlas.Group.genT
#print axioms UorAtlas.Group.genT.eq_1
#print axioms UorAtlas.Group.genT_even
#print axioms UorAtlas.Group.genT_odd
#print axioms UorAtlas.Group.gen_block_perm
#print axioms UorAtlas.Group.gen_blocks
#print axioms UorAtlas.Group.gen_evalP
#print axioms UorAtlas.Group.gen_fixes
#print axioms UorAtlas.Group.gen_genP
#print axioms UorAtlas.Group.gen_iff_step
#print axioms UorAtlas.Group.gen_ker
#print axioms UorAtlas.Group.gen_maps
#print axioms UorAtlas.Group.gen_nextGt
#print axioms UorAtlas.Group.gen_nil_iff
#print axioms UorAtlas.Group.gen_sub
#print axioms UorAtlas.Group.gensP_adj
#print axioms UorAtlas.Group.getD_mem_or
#print axioms UorAtlas.Group.getD_permsOf
#print axioms UorAtlas.Group.hasKey
#print axioms UorAtlas.Group.hasKey.match_1
#print axioms UorAtlas.Group.hasOrder_nil
#print axioms UorAtlas.Group.hasOrder_step
#print axioms UorAtlas.Group.hasPtC
#print axioms UorAtlas.Group.hasPtC.eq_1
#print axioms UorAtlas.Group.headLevel
#print axioms UorAtlas.Group.idT
#print axioms UorAtlas.Group.imgN
#print axioms UorAtlas.Group.imgN_congr
#print axioms UorAtlas.Group.imgN_succ_neg
#print axioms UorAtlas.Group.imgN_succ_pos
#print axioms UorAtlas.Group.ind_actP
#print axioms UorAtlas.Group.ind_adjRow
#print axioms UorAtlas.Group.ind_inter
#print axioms UorAtlas.Group.invOf4
#print axioms UorAtlas.Group.isEmpty_nil
#print axioms UorAtlas.Group.jAt
#print axioms UorAtlas.Group.kAt
#print axioms UorAtlas.Group.kerChain
#print axioms UorAtlas.Group.kerChainLen
#print axioms UorAtlas.Group.kerGen_of_mem
#print axioms UorAtlas.Group.kerGen_stabPres
#print axioms UorAtlas.Group.kerGt
#print axioms UorAtlas.Group.kerGt_blk
#print axioms UorAtlas.Group.kerGt_ok
#print axioms UorAtlas.Group.kerOrder
#print axioms UorAtlas.Group.kerSpec
#print axioms UorAtlas.Group.kerWords
#print axioms UorAtlas.Group.levelCheck
#print axioms UorAtlas.Group.levelCheck.eq_1
#print axioms UorAtlas.Group.levelG
#print axioms UorAtlas.Group.levelG.eq_1
#print axioms UorAtlas.Group.levelOK
#print axioms UorAtlas.Group.levelOK.eq_1
#print axioms UorAtlas.Group.matWord
#print axioms UorAtlas.Group.matWord.match_1
#print axioms UorAtlas.Group.memChain
#print axioms UorAtlas.Group.memChain.match_1
#print axioms UorAtlas.Group.memChain.match_3
#print axioms UorAtlas.Group.memChain_fix
#print axioms UorAtlas.Group.mem_actP
#print axioms UorAtlas.Group.mem_actP_iff
#print axioms UorAtlas.Group.mem_adjRow
#print axioms UorAtlas.Group.mem_bitset_iff
#print axioms UorAtlas.Group.mem_imgN
#print axioms UorAtlas.Group.mem_orbFin
#print axioms UorAtlas.Group.mem_union4
#print axioms UorAtlas.Group.mkChain
#print axioms UorAtlas.Group.mkChain.eq_1
#print axioms UorAtlas.Group.mkChain.eq_2
#print axioms UorAtlas.Group.mkChain.eq_def
#print axioms UorAtlas.Group.mkChain.match_1
#print axioms UorAtlas.Group.mkChain_bp
#print axioms UorAtlas.Group.mkChain_bp_lt
#print axioms UorAtlas.Group.mkChain_cons
#print axioms UorAtlas.Group.mkChain_spec
#print axioms UorAtlas.Group.mkMask
#print axioms UorAtlas.Group.mkOrb
#print axioms UorAtlas.Group.mkOrb_form
#print axioms UorAtlas.Group.mulT
#print axioms UorAtlas.Group.negMat
#print axioms UorAtlas.Group.negMat_eq
#print axioms UorAtlas.Group.negWord
#print axioms UorAtlas.Group.negWordComp
#print axioms UorAtlas.Group.nodupOrb
#print axioms UorAtlas.Group.nodupOrb.match_1
#print axioms UorAtlas.Group.nodup_flatMap
#print axioms UorAtlas.Group.nodup_orbFin
#print axioms UorAtlas.Group.nodup_pmap
#print axioms UorAtlas.Group.orbitAction
#print axioms UorAtlas.Group.orbitData
#print axioms UorAtlas.Group.orbit_stab_card
#print axioms UorAtlas.Group.pak
#print axioms UorAtlas.Group.pak_eq_pk
#print axioms UorAtlas.Group.pak_succ
#print axioms UorAtlas.Group.permOf4
#print axioms UorAtlas.Group.permOf4.eq_1
#print axioms UorAtlas.Group.permOf4_of_perm
#print axioms UorAtlas.Group.permOf4_toFun
#print axioms UorAtlas.Group.permsOf
#print axioms UorAtlas.Group.permsOf.eq_1
#print axioms UorAtlas.Group.piK
#print axioms UorAtlas.Group.pinCert1
#print axioms UorAtlas.Group.pinCert2
#print axioms UorAtlas.Group.pinCover
#print axioms UorAtlas.Group.pinR1
#print axioms UorAtlas.Group.pinR2
#print axioms UorAtlas.Group.pinRound
#print axioms UorAtlas.Group.pin_fix
#print axioms UorAtlas.Group.profG
#print axioms UorAtlas.Group.profG.eq_1
#print axioms UorAtlas.Group.profG_image
#print axioms UorAtlas.Group.profOK
#print axioms UorAtlas.Group.profOK.eq_1
#print axioms UorAtlas.Group.profOK_image
#print axioms UorAtlas.Group.reflOnChk
#print axioms UorAtlas.Group.reflOnChk0
#print axioms UorAtlas.Group.reflOnChk1
#print axioms UorAtlas.Group.reflOnChk2
#print axioms UorAtlas.Group.reflOnChk3
#print axioms UorAtlas.Group.reflOnChk4
#print axioms UorAtlas.Group.reflOnChk5
#print axioms UorAtlas.Group.reflOnChk6
#print axioms UorAtlas.Group.reflOnChk7
#print axioms UorAtlas.Group.reflOnComp
#print axioms UorAtlas.Group.reflOn_eq
#print axioms UorAtlas.Group.reindex
#print axioms UorAtlas.Group.sOf
#print axioms UorAtlas.Group.sOf_apply
#print axioms UorAtlas.Group.sOf_gen
#print axioms UorAtlas.Group.sRefl_eq
#print axioms UorAtlas.Group.sameAdj
#print axioms UorAtlas.Group.schreier_key
#print axioms UorAtlas.Group.signStep
#print axioms UorAtlas.Group.signStep_spec
#print axioms UorAtlas.Group.stVec
#print axioms UorAtlas.Group.stVec_false
#print axioms UorAtlas.Group.stVec_true
#print axioms UorAtlas.Group.stabBlkComp
#print axioms UorAtlas.Group.stabChain
#print axioms UorAtlas.Group.stabChainLen
#print axioms UorAtlas.Group.stabGen_gauge
#print axioms UorAtlas.Group.stabGen_of_mem
#print axioms UorAtlas.Group.stabGt
#print axioms UorAtlas.Group.stabGt_ok
#print axioms UorAtlas.Group.stabGt_stab
#print axioms UorAtlas.Group.stabOrder
#print axioms UorAtlas.Group.stabPres
#print axioms UorAtlas.Group.stabPres_eq
#print axioms UorAtlas.Group.stabPres_iff_D29
#print axioms UorAtlas.Group.stabPres_le_D28
#print axioms UorAtlas.Group.stabPres_subgroup
#print axioms UorAtlas.Group.stabSpec
#print axioms UorAtlas.Group.stabWords
#print axioms UorAtlas.Group.stab_eq
#print axioms UorAtlas.Group.stab_letter
#print axioms UorAtlas.Group.sumK_reindex
#print axioms UorAtlas.Group.swapFacts
#print axioms UorAtlas.Group.swapPerm
#print axioms UorAtlas.Group.swapQ
#print axioms UorAtlas.Group.swapTabOK
#print axioms UorAtlas.Group.swapWord
#print axioms UorAtlas.Group.swap_gen
#print axioms UorAtlas.Group.swap_stab
#print axioms UorAtlas.Group.tabOK
#print axioms UorAtlas.Group.tabOK_bwd
#print axioms UorAtlas.Group.tabOK_evalT
#print axioms UorAtlas.Group.tabOK_fwd
#print axioms UorAtlas.Group.tabOK_genT
#print axioms UorAtlas.Group.tabOK_idT
#print axioms UorAtlas.Group.tabOK_left
#print axioms UorAtlas.Group.tabOK_mul
#print axioms UorAtlas.Group.tabOK_of
#print axioms UorAtlas.Group.tabOK_right
#print axioms UorAtlas.Group.tabOK_swap
#print axioms UorAtlas.Group.tabOK_trQ
#print axioms UorAtlas.Group.tabOf
#print axioms UorAtlas.Group.tabOf.match_1
#print axioms UorAtlas.Group.tabsOK_nextGt
#print axioms UorAtlas.Group.tperm
#print axioms UorAtlas.Group.tperm.eq_1
#print axioms UorAtlas.Group.tpermP
#print axioms UorAtlas.Group.tpermP_comp
#print axioms UorAtlas.Group.tperm_congr
#print axioms UorAtlas.Group.tperm_eq_one
#print axioms UorAtlas.Group.tperm_idT
#print axioms UorAtlas.Group.tperm_invFun
#print axioms UorAtlas.Group.tperm_mul
#print axioms UorAtlas.Group.tperm_swap
#print axioms UorAtlas.Group.tperm_toFun
#print axioms UorAtlas.Group.trFind
#print axioms UorAtlas.Group.trFind_key
#print axioms UorAtlas.Group.trL0
#print axioms UorAtlas.Group.trL1
#print axioms UorAtlas.Group.trL2
#print axioms UorAtlas.Group.trL3
#print axioms UorAtlas.Group.trL4
#print axioms UorAtlas.Group.trL5
#print axioms UorAtlas.Group.trL6
#print axioms UorAtlas.Group.trP_gen
#print axioms UorAtlas.Group.trQ_of_cosAt
#print axioms UorAtlas.Group.trQ_of_mem
#print axioms UorAtlas.Group.triB
#print axioms UorAtlas.Group.triB_eq
#print axioms UorAtlas.Group.triB_image
#print axioms UorAtlas.Group.triK
#print axioms UorAtlas.Group.triK_inv
#print axioms UorAtlas.Group.vecEq8
#print axioms UorAtlas.Group.vecEq8_eq
#print axioms UorAtlas.Group.wlin_matWord
#print axioms UorAtlas.LexLeanInternal.decl1010
#print axioms UorAtlas.LexLeanInternal.decl1025
#print axioms UorAtlas.LexLeanInternal.decl1030
#print axioms UorAtlas.LexLeanInternal.decl1054
#print axioms UorAtlas.LexLeanInternal.decl1056
#print axioms UorAtlas.LexLeanInternal.decl1059
#print axioms UorAtlas.LexLeanInternal.decl1068
#print axioms UorAtlas.LexLeanInternal.decl1070
#print axioms UorAtlas.LexLeanInternal.decl1072
#print axioms UorAtlas.LexLeanInternal.decl1079
#print axioms UorAtlas.LexLeanInternal.decl1088
#print axioms UorAtlas.LexLeanInternal.decl1108
#print axioms UorAtlas.LexLeanInternal.decl1109
#print axioms UorAtlas.LexLeanInternal.decl1127
#print axioms UorAtlas.LexLeanInternal.decl1130
#print axioms UorAtlas.LexLeanInternal.decl1131
#print axioms UorAtlas.LexLeanInternal.decl1147
#print axioms UorAtlas.LexLeanInternal.decl1152
#print axioms UorAtlas.LexLeanInternal.decl1155
#print axioms UorAtlas.LexLeanInternal.decl1166
#print axioms UorAtlas.LexLeanInternal.decl1190
#print axioms UorAtlas.LexLeanInternal.decl1197
#print axioms UorAtlas.LexLeanInternal.decl1199
#print axioms UorAtlas.LexLeanInternal.decl1206
#print axioms UorAtlas.LexLeanInternal.decl1219
#print axioms UorAtlas.LexLeanInternal.decl1220
#print axioms UorAtlas.LexLeanInternal.decl1225
#print axioms UorAtlas.LexLeanInternal.decl1238
#print axioms UorAtlas.LexLeanInternal.decl125
#print axioms UorAtlas.LexLeanInternal.decl1265
#print axioms UorAtlas.LexLeanInternal.decl1269
#print axioms UorAtlas.LexLeanInternal.decl1270
#print axioms UorAtlas.LexLeanInternal.decl1274
#print axioms UorAtlas.LexLeanInternal.decl1298
#print axioms UorAtlas.LexLeanInternal.decl13
#print axioms UorAtlas.LexLeanInternal.decl1313
#print axioms UorAtlas.LexLeanInternal.decl1319
#print axioms UorAtlas.LexLeanInternal.decl1322
#print axioms UorAtlas.LexLeanInternal.decl1331
#print axioms UorAtlas.LexLeanInternal.decl1351
#print axioms UorAtlas.LexLeanInternal.decl1357
#print axioms UorAtlas.LexLeanInternal.decl1360
#print axioms UorAtlas.LexLeanInternal.decl1361
#print axioms UorAtlas.LexLeanInternal.decl1373
#print axioms UorAtlas.LexLeanInternal.decl1380
#print axioms UorAtlas.LexLeanInternal.decl1390
#print axioms UorAtlas.LexLeanInternal.decl1393
#print axioms UorAtlas.LexLeanInternal.decl1411
#print axioms UorAtlas.LexLeanInternal.decl1421
#print axioms UorAtlas.LexLeanInternal.decl1427
#print axioms UorAtlas.LexLeanInternal.decl1432
#print axioms UorAtlas.LexLeanInternal.decl1447
#print axioms UorAtlas.LexLeanInternal.decl1480
#print axioms UorAtlas.LexLeanInternal.decl1481
#print axioms UorAtlas.LexLeanInternal.decl1496
#print axioms UorAtlas.LexLeanInternal.decl1498
#print axioms UorAtlas.LexLeanInternal.decl1504
#print axioms UorAtlas.LexLeanInternal.decl1506
#print axioms UorAtlas.LexLeanInternal.decl1507
#print axioms UorAtlas.LexLeanInternal.decl1517
#print axioms UorAtlas.LexLeanInternal.decl1537
#print axioms UorAtlas.LexLeanInternal.decl159
#print axioms UorAtlas.LexLeanInternal.decl1600
#print axioms UorAtlas.LexLeanInternal.decl1602
#print axioms UorAtlas.LexLeanInternal.decl1614
#print axioms UorAtlas.LexLeanInternal.decl1618
#print axioms UorAtlas.LexLeanInternal.decl1621
#print axioms UorAtlas.LexLeanInternal.decl1644
#print axioms UorAtlas.LexLeanInternal.decl1648
#print axioms UorAtlas.LexLeanInternal.decl165
#print axioms UorAtlas.LexLeanInternal.decl1652
#print axioms UorAtlas.LexLeanInternal.decl1653
#print axioms UorAtlas.LexLeanInternal.decl1655
#print axioms UorAtlas.LexLeanInternal.decl1677
#print axioms UorAtlas.LexLeanInternal.decl1682
#print axioms UorAtlas.LexLeanInternal.decl1700
#print axioms UorAtlas.LexLeanInternal.decl1706
#print axioms UorAtlas.LexLeanInternal.decl172
#print axioms UorAtlas.LexLeanInternal.decl186
#print axioms UorAtlas.LexLeanInternal.decl19
#print axioms UorAtlas.LexLeanInternal.decl201
#print axioms UorAtlas.LexLeanInternal.decl218
#print axioms UorAtlas.LexLeanInternal.decl25
#print axioms UorAtlas.LexLeanInternal.decl257
#print axioms UorAtlas.LexLeanInternal.decl259
#print axioms UorAtlas.LexLeanInternal.decl262
#print axioms UorAtlas.LexLeanInternal.decl265
#print axioms UorAtlas.LexLeanInternal.decl270
#print axioms UorAtlas.LexLeanInternal.decl271
#print axioms UorAtlas.LexLeanInternal.decl272
#print axioms UorAtlas.LexLeanInternal.decl273
#print axioms UorAtlas.LexLeanInternal.decl308
#print axioms UorAtlas.LexLeanInternal.decl313
#print axioms UorAtlas.LexLeanInternal.decl319
#print axioms UorAtlas.LexLeanInternal.decl323
#print axioms UorAtlas.LexLeanInternal.decl338
#print axioms UorAtlas.LexLeanInternal.decl349
#print axioms UorAtlas.LexLeanInternal.decl36
#print axioms UorAtlas.LexLeanInternal.decl364
#print axioms UorAtlas.LexLeanInternal.decl368
#print axioms UorAtlas.LexLeanInternal.decl378
#print axioms UorAtlas.LexLeanInternal.decl379
#print axioms UorAtlas.LexLeanInternal.decl386
#print axioms UorAtlas.LexLeanInternal.decl394
#print axioms UorAtlas.LexLeanInternal.decl409
#print axioms UorAtlas.LexLeanInternal.decl416
#print axioms UorAtlas.LexLeanInternal.decl423
#print axioms UorAtlas.LexLeanInternal.decl43
#print axioms UorAtlas.LexLeanInternal.decl479
#print axioms UorAtlas.LexLeanInternal.decl483
#print axioms UorAtlas.LexLeanInternal.decl49
#print axioms UorAtlas.LexLeanInternal.decl494
#print axioms UorAtlas.LexLeanInternal.decl50
#print axioms UorAtlas.LexLeanInternal.decl508
#print axioms UorAtlas.LexLeanInternal.decl518
#print axioms UorAtlas.LexLeanInternal.decl521
#print axioms UorAtlas.LexLeanInternal.decl525
#print axioms UorAtlas.LexLeanInternal.decl559
#print axioms UorAtlas.LexLeanInternal.decl569
#print axioms UorAtlas.LexLeanInternal.decl570
#print axioms UorAtlas.LexLeanInternal.decl573
#print axioms UorAtlas.LexLeanInternal.decl576
#print axioms UorAtlas.LexLeanInternal.decl579
#print axioms UorAtlas.LexLeanInternal.decl586
#print axioms UorAtlas.LexLeanInternal.decl597
#print axioms UorAtlas.LexLeanInternal.decl601
#print axioms UorAtlas.LexLeanInternal.decl619
#print axioms UorAtlas.LexLeanInternal.decl635
#print axioms UorAtlas.LexLeanInternal.decl646
#print axioms UorAtlas.LexLeanInternal.decl647
#print axioms UorAtlas.LexLeanInternal.decl666
#print axioms UorAtlas.LexLeanInternal.decl694
#print axioms UorAtlas.LexLeanInternal.decl72
#print axioms UorAtlas.LexLeanInternal.decl727
#print axioms UorAtlas.LexLeanInternal.decl73
#print axioms UorAtlas.LexLeanInternal.decl735
#print axioms UorAtlas.LexLeanInternal.decl748
#print axioms UorAtlas.LexLeanInternal.decl758
#print axioms UorAtlas.LexLeanInternal.decl77
#print axioms UorAtlas.LexLeanInternal.decl777
#print axioms UorAtlas.LexLeanInternal.decl783
#print axioms UorAtlas.LexLeanInternal.decl792
#print axioms UorAtlas.LexLeanInternal.decl794
#print axioms UorAtlas.LexLeanInternal.decl798
#print axioms UorAtlas.LexLeanInternal.decl800
#print axioms UorAtlas.LexLeanInternal.decl827
#print axioms UorAtlas.LexLeanInternal.decl855
#print axioms UorAtlas.LexLeanInternal.decl867
#print axioms UorAtlas.LexLeanInternal.decl900
#print axioms UorAtlas.LexLeanInternal.decl918
#print axioms UorAtlas.LexLeanInternal.decl934
#print axioms UorAtlas.LexLeanInternal.decl948
#print axioms UorAtlas.LexLeanInternal.decl950
#print axioms UorAtlas.LexLeanInternal.decl958
#print axioms UorAtlas.LexLeanInternal.decl959
#print axioms UorAtlas.LexLeanInternal.decl98
#print axioms UorAtlas.LexLeanInternal.decl986
#print axioms UorAtlas.LexLeanInternal.decl988
#print axioms UorAtlas.LexLeanInternal.decl991
