module
import LexLeanExample.Places
#print axioms UorAtlas.LexLeanInternal.decl0
#print axioms UorAtlas.LexLeanInternal.decl1009
#print axioms UorAtlas.LexLeanInternal.decl1013
#print axioms UorAtlas.LexLeanInternal.decl1047
#print axioms UorAtlas.LexLeanInternal.decl1048
#print axioms UorAtlas.LexLeanInternal.decl1053
#print axioms UorAtlas.LexLeanInternal.decl1055
#print axioms UorAtlas.LexLeanInternal.decl106
#print axioms UorAtlas.LexLeanInternal.decl107
#print axioms UorAtlas.LexLeanInternal.decl1074
#print axioms UorAtlas.LexLeanInternal.decl1080
#print axioms UorAtlas.LexLeanInternal.decl1110
#print axioms UorAtlas.LexLeanInternal.decl1113
#print axioms UorAtlas.LexLeanInternal.decl1139
#print axioms UorAtlas.LexLeanInternal.decl1150
#print axioms UorAtlas.LexLeanInternal.decl1179
#print axioms UorAtlas.LexLeanInternal.decl1186
#print axioms UorAtlas.LexLeanInternal.decl1231
#print axioms UorAtlas.LexLeanInternal.decl1233
#print axioms UorAtlas.LexLeanInternal.decl1255
#print axioms UorAtlas.LexLeanInternal.decl1260
#print axioms UorAtlas.LexLeanInternal.decl1271
#print axioms UorAtlas.LexLeanInternal.decl1272
#print axioms UorAtlas.LexLeanInternal.decl1287
#print axioms UorAtlas.LexLeanInternal.decl1297
#print axioms UorAtlas.LexLeanInternal.decl1308
#print axioms UorAtlas.LexLeanInternal.decl1315
#print axioms UorAtlas.LexLeanInternal.decl133
#print axioms UorAtlas.LexLeanInternal.decl1338
#print axioms UorAtlas.LexLeanInternal.decl1339
#print axioms UorAtlas.LexLeanInternal.decl1341
#print axioms UorAtlas.LexLeanInternal.decl1350
#print axioms UorAtlas.LexLeanInternal.decl1363
#print axioms UorAtlas.LexLeanInternal.decl139
#print axioms UorAtlas.LexLeanInternal.decl1398
#print axioms UorAtlas.LexLeanInternal.decl1425
#print axioms UorAtlas.LexLeanInternal.decl1444
#print axioms UorAtlas.LexLeanInternal.decl1472
#print axioms UorAtlas.LexLeanInternal.decl1476
#print axioms UorAtlas.LexLeanInternal.decl1482
#print axioms UorAtlas.LexLeanInternal.decl1484
#print axioms UorAtlas.LexLeanInternal.decl1488
#print axioms UorAtlas.LexLeanInternal.decl1514
#print axioms UorAtlas.LexLeanInternal.decl1532
#print axioms UorAtlas.LexLeanInternal.decl1535
#print axioms UorAtlas.LexLeanInternal.decl1541
#print axioms UorAtlas.LexLeanInternal.decl1556
#print axioms UorAtlas.LexLeanInternal.decl1593
#print axioms UorAtlas.LexLeanInternal.decl1599
#print axioms UorAtlas.LexLeanInternal.decl1623
#print axioms UorAtlas.LexLeanInternal.decl1647
#print axioms UorAtlas.LexLeanInternal.decl1650
#print axioms UorAtlas.LexLeanInternal.decl1689
#print axioms UorAtlas.LexLeanInternal.decl1698
#print axioms UorAtlas.LexLeanInternal.decl176
#print axioms UorAtlas.LexLeanInternal.decl18
#print axioms UorAtlas.LexLeanInternal.decl193
#print axioms UorAtlas.LexLeanInternal.decl194
#print axioms UorAtlas.LexLeanInternal.decl2
#print axioms UorAtlas.LexLeanInternal.decl204
#print axioms UorAtlas.LexLeanInternal.decl21
#print axioms UorAtlas.LexLeanInternal.decl212
#print axioms UorAtlas.LexLeanInternal.decl231
#print axioms UorAtlas.LexLeanInternal.decl237
#print axioms UorAtlas.LexLeanInternal.decl239
#print axioms UorAtlas.LexLeanInternal.decl275
#print axioms UorAtlas.LexLeanInternal.decl282
#print axioms UorAtlas.LexLeanInternal.decl287
#print axioms UorAtlas.LexLeanInternal.decl299
#print axioms UorAtlas.LexLeanInternal.decl301
#print axioms UorAtlas.LexLeanInternal.decl310
#print axioms UorAtlas.LexLeanInternal.decl331
#print axioms UorAtlas.LexLeanInternal.decl333
#print axioms UorAtlas.LexLeanInternal.decl339
#print axioms UorAtlas.LexLeanInternal.decl355
#print axioms UorAtlas.LexLeanInternal.decl37
#print axioms UorAtlas.LexLeanInternal.decl398
#print axioms UorAtlas.LexLeanInternal.decl403
#print axioms UorAtlas.LexLeanInternal.decl406
#print axioms UorAtlas.LexLeanInternal.decl415
#print axioms UorAtlas.LexLeanInternal.decl429
#print axioms UorAtlas.LexLeanInternal.decl432
#print axioms UorAtlas.LexLeanInternal.decl433
#print axioms UorAtlas.LexLeanInternal.decl434
#print axioms UorAtlas.LexLeanInternal.decl436
#print axioms UorAtlas.LexLeanInternal.decl447
#print axioms UorAtlas.LexLeanInternal.decl46
#print axioms UorAtlas.LexLeanInternal.decl461
#print axioms UorAtlas.LexLeanInternal.decl482
#print axioms UorAtlas.LexLeanInternal.decl533
#print axioms UorAtlas.LexLeanInternal.decl541
#print axioms UorAtlas.LexLeanInternal.decl548
#print axioms UorAtlas.LexLeanInternal.decl556
#print axioms UorAtlas.LexLeanInternal.decl57
#print axioms UorAtlas.LexLeanInternal.decl577
#print axioms UorAtlas.LexLeanInternal.decl629
#print axioms UorAtlas.LexLeanInternal.decl638
#print axioms UorAtlas.LexLeanInternal.decl66
#print axioms UorAtlas.LexLeanInternal.decl686
#print axioms UorAtlas.LexLeanInternal.decl687
#print axioms UorAtlas.LexLeanInternal.decl690
#print axioms UorAtlas.LexLeanInternal.decl693
#print axioms UorAtlas.LexLeanInternal.decl695
#print axioms UorAtlas.LexLeanInternal.decl722
#print axioms UorAtlas.LexLeanInternal.decl725
#print axioms UorAtlas.LexLeanInternal.decl738
#print axioms UorAtlas.LexLeanInternal.decl754
#print axioms UorAtlas.LexLeanInternal.decl757
#print axioms UorAtlas.LexLeanInternal.decl781
#print axioms UorAtlas.LexLeanInternal.decl803
#print axioms UorAtlas.LexLeanInternal.decl831
#print axioms UorAtlas.LexLeanInternal.decl844
#print axioms UorAtlas.LexLeanInternal.decl847
#print axioms UorAtlas.LexLeanInternal.decl885
#print axioms UorAtlas.LexLeanInternal.decl898
#print axioms UorAtlas.LexLeanInternal.decl906
#print axioms UorAtlas.LexLeanInternal.decl938
#print axioms UorAtlas.LexLeanInternal.decl94
#print axioms UorAtlas.LexLeanInternal.decl943
#print axioms UorAtlas.LexLeanInternal.decl955
#print axioms UorAtlas.LexLeanInternal.decl964
#print axioms UorAtlas.LexLeanInternal.decl967
#print axioms UorAtlas.LexLeanInternal.decl968
#print axioms UorAtlas.LexLeanInternal.decl982
#print axioms UorAtlas.LexLeanInternal.decl987
#print axioms UorAtlas.LexLeanInternal.decl994
#print axioms UorAtlas.Places.AutGamma
#print axioms UorAtlas.Places.AutGen
#print axioms UorAtlas.Places.AutGen.below
#print axioms UorAtlas.Places.AutGen.below.casesOn
#print axioms UorAtlas.Places.AutGen.below.gen
#print axioms UorAtlas.Places.AutGen.below.mul
#print axioms UorAtlas.Places.AutGen.below.one
#print axioms UorAtlas.Places.AutGen.below.rec
#print axioms UorAtlas.Places.AutGen.brecOn
#print axioms UorAtlas.Places.AutGen.casesOn
#print axioms UorAtlas.Places.AutGen.gen
#print axioms UorAtlas.Places.AutGen.mul
#print axioms UorAtlas.Places.AutGen.one
#print axioms UorAtlas.Places.AutGen.rec
#print axioms UorAtlas.Places.AutGen.recOn
#print axioms UorAtlas.Places.D31
#print axioms UorAtlas.Places.D32
#print axioms UorAtlas.Places.D33
#print axioms UorAtlas.Places.D34
#print axioms UorAtlas.Places.D35
#print axioms UorAtlas.Places.D35_qOf
#print axioms UorAtlas.Places.D35a
#print axioms UorAtlas.Places.D36
#print axioms UorAtlas.Places.D36_finite
#print axioms UorAtlas.Places.D36_infty
#print axioms UorAtlas.Places.D37
#print axioms UorAtlas.Places.D38
#print axioms UorAtlas.Places.D38.add_comp
#print axioms UorAtlas.Places.D38.ae
#print axioms UorAtlas.Places.D38.casesOn
#print axioms UorAtlas.Places.D38.comp
#print axioms UorAtlas.Places.D38.ctorIdx
#print axioms UorAtlas.Places.D38.ext
#print axioms UorAtlas.Places.D38.mk
#print axioms UorAtlas.Places.D38.mk.inj
#print axioms UorAtlas.Places.D38.mk.injEq
#print axioms UorAtlas.Places.D38.mk.noConfusion
#print axioms UorAtlas.Places.D38.mk.sizeOf_spec
#print axioms UorAtlas.Places.D38.neg_comp
#print axioms UorAtlas.Places.D38.noConfusion
#print axioms UorAtlas.Places.D38.noConfusionType
#print axioms UorAtlas.Places.D38.rec
#print axioms UorAtlas.Places.D38.recOn
#print axioms UorAtlas.Places.D39
#print axioms UorAtlas.Places.D39_comp
#print axioms UorAtlas.Places.D40
#print axioms UorAtlas.Places.D41
#print axioms UorAtlas.Places.D42
#print axioms UorAtlas.Places.D42_aut
#print axioms UorAtlas.Places.D42_comp_inv
#print axioms UorAtlas.Places.D42_edge
#print axioms UorAtlas.Places.D42_mul
#print axioms UorAtlas.Places.D42_one
#print axioms UorAtlas.Places.D42_reflMat
#print axioms UorAtlas.Places.D42_spec
#print axioms UorAtlas.Places.D43
#print axioms UorAtlas.Places.D44
#print axioms UorAtlas.Places.D45
#print axioms UorAtlas.Places.D46
#print axioms UorAtlas.Places.D47
#print axioms UorAtlas.Places.D48
#print axioms UorAtlas.Places.D49
#print axioms UorAtlas.Places.D49a
#print axioms UorAtlas.Places.D49b
#print axioms UorAtlas.Places.D50
#print axioms UorAtlas.Places.D51
#print axioms UorAtlas.Places.D51a
#print axioms UorAtlas.Places.FrameTransitive
#print axioms UorAtlas.Places.FullSystem
#print axioms UorAtlas.Places.FullSystem.arch
#print axioms UorAtlas.Places.FullSystem.at_
#print axioms UorAtlas.Places.FullSystem.at_.match_1
#print axioms UorAtlas.Places.FullSystem.casesOn
#print axioms UorAtlas.Places.FullSystem.ctorIdx
#print axioms UorAtlas.Places.FullSystem.fin_
#print axioms UorAtlas.Places.FullSystem.mk
#print axioms UorAtlas.Places.FullSystem.mk.inj
#print axioms UorAtlas.Places.FullSystem.mk.injEq
#print axioms UorAtlas.Places.FullSystem.mk.noConfusion
#print axioms UorAtlas.Places.FullSystem.mk.sizeOf_spec
#print axioms UorAtlas.Places.FullSystem.noConfusion
#print axioms UorAtlas.Places.FullSystem.noConfusionType
#print axioms UorAtlas.Places.FullSystem.rec
#print axioms UorAtlas.Places.FullSystem.recOn
#print axioms UorAtlas.Places.Gauge
#print axioms UorAtlas.Places.IsPrime.dvd_mul
#print axioms UorAtlas.Places.Lift
#print axioms UorAtlas.Places.LocAut
#print axioms UorAtlas.Places.LocAutRel
#print axioms UorAtlas.Places.MapsOnto
#print axioms UorAtlas.Places.OrthLoc
#print axioms UorAtlas.Places.PLocAut
#print axioms UorAtlas.Places.Pl
#print axioms UorAtlas.Places.Place
#print axioms UorAtlas.Places.Place.Amb
#print axioms UorAtlas.Places.Place.Loc
#print axioms UorAtlas.Places.Place.ambRing
#print axioms UorAtlas.Places.Place.casesOn
#print axioms UorAtlas.Places.Place.compat
#print axioms UorAtlas.Places.Place.ctorIdx
#print axioms UorAtlas.Places.Place.fromInt
#print axioms UorAtlas.Places.Place.fromIntAmb
#print axioms UorAtlas.Places.Place.fromRat
#print axioms UorAtlas.Places.Place.incl
#print axioms UorAtlas.Places.Place.integral
#print axioms UorAtlas.Places.Place.locRing
#print axioms UorAtlas.Places.Place.mk
#print axioms UorAtlas.Places.Place.mk.inj
#print axioms UorAtlas.Places.Place.mk.injEq
#print axioms UorAtlas.Places.Place.mk.noConfusion
#print axioms UorAtlas.Places.Place.mk.sizeOf_spec
#print axioms UorAtlas.Places.Place.noConfusion
#print axioms UorAtlas.Places.Place.noConfusionType
#print axioms UorAtlas.Places.Place.rec
#print axioms UorAtlas.Places.Place.recOn
#print axioms UorAtlas.Places.Place.res
#print axioms UorAtlas.Places.PlaceIx
#print axioms UorAtlas.Places.PlaceIx.arch
#print axioms UorAtlas.Places.PlaceIx.arch.elim
#print axioms UorAtlas.Places.PlaceIx.arch.sizeOf_spec
#print axioms UorAtlas.Places.PlaceIx.casesOn
#print axioms UorAtlas.Places.PlaceIx.ctorElim
#print axioms UorAtlas.Places.PlaceIx.ctorElimType
#print axioms UorAtlas.Places.PlaceIx.ctorIdx
#print axioms UorAtlas.Places.PlaceIx.finite
#print axioms UorAtlas.Places.PlaceIx.finite.elim
#print axioms UorAtlas.Places.PlaceIx.finite.inj
#print axioms UorAtlas.Places.PlaceIx.finite.injEq
#print axioms UorAtlas.Places.PlaceIx.finite.noConfusion
#print axioms UorAtlas.Places.PlaceIx.finite.sizeOf_spec
#print axioms UorAtlas.Places.PlaceIx.noConfusion
#print axioms UorAtlas.Places.PlaceIx.noConfusionType
#print axioms UorAtlas.Places.PlaceIx.rec
#print axioms UorAtlas.Places.PlaceIx.recOn
#print axioms UorAtlas.Places.PlaceSystem
#print axioms UorAtlas.Places.PlaceSystem.Nondegenerate
#print axioms UorAtlas.Places.PlaceSystem.at_
#print axioms UorAtlas.Places.PlaceSystem.casesOn
#print axioms UorAtlas.Places.PlaceSystem.ctorIdx
#print axioms UorAtlas.Places.PlaceSystem.mk
#print axioms UorAtlas.Places.PlaceSystem.mk.inj
#print axioms UorAtlas.Places.PlaceSystem.mk.injEq
#print axioms UorAtlas.Places.PlaceSystem.mk.noConfusion
#print axioms UorAtlas.Places.PlaceSystem.mk.sizeOf_spec
#print axioms UorAtlas.Places.PlaceSystem.noConfusion
#print axioms UorAtlas.Places.PlaceSystem.noConfusionType
#print axioms UorAtlas.Places.PlaceSystem.rec
#print axioms UorAtlas.Places.PlaceSystem.recOn
#print axioms UorAtlas.Places.PlaceSystem.res_eq
#print axioms UorAtlas.Places.RP1
#print axioms UorAtlas.Places.RootC
#print axioms UorAtlas.Places.T58
#print axioms UorAtlas.Places.T61
#print axioms UorAtlas.Places.T62
#print axioms UorAtlas.Places.T65
#print axioms UorAtlas.Places.T65_indep
#print axioms UorAtlas.Places.T65_span
#print axioms UorAtlas.Places.T66
#print axioms UorAtlas.Places.T67
#print axioms UorAtlas.Places.T68
#print axioms UorAtlas.Places.T69
#print axioms UorAtlas.Places.T70
#print axioms UorAtlas.Places.T71
#print axioms UorAtlas.Places.T72
#print axioms UorAtlas.Places.T72_surj
#print axioms UorAtlas.Places.T73
#print axioms UorAtlas.Places.T74
#print axioms UorAtlas.Places.T75
#print axioms UorAtlas.Places.T75_wd
#print axioms UorAtlas.Places.T76
#print axioms UorAtlas.Places.T77
#print axioms UorAtlas.Places.T77a
#print axioms UorAtlas.Places.T78
#print axioms UorAtlas.Places.T80a
#print axioms UorAtlas.Places.T80p
#print axioms UorAtlas.Places.T81
#print axioms UorAtlas.Places.T82
#print axioms UorAtlas.Places.T83
#print axioms UorAtlas.Places.Trans
#print axioms UorAtlas.Places.V65c
#print axioms UorAtlas.Places.V69
#print axioms UorAtlas.Places.V70
#print axioms UorAtlas.Places.V71
#print axioms UorAtlas.Places.V72
#print axioms UorAtlas.Places.V73
#print axioms UorAtlas.Places.V74
#print axioms UorAtlas.Places.V74_int
#print axioms UorAtlas.Places.V75
#print axioms UorAtlas.Places.WLinMem
#print axioms UorAtlas.Places.WLinMem.below
#print axioms UorAtlas.Places.WLinMem.below.casesOn
#print axioms UorAtlas.Places.WLinMem.below.gen
#print axioms UorAtlas.Places.WLinMem.below.mul
#print axioms UorAtlas.Places.WLinMem.below.one
#print axioms UorAtlas.Places.WLinMem.below.rec
#print axioms UorAtlas.Places.WLinMem.brecOn
#print axioms UorAtlas.Places.WLinMem.casesOn
#print axioms UorAtlas.Places.WLinMem.gen
#print axioms UorAtlas.Places.WLinMem.mul
#print axioms UorAtlas.Places.WLinMem.one
#print axioms UorAtlas.Places.WLinMem.rec
#print axioms UorAtlas.Places.WLinMem.recOn
#print axioms UorAtlas.Places.Zloc
#print axioms UorAtlas.Places.ZlocFromInt
#print axioms UorAtlas.Places.ZlocIncl
#print axioms UorAtlas.Places.addrAct
#print axioms UorAtlas.Places.addrAct_comp
#print axioms UorAtlas.Places.addrAct_diag
#print axioms UorAtlas.Places.addrAct_neg
#print axioms UorAtlas.Places.appendB
#print axioms UorAtlas.Places.appendB_hi
#print axioms UorAtlas.Places.appendB_lo
#print axioms UorAtlas.Places.apply_gram_simZ
#print axioms UorAtlas.Places.apply_neg_vec
#print axioms UorAtlas.Places.apply_simZ
#print axioms UorAtlas.Places.archPlace
#print axioms UorAtlas.Places.autGen_autGamma
#print axioms UorAtlas.Places.autGen_inv
#print axioms UorAtlas.Places.block_rank
#print axioms UorAtlas.Places.closed8
#print axioms UorAtlas.Places.coordOf
#print axioms UorAtlas.Places.coordOf_class
#print axioms UorAtlas.Places.coordOf_kOf
#print axioms UorAtlas.Places.den_add_dvd
#print axioms UorAtlas.Places.den_mul_dvd
#print axioms UorAtlas.Places.diag
#print axioms UorAtlas.Places.diagP
#print axioms UorAtlas.Places.diag_comp
#print axioms UorAtlas.Places.diag_injective
#print axioms UorAtlas.Places.diag_neg
#print axioms UorAtlas.Places.diag_sign
#print axioms UorAtlas.Places.dotClassCheck
#print axioms UorAtlas.Places.dot_emb
#print axioms UorAtlas.Places.dot_rep_D42
#print axioms UorAtlas.Places.dot_rep_vals
#print axioms UorAtlas.Places.dot_root_rep
#print axioms UorAtlas.Places.dualBasis
#print axioms UorAtlas.Places.dualRows
#print axioms UorAtlas.Places.dual_sim
#print axioms UorAtlas.Places.dual_sim_rat
#print axioms UorAtlas.Places.emb
#print axioms UorAtlas.Places.emb_add
#print axioms UorAtlas.Places.emb_apply
#print axioms UorAtlas.Places.emb_coordOf
#print axioms UorAtlas.Places.emb_eq_zero
#print axioms UorAtlas.Places.emb_inj
#print axioms UorAtlas.Places.emb_memL
#print axioms UorAtlas.Places.emb_neg
#print axioms UorAtlas.Places.emb_recon
#print axioms UorAtlas.Places.emb_simZ
#print axioms UorAtlas.Places.eq_neg_of_add_eq_zero
#print axioms UorAtlas.Places.fin8_cases
#print axioms UorAtlas.Places.form_apply
#print axioms UorAtlas.Places.frame_orth
#print axioms UorAtlas.Places.frame_rank
#print axioms UorAtlas.Places.fullSystem
#print axioms UorAtlas.Places.gauge_comp
#print axioms UorAtlas.Places.gauge_inv
#print axioms UorAtlas.Places.gauge_one
#print axioms UorAtlas.Places.gformZ
#print axioms UorAtlas.Places.gformZ_apply
#print axioms UorAtlas.Places.gformZ_neg_left
#print axioms UorAtlas.Places.gformZ_neg_right
#print axioms UorAtlas.Places.gformZ_simZ
#print axioms UorAtlas.Places.gformZ_simZ_simZ
#print axioms UorAtlas.Places.gramAt
#print axioms UorAtlas.Places.gramAt_InGL
#print axioms UorAtlas.Places.gramInv
#print axioms UorAtlas.Places.gramInvRows
#print axioms UorAtlas.Places.gramInv_left
#print axioms UorAtlas.Places.gramInv_right
#print axioms UorAtlas.Places.gramInv_sim
#print axioms UorAtlas.Places.gram_InGL
#print axioms UorAtlas.Places.gram_ne_zero_of_nonOrth
#print axioms UorAtlas.Places.gram_symm
#print axioms UorAtlas.Places.hiIdx
#print axioms UorAtlas.Places.homComp
#print axioms UorAtlas.Places.homId
#print axioms UorAtlas.Places.idx4
#print axioms UorAtlas.Places.idx4_val
#print axioms UorAtlas.Places.inImage_neg
#print axioms UorAtlas.Places.inSpan_append_hi
#print axioms UorAtlas.Places.inSpan_append_lo
#print axioms UorAtlas.Places.indep
#print axioms UorAtlas.Places.indep_append
#print axioms UorAtlas.Places.inner_apply_left
#print axioms UorAtlas.Places.inner_emb_right
#print axioms UorAtlas.Places.inner_qComb_orth
#print axioms UorAtlas.Places.inner_sim
#print axioms UorAtlas.Places.instAddCommGroupD38
#print axioms UorAtlas.Places.instAddCommGroupZloc
#print axioms UorAtlas.Places.instCommRingZloc
#print axioms UorAtlas.Places.integral8
#print axioms UorAtlas.Places.integralAt_add
#print axioms UorAtlas.Places.integralAt_intCast
#print axioms UorAtlas.Places.integralAt_mul
#print axioms UorAtlas.Places.integralAt_neg
#print axioms UorAtlas.Places.integralAt_one
#print axioms UorAtlas.Places.integralAt_zero
#print axioms UorAtlas.Places.integral_off
#print axioms UorAtlas.Places.isPrime_two
#print axioms UorAtlas.Places.kOf
#print axioms UorAtlas.Places.kOf_coordOf
#print axioms UorAtlas.Places.kOf_neg
#print axioms UorAtlas.Places.lift_eq_upto_sign
#print axioms UorAtlas.Places.lift_nonempty
#print axioms UorAtlas.Places.loIdx
#print axioms UorAtlas.Places.locAut_orthLoc
#print axioms UorAtlas.Places.locForm
#print axioms UorAtlas.Places.locForm_eq
#print axioms UorAtlas.Places.locGram_iso
#print axioms UorAtlas.Places.locL
#print axioms UorAtlas.Places.locL_apply
#print axioms UorAtlas.Places.locL_image
#print axioms UorAtlas.Places.locL_of_int
#print axioms UorAtlas.Places.locMat
#print axioms UorAtlas.Places.locSystem
#print axioms UorAtlas.Places.locSystem_nondegenerate
#print axioms UorAtlas.Places.localInGL
#print axioms UorAtlas.Places.map_fromIntAmb
#print axioms UorAtlas.Places.mapsOnto_comp
#print axioms UorAtlas.Places.mapsOnto_id
#print axioms UorAtlas.Places.mapsOnto_inv
#print axioms UorAtlas.Places.matMap_neg
#print axioms UorAtlas.Places.memL_neg
#print axioms UorAtlas.Places.memL_rep
#print axioms UorAtlas.Places.memL_smul
#print axioms UorAtlas.Places.memL_sum
#print axioms UorAtlas.Places.memL_zero
#print axioms UorAtlas.Places.mul_neg_id
#print axioms UorAtlas.Places.natAbs_den_mul
#print axioms UorAtlas.Places.negInj
#print axioms UorAtlas.Places.not_dvd_one
#print axioms UorAtlas.Places.nrm_cases
#print axioms UorAtlas.Places.paddr
#print axioms UorAtlas.Places.paddrAct
#print axioms UorAtlas.Places.paddrAct_mk
#print axioms UorAtlas.Places.paddr_diag_neg
#print axioms UorAtlas.Places.pair_dvd
#print axioms UorAtlas.Places.pairing
#print axioms UorAtlas.Places.pairing_spec
#print axioms UorAtlas.Places.placeAt
#print axioms UorAtlas.Places.placeSystem_ext
#print axioms UorAtlas.Places.posdef_int
#print axioms UorAtlas.Places.posdef_rat
#print axioms UorAtlas.Places.qComb_split
#print axioms UorAtlas.Places.qComb_zero
#print axioms UorAtlas.Places.qOf_inj
#print axioms UorAtlas.Places.qOf_neg
#print axioms UorAtlas.Places.quot_sign_eq
#print axioms UorAtlas.Places.ratSmul
#print axioms UorAtlas.Places.ratSmul_comp
#print axioms UorAtlas.Places.rat_eq_zero_of_mul
#print axioms UorAtlas.Places.rat_eq_zero_of_mul_four
#print axioms UorAtlas.Places.recon
#print axioms UorAtlas.Places.reflCoord
#print axioms UorAtlas.Places.reflCoord_eq
#print axioms UorAtlas.Places.reflMat
#print axioms UorAtlas.Places.reflMat_apply
#print axioms UorAtlas.Places.reflMat_gram
#print axioms UorAtlas.Places.reflMat_involution
#print axioms UorAtlas.Places.reflOn
#print axioms UorAtlas.Places.reflOn.eq_1
#print axioms UorAtlas.Places.rep_kOf
#print axioms UorAtlas.Places.rootC_apply
#print axioms UorAtlas.Places.rootC_coordOf
#print axioms UorAtlas.Places.rootC_simZ
#print axioms UorAtlas.Places.root_eq_rep
#print axioms UorAtlas.Places.sRefl
#print axioms UorAtlas.Places.sRefl_involution
#print axioms UorAtlas.Places.simCoord
#print axioms UorAtlas.Places.simCoord_comb
#print axioms UorAtlas.Places.simMemL
#print axioms UorAtlas.Places.simZ
#print axioms UorAtlas.Places.sim_dual
#print axioms UorAtlas.Places.sim_dual_rat
#print axioms UorAtlas.Places.sum8_split
#print axioms UorAtlas.Places.sumInt_exchange
#print axioms UorAtlas.Places.sumInt_ite_eq
#print axioms UorAtlas.Places.sumInt_mul_right
#print axioms UorAtlas.Places.sumInt_toRat
#print axioms UorAtlas.Places.sum_apply
#print axioms UorAtlas.Places.sum_ite_int
#print axioms UorAtlas.Places.sum_sub_int
#print axioms UorAtlas.Places.transpose_id
#print axioms UorAtlas.Places.wlin_InGL
#print axioms UorAtlas.Places.wlin_form
#print axioms UorAtlas.Places.wlin_gram
#print axioms UorAtlas.Places.wlin_inv
