module
import LexLeanExample.CensusClosure
#print axioms UorAtlas.Census.Mem4
#print axioms UorAtlas.Census.Mem4.eq_1
#print axioms UorAtlas.Census.PairValue
#print axioms UorAtlas.Census.apply_mapped_scaledId
#print axioms UorAtlas.Census.badGramCert
#print axioms UorAtlas.Census.badGramCert.eq_1
#print axioms UorAtlas.Census.badGramWitness
#print axioms UorAtlas.Census.badGramWitnessPack
#print axioms UorAtlas.Census.badGramWitnessPack.match_1
#print axioms UorAtlas.Census.badGramWitnesses
#print axioms UorAtlas.Census.badGram_impossible
#print axioms UorAtlas.Census.badVectorOK
#print axioms UorAtlas.Census.badVectorOK.eq_1
#print axioms UorAtlas.Census.basisGram
#print axioms UorAtlas.Census.basisGram.eq_1
#print axioms UorAtlas.Census.blockGramData
#print axioms UorAtlas.Census.block_eq_quadSet
#print axioms UorAtlas.Census.block_has_orthogonal_quad
#print axioms UorAtlas.Census.block_in_table
#print axioms UorAtlas.Census.block_oracle_parseval
#print axioms UorAtlas.Census.block_oracle_quad
#print axioms UorAtlas.Census.canonicalCode
#print axioms UorAtlas.Census.canonicalCode.eq_1
#print axioms UorAtlas.Census.canonicalCode_rootColumn
#print axioms UorAtlas.Census.canonicalRoot
#print axioms UorAtlas.Census.canonicalRoot.eq_1
#print axioms UorAtlas.Census.canonicalRoot_D11
#print axioms UorAtlas.Census.canonicalRoot_class
#print axioms UorAtlas.Census.canonicalRoot_code
#print axioms UorAtlas.Census.canonicalRoot_injective
#print axioms UorAtlas.Census.canonicalRoot_span
#print axioms UorAtlas.Census.canonical_dot_square
#print axioms UorAtlas.Census.censusIdx4
#print axioms UorAtlas.Census.censusIdx4_val
#print axioms UorAtlas.Census.certAdj
#print axioms UorAtlas.Census.certScale
#print axioms UorAtlas.Census.coordNum
#print axioms UorAtlas.Census.coordNum.eq_1
#print axioms UorAtlas.Census.coordNum_of_span
#print axioms UorAtlas.Census.crossNum
#print axioms UorAtlas.Census.crossNum.eq_1
#print axioms UorAtlas.Census.cross_eq_scaled_dot
#print axioms UorAtlas.Census.dot_zero_of_cross
#print axioms UorAtlas.Census.factor4
#print axioms UorAtlas.Census.findBad
#print axioms UorAtlas.Census.findBad.match_1
#print axioms UorAtlas.Census.form4
#print axioms UorAtlas.Census.form4.eq_1
#print axioms UorAtlas.Census.form4_basisGram
#print axioms UorAtlas.Census.gramCaseOK
#print axioms UorAtlas.Census.gramCaseOK.eq_1
#print axioms UorAtlas.Census.gramCode
#print axioms UorAtlas.Census.gramCode.eq_1
#print axioms UorAtlas.Census.gramCode_digit
#print axioms UorAtlas.Census.gramCode_lt
#print axioms UorAtlas.Census.gramInversePack
#print axioms UorAtlas.Census.gramInverseRows
#print axioms UorAtlas.Census.gramLeft
#print axioms UorAtlas.Census.gramLeft.eq_1
#print axioms UorAtlas.Census.gramLeft.eq_2
#print axioms UorAtlas.Census.gramLeft.eq_3
#print axioms UorAtlas.Census.gramLeft.eq_4
#print axioms UorAtlas.Census.gramLeft.eq_5
#print axioms UorAtlas.Census.gramLeft.eq_6
#print axioms UorAtlas.Census.gramLeft.match_1
#print axioms UorAtlas.Census.gramQuad
#print axioms UorAtlas.Census.gramQuadRows
#print axioms UorAtlas.Census.gramRange
#print axioms UorAtlas.Census.gramRange.eq_1
#print axioms UorAtlas.Census.gramRange_append
#print axioms UorAtlas.Census.gramRange_true
#print axioms UorAtlas.Census.gramRight
#print axioms UorAtlas.Census.gramRight.eq_1
#print axioms UorAtlas.Census.gramRight.eq_2
#print axioms UorAtlas.Census.gramRight.eq_3
#print axioms UorAtlas.Census.gramRight.eq_4
#print axioms UorAtlas.Census.gramRight.eq_5
#print axioms UorAtlas.Census.gramRight.eq_6
#print axioms UorAtlas.Census.gramSlot
#print axioms UorAtlas.Census.gramSlot.eq_1
#print axioms UorAtlas.Census.gramType
#print axioms UorAtlas.Census.gramType.eq_1
#print axioms UorAtlas.Census.gramType_gramCode
#print axioms UorAtlas.Census.inSpan4_trans
#print axioms UorAtlas.Census.inSpan_neg
#print axioms UorAtlas.Census.integral_relation_zero
#print axioms UorAtlas.Census.inverseCert
#print axioms UorAtlas.Census.inverseCert.eq_1
#print axioms UorAtlas.Census.inverseCert_left
#print axioms UorAtlas.Census.inverseCert_scale
#print axioms UorAtlas.Census.length_rootColumnList
#print axioms UorAtlas.Census.lookupPacked
#print axioms UorAtlas.Census.lookupPacked.match_1
#print axioms UorAtlas.Census.lookupQuad
#print axioms UorAtlas.Census.map_apply_intToRat
#print axioms UorAtlas.Census.mem4_crossSort
#print axioms UorAtlas.Census.mem4_exists_fin
#print axioms UorAtlas.Census.mem4_middleSort
#print axioms UorAtlas.Census.mem4_pairSort
#print axioms UorAtlas.Census.mem_of_subset_length_eq
#print axioms UorAtlas.Census.mem_quadSet_mem4
#print axioms UorAtlas.Census.mem_rootColumnList
#print axioms UorAtlas.Census.nodup_length_le_of_subset
#print axioms UorAtlas.Census.nodup_map_on
#print axioms UorAtlas.Census.nodup_toList
#print axioms UorAtlas.Census.nodup_toListFrom
#print axioms UorAtlas.Census.pairCode
#print axioms UorAtlas.Census.pairCode.eq_1
#print axioms UorAtlas.Census.pairCode_lt
#print axioms UorAtlas.Census.pairCode_ne_mid
#print axioms UorAtlas.Census.pairCode_neg
#print axioms UorAtlas.Census.pairDigit
#print axioms UorAtlas.Census.pairDigit_lt
#print axioms UorAtlas.Census.pairDigit_neg
#print axioms UorAtlas.Census.pairVal
#print axioms UorAtlas.Census.pairVal.eq_1
#print axioms UorAtlas.Census.pairVal_pairDigit
#print axioms UorAtlas.Census.pairVec
#print axioms UorAtlas.Census.pairVec_pairCode
#print axioms UorAtlas.Census.pairing
#print axioms UorAtlas.Census.pairing.eq_1
#print axioms UorAtlas.Census.pairing_five
#print axioms UorAtlas.Census.pairing_matrix
#print axioms UorAtlas.Census.pairing_ne_zero_of_span
#print axioms UorAtlas.Census.pk_complement
#print axioms UorAtlas.Census.pk_congr
#print axioms UorAtlas.Census.positiveData_of_case
#print axioms UorAtlas.Census.positiveGram
#print axioms UorAtlas.Census.positiveGramMask
#print axioms UorAtlas.Census.qComb_int_comb4
#print axioms UorAtlas.Census.quadColumn
#print axioms UorAtlas.Census.quadColumnsOK
#print axioms UorAtlas.Census.quadColumnsOK.eq_1
#print axioms UorAtlas.Census.quadSet_eq_of_mem4
#print axioms UorAtlas.Census.rootColumnCount
#print axioms UorAtlas.Census.rootColumnCount.eq_1
#print axioms UorAtlas.Census.rootColumnCount.eq_2
#print axioms UorAtlas.Census.rootColumnCount.eq_def
#print axioms UorAtlas.Census.rootColumnList
#print axioms UorAtlas.Census.rootColumnList.eq_1
#print axioms UorAtlas.Census.rootColumnList.eq_2
#print axioms UorAtlas.Census.rootColumnList.eq_def
#print axioms UorAtlas.Census.rootColumnOK
#print axioms UorAtlas.Census.rootColumnOK.eq_1
#print axioms UorAtlas.Census.rootColumn_of_span
#print axioms UorAtlas.Census.root_dot_five
#print axioms UorAtlas.Census.scaledId
#print axioms UorAtlas.Census.scaled_recon_of_span
#print axioms UorAtlas.Census.smallVec
#print axioms UorAtlas.Census.sortQuad
#print axioms UorAtlas.Census.sortQuad.eq_1
#print axioms UorAtlas.Census.sortQuad.match_1
#print axioms UorAtlas.Census.sortQuad_mem4
#print axioms UorAtlas.Census.sortQuad_strict
#print axioms UorAtlas.Census.strict4_ne
#print axioms UorAtlas.LexLeanInternal.decl1077
#print axioms UorAtlas.LexLeanInternal.decl1091
#print axioms UorAtlas.LexLeanInternal.decl1094
#print axioms UorAtlas.LexLeanInternal.decl112
#print axioms UorAtlas.LexLeanInternal.decl1161
#print axioms UorAtlas.LexLeanInternal.decl1175
#print axioms UorAtlas.LexLeanInternal.decl1180
#print axioms UorAtlas.LexLeanInternal.decl1195
#print axioms UorAtlas.LexLeanInternal.decl1201
#print axioms UorAtlas.LexLeanInternal.decl1252
#print axioms UorAtlas.LexLeanInternal.decl1257
#print axioms UorAtlas.LexLeanInternal.decl1262
#print axioms UorAtlas.LexLeanInternal.decl1268
#print axioms UorAtlas.LexLeanInternal.decl1277
#print axioms UorAtlas.LexLeanInternal.decl1280
#print axioms UorAtlas.LexLeanInternal.decl130
#print axioms UorAtlas.LexLeanInternal.decl1300
#print axioms UorAtlas.LexLeanInternal.decl1301
#print axioms UorAtlas.LexLeanInternal.decl1343
#print axioms UorAtlas.LexLeanInternal.decl1345
#print axioms UorAtlas.LexLeanInternal.decl1355
#print axioms UorAtlas.LexLeanInternal.decl1368
#print axioms UorAtlas.LexLeanInternal.decl1381
#print axioms UorAtlas.LexLeanInternal.decl1396
#print axioms UorAtlas.LexLeanInternal.decl1399
#print axioms UorAtlas.LexLeanInternal.decl1418
#print axioms UorAtlas.LexLeanInternal.decl1419
#print axioms UorAtlas.LexLeanInternal.decl1434
#print axioms UorAtlas.LexLeanInternal.decl1439
#print axioms UorAtlas.LexLeanInternal.decl1440
#print axioms UorAtlas.LexLeanInternal.decl1445
#print axioms UorAtlas.LexLeanInternal.decl145
#print axioms UorAtlas.LexLeanInternal.decl1450
#print axioms UorAtlas.LexLeanInternal.decl1451
#print axioms UorAtlas.LexLeanInternal.decl1455
#print axioms UorAtlas.LexLeanInternal.decl1458
#print axioms UorAtlas.LexLeanInternal.decl1491
#print axioms UorAtlas.LexLeanInternal.decl1509
#print axioms UorAtlas.LexLeanInternal.decl1559
#print axioms UorAtlas.LexLeanInternal.decl158
#print axioms UorAtlas.LexLeanInternal.decl1587
#print axioms UorAtlas.LexLeanInternal.decl1589
#print axioms UorAtlas.LexLeanInternal.decl1594
#print axioms UorAtlas.LexLeanInternal.decl1630
#print axioms UorAtlas.LexLeanInternal.decl164
#print axioms UorAtlas.LexLeanInternal.decl1649
#print axioms UorAtlas.LexLeanInternal.decl1651
#print axioms UorAtlas.LexLeanInternal.decl1661
#print axioms UorAtlas.LexLeanInternal.decl1662
#print axioms UorAtlas.LexLeanInternal.decl1667
#print axioms UorAtlas.LexLeanInternal.decl1683
#print axioms UorAtlas.LexLeanInternal.decl1685
#print axioms UorAtlas.LexLeanInternal.decl169
#print axioms UorAtlas.LexLeanInternal.decl170
#print axioms UorAtlas.LexLeanInternal.decl1702
#print axioms UorAtlas.LexLeanInternal.decl174
#print axioms UorAtlas.LexLeanInternal.decl208
#print axioms UorAtlas.LexLeanInternal.decl219
#print axioms UorAtlas.LexLeanInternal.decl252
#print axioms UorAtlas.LexLeanInternal.decl277
#print axioms UorAtlas.LexLeanInternal.decl302
#print axioms UorAtlas.LexLeanInternal.decl309
#print axioms UorAtlas.LexLeanInternal.decl32
#print axioms UorAtlas.LexLeanInternal.decl320
#print axioms UorAtlas.LexLeanInternal.decl343
#print axioms UorAtlas.LexLeanInternal.decl388
#print axioms UorAtlas.LexLeanInternal.decl411
#print axioms UorAtlas.LexLeanInternal.decl42
#print axioms UorAtlas.LexLeanInternal.decl435
#print axioms UorAtlas.LexLeanInternal.decl438
#print axioms UorAtlas.LexLeanInternal.decl444
#print axioms UorAtlas.LexLeanInternal.decl450
#print axioms UorAtlas.LexLeanInternal.decl451
#print axioms UorAtlas.LexLeanInternal.decl47
#print axioms UorAtlas.LexLeanInternal.decl501
#print axioms UorAtlas.LexLeanInternal.decl515
#print axioms UorAtlas.LexLeanInternal.decl529
#print axioms UorAtlas.LexLeanInternal.decl531
#print axioms UorAtlas.LexLeanInternal.decl534
#print axioms UorAtlas.LexLeanInternal.decl587
#print axioms UorAtlas.LexLeanInternal.decl599
#print axioms UorAtlas.LexLeanInternal.decl60
#print axioms UorAtlas.LexLeanInternal.decl631
#print axioms UorAtlas.LexLeanInternal.decl641
#print axioms UorAtlas.LexLeanInternal.decl650
#print axioms UorAtlas.LexLeanInternal.decl673
#print axioms UorAtlas.LexLeanInternal.decl708
#print axioms UorAtlas.LexLeanInternal.decl76
#print axioms UorAtlas.LexLeanInternal.decl762
#print axioms UorAtlas.LexLeanInternal.decl765
#print axioms UorAtlas.LexLeanInternal.decl78
#print axioms UorAtlas.LexLeanInternal.decl799
#print axioms UorAtlas.LexLeanInternal.decl813
#print axioms UorAtlas.LexLeanInternal.decl833
#print axioms UorAtlas.LexLeanInternal.decl836
#print axioms UorAtlas.LexLeanInternal.decl838
#print axioms UorAtlas.LexLeanInternal.decl840
#print axioms UorAtlas.LexLeanInternal.decl845
#print axioms UorAtlas.LexLeanInternal.decl864
#print axioms UorAtlas.LexLeanInternal.decl886
#print axioms UorAtlas.LexLeanInternal.decl897
#print axioms UorAtlas.LexLeanInternal.decl901
#print axioms UorAtlas.LexLeanInternal.decl903
#print axioms UorAtlas.LexLeanInternal.decl921
#print axioms UorAtlas.LexLeanInternal.decl935
#print axioms UorAtlas.LexLeanInternal.decl963
#print axioms UorAtlas.LexLeanInternal.decl973
#print axioms UorAtlas.LexLeanInternal.decl984
#print axioms UorAtlas.LexLeanInternal.decl999
