module
import LexLeanExample.Prelude.Perm
#print axioms UorAtlas.LexLeanInternal.decl1034
#print axioms UorAtlas.LexLeanInternal.decl1058
#print axioms UorAtlas.LexLeanInternal.decl1069
#print axioms UorAtlas.LexLeanInternal.decl1086
#print axioms UorAtlas.LexLeanInternal.decl1104
#print axioms UorAtlas.LexLeanInternal.decl1191
#print axioms UorAtlas.LexLeanInternal.decl122
#print axioms UorAtlas.LexLeanInternal.decl1239
#print axioms UorAtlas.LexLeanInternal.decl126
#print axioms UorAtlas.LexLeanInternal.decl1283
#print axioms UorAtlas.LexLeanInternal.decl1334
#print axioms UorAtlas.LexLeanInternal.decl1387
#print axioms UorAtlas.LexLeanInternal.decl141
#print axioms UorAtlas.LexLeanInternal.decl1430
#print axioms UorAtlas.LexLeanInternal.decl1436
#print axioms UorAtlas.LexLeanInternal.decl1462
#print axioms UorAtlas.LexLeanInternal.decl1466
#print axioms UorAtlas.LexLeanInternal.decl1529
#print axioms UorAtlas.LexLeanInternal.decl1572
#print axioms UorAtlas.LexLeanInternal.decl163
#print axioms UorAtlas.LexLeanInternal.decl1674
#print axioms UorAtlas.LexLeanInternal.decl1703
#print axioms UorAtlas.LexLeanInternal.decl207
#print axioms UorAtlas.LexLeanInternal.decl253
#print axioms UorAtlas.LexLeanInternal.decl311
#print axioms UorAtlas.LexLeanInternal.decl385
#print axioms UorAtlas.LexLeanInternal.decl467
#print axioms UorAtlas.LexLeanInternal.decl532
#print axioms UorAtlas.LexLeanInternal.decl600
#print axioms UorAtlas.LexLeanInternal.decl645
#print axioms UorAtlas.LexLeanInternal.decl658
#print axioms UorAtlas.LexLeanInternal.decl744
#print axioms UorAtlas.LexLeanInternal.decl778
#print axioms UorAtlas.LexLeanInternal.decl785
#print axioms UorAtlas.LexLeanInternal.decl811
#print axioms UorAtlas.LexLeanInternal.decl848
#print axioms UorAtlas.LexLeanInternal.decl854
#print axioms UorAtlas.LexLeanInternal.decl866
#print axioms UorAtlas.LexLeanInternal.decl871
#print axioms UorAtlas.LexLeanInternal.decl889
#print axioms UorAtlas.LexLeanInternal.decl945
#print axioms UorAtlas.Prelude.ListAux.consNew
#print axioms UorAtlas.Prelude.ListAux.consNew.eq_1
#print axioms UorAtlas.Prelude.ListAux.dedup
#print axioms UorAtlas.Prelude.ListAux.dedup.eq_1
#print axioms UorAtlas.Prelude.ListAux.freshOf
#print axioms UorAtlas.Prelude.ListAux.freshOf.eq_1
#print axioms UorAtlas.Prelude.ListAux.freshOf.eq_2
#print axioms UorAtlas.Prelude.ListAux.freshOf.eq_def
#print axioms UorAtlas.Prelude.ListAux.freshOf.match_1
#print axioms UorAtlas.Prelude.ListAux.length_eq_of_mem_iff
#print axioms UorAtlas.Prelude.ListAux.length_eq_sum_fibres
#print axioms UorAtlas.Prelude.ListAux.mem_dedup
#print axioms UorAtlas.Prelude.ListAux.mem_freshOf
#print axioms UorAtlas.Prelude.ListAux.nodup_dedup
#print axioms UorAtlas.Prelude.ListAux.nodup_freshOf
#print axioms UorAtlas.Prelude.ListAux.sum_map_add
#print axioms UorAtlas.Prelude.ListAux.sum_map_const
#print axioms UorAtlas.Prelude.ListAux.sum_map_eq_zero
#print axioms UorAtlas.Prelude.ListAux.sum_map_indicator
#print axioms UorAtlas.Prelude.Perm
#print axioms UorAtlas.Prelude.Perm.ClosedUnder
#print axioms UorAtlas.Prelude.Perm.Gen
#print axioms UorAtlas.Prelude.Perm.Gen.below
#print axioms UorAtlas.Prelude.Perm.Gen.below.casesOn
#print axioms UorAtlas.Prelude.Perm.Gen.below.one
#print axioms UorAtlas.Prelude.Perm.Gen.below.rec
#print axioms UorAtlas.Prelude.Perm.Gen.below.step
#print axioms UorAtlas.Prelude.Perm.Gen.below.stepInv
#print axioms UorAtlas.Prelude.Perm.Gen.brecOn
#print axioms UorAtlas.Prelude.Perm.Gen.casesOn
#print axioms UorAtlas.Prelude.Perm.Gen.comp_mem
#print axioms UorAtlas.Prelude.Perm.Gen.inv_mem
#print axioms UorAtlas.Prelude.Perm.Gen.mem_gen
#print axioms UorAtlas.Prelude.Perm.Gen.mem_gen_inv
#print axioms UorAtlas.Prelude.Perm.Gen.one
#print axioms UorAtlas.Prelude.Perm.Gen.rec
#print axioms UorAtlas.Prelude.Perm.Gen.recOn
#print axioms UorAtlas.Prelude.Perm.Gen.step
#print axioms UorAtlas.Prelude.Perm.Gen.stepInv
#print axioms UorAtlas.Prelude.Perm.Gen.subset_of_closedUnder
#print axioms UorAtlas.Prelude.Perm.Reach
#print axioms UorAtlas.Prelude.Perm.Reach.apply_gen
#print axioms UorAtlas.Prelude.Perm.Reach.base
#print axioms UorAtlas.Prelude.Perm.Reach.below
#print axioms UorAtlas.Prelude.Perm.Reach.below.base
#print axioms UorAtlas.Prelude.Perm.Reach.below.casesOn
#print axioms UorAtlas.Prelude.Perm.Reach.below.rec
#print axioms UorAtlas.Prelude.Perm.Reach.below.step
#print axioms UorAtlas.Prelude.Perm.Reach.below.stepInv
#print axioms UorAtlas.Prelude.Perm.Reach.brecOn
#print axioms UorAtlas.Prelude.Perm.Reach.casesOn
#print axioms UorAtlas.Prelude.Perm.Reach.iff_exists_gen
#print axioms UorAtlas.Prelude.Perm.Reach.rec
#print axioms UorAtlas.Prelude.Perm.Reach.recOn
#print axioms UorAtlas.Prelude.Perm.Reach.step
#print axioms UorAtlas.Prelude.Perm.Reach.stepInv
#print axioms UorAtlas.Prelude.Perm.Subgroup
#print axioms UorAtlas.Prelude.Perm.Subgroup.carrier
#print axioms UorAtlas.Prelude.Perm.Subgroup.casesOn
#print axioms UorAtlas.Prelude.Perm.Subgroup.comp_mem
#print axioms UorAtlas.Prelude.Perm.Subgroup.countP_fibre_eq
#print axioms UorAtlas.Prelude.Perm.Subgroup.ctorIdx
#print axioms UorAtlas.Prelude.Perm.Subgroup.inv_mem
#print axioms UorAtlas.Prelude.Perm.Subgroup.length_orbitOf_eq
#print axioms UorAtlas.Prelude.Perm.Subgroup.mem_ofClosure
#print axioms UorAtlas.Prelude.Perm.Subgroup.mem_orbit
#print axioms UorAtlas.Prelude.Perm.Subgroup.mem_stabilizer
#print axioms UorAtlas.Prelude.Perm.Subgroup.mk
#print axioms UorAtlas.Prelude.Perm.Subgroup.mk.inj
#print axioms UorAtlas.Prelude.Perm.Subgroup.mk.injEq
#print axioms UorAtlas.Prelude.Perm.Subgroup.mk.noConfusion
#print axioms UorAtlas.Prelude.Perm.Subgroup.mk.sizeOf_spec
#print axioms UorAtlas.Prelude.Perm.Subgroup.noConfusion
#print axioms UorAtlas.Prelude.Perm.Subgroup.noConfusionType
#print axioms UorAtlas.Prelude.Perm.Subgroup.nodup
#print axioms UorAtlas.Prelude.Perm.Subgroup.nodup_orbit
#print axioms UorAtlas.Prelude.Perm.Subgroup.nodup_stabilizer
#print axioms UorAtlas.Prelude.Perm.Subgroup.ofClosure
#print axioms UorAtlas.Prelude.Perm.Subgroup.one_mem
#print axioms UorAtlas.Prelude.Perm.Subgroup.orbit
#print axioms UorAtlas.Prelude.Perm.Subgroup.orbit.eq_1
#print axioms UorAtlas.Prelude.Perm.Subgroup.orbit_stabilizer
#print axioms UorAtlas.Prelude.Perm.Subgroup.order
#print axioms UorAtlas.Prelude.Perm.Subgroup.order.eq_1
#print axioms UorAtlas.Prelude.Perm.Subgroup.order_eq_orbitOf_mul_stabilizer
#print axioms UorAtlas.Prelude.Perm.Subgroup.order_ofClosure
#print axioms UorAtlas.Prelude.Perm.Subgroup.rec
#print axioms UorAtlas.Prelude.Perm.Subgroup.recOn
#print axioms UorAtlas.Prelude.Perm.Subgroup.stabilizer
#print axioms UorAtlas.Prelude.Perm.Subgroup.stabilizer.eq_1
#print axioms UorAtlas.Prelude.Perm.beq
#print axioms UorAtlas.Prelude.Perm.beq.eq_1
#print axioms UorAtlas.Prelude.Perm.beq_iff
#print axioms UorAtlas.Prelude.Perm.casesOn
#print axioms UorAtlas.Prelude.Perm.closure
#print axioms UorAtlas.Prelude.Perm.closure_spec
#print axioms UorAtlas.Prelude.Perm.comp
#print axioms UorAtlas.Prelude.Perm.comp_apply
#print axioms UorAtlas.Prelude.Perm.comp_assoc
#print axioms UorAtlas.Prelude.Perm.comp_inv
#print axioms UorAtlas.Prelude.Perm.comp_left_cancel
#print axioms UorAtlas.Prelude.Perm.comp_one
#print axioms UorAtlas.Prelude.Perm.ctorIdx
#print axioms UorAtlas.Prelude.Perm.cycleThree
#print axioms UorAtlas.Prelude.Perm.ext
#print axioms UorAtlas.Prelude.Perm.images
#print axioms UorAtlas.Prelude.Perm.instDecidableEq
#print axioms UorAtlas.Prelude.Perm.inv
#print axioms UorAtlas.Prelude.Perm.invFun
#print axioms UorAtlas.Prelude.Perm.inv_apply
#print axioms UorAtlas.Prelude.Perm.inv_comp
#print axioms UorAtlas.Prelude.Perm.inv_comp_distrib
#print axioms UorAtlas.Prelude.Perm.inv_inv
#print axioms UorAtlas.Prelude.Perm.left_inv
#print axioms UorAtlas.Prelude.Perm.mem_images
#print axioms UorAtlas.Prelude.Perm.mem_products
#print axioms UorAtlas.Prelude.Perm.mk
#print axioms UorAtlas.Prelude.Perm.mk.inj
#print axioms UorAtlas.Prelude.Perm.mk.injEq
#print axioms UorAtlas.Prelude.Perm.mk.noConfusion
#print axioms UorAtlas.Prelude.Perm.mk.sizeOf_spec
#print axioms UorAtlas.Prelude.Perm.noConfusion
#print axioms UorAtlas.Prelude.Perm.noConfusionType
#print axioms UorAtlas.Prelude.Perm.one
#print axioms UorAtlas.Prelude.Perm.one_apply
#print axioms UorAtlas.Prelude.Perm.one_comp
#print axioms UorAtlas.Prelude.Perm.one_inv
#print axioms UorAtlas.Prelude.Perm.orbitOf
#print axioms UorAtlas.Prelude.Perm.orbitOf_spec
#print axioms UorAtlas.Prelude.Perm.orbitSat
#print axioms UorAtlas.Prelude.Perm.orbitSat.eq_1
#print axioms UorAtlas.Prelude.Perm.orbitSat.eq_2
#print axioms UorAtlas.Prelude.Perm.orbitSat.eq_3
#print axioms UorAtlas.Prelude.Perm.orbitSat.eq_def
#print axioms UorAtlas.Prelude.Perm.orbitSat.match_1
#print axioms UorAtlas.Prelude.Perm.orbitSat_spec
#print axioms UorAtlas.Prelude.Perm.products
#print axioms UorAtlas.Prelude.Perm.rec
#print axioms UorAtlas.Prelude.Perm.recOn
#print axioms UorAtlas.Prelude.Perm.right_inv
#print axioms UorAtlas.Prelude.Perm.saturate
#print axioms UorAtlas.Prelude.Perm.saturate.eq_1
#print axioms UorAtlas.Prelude.Perm.saturate.eq_2
#print axioms UorAtlas.Prelude.Perm.saturate.eq_3
#print axioms UorAtlas.Prelude.Perm.saturate.eq_def
#print axioms UorAtlas.Prelude.Perm.saturate.match_1
#print axioms UorAtlas.Prelude.Perm.saturate_spec
#print axioms UorAtlas.Prelude.Perm.swapThree
#print axioms UorAtlas.Prelude.Perm.symThree
#print axioms UorAtlas.Prelude.Perm.symThreeGens
#print axioms UorAtlas.Prelude.Perm.symThreeList
#print axioms UorAtlas.Prelude.Perm.symThreeOrbit
#print axioms UorAtlas.Prelude.Perm.symThree_closure
#print axioms UorAtlas.Prelude.Perm.symThree_orbitOf
#print axioms UorAtlas.Prelude.Perm.symThree_orbit_length
#print axioms UorAtlas.Prelude.Perm.symThree_orbit_stabilizer
#print axioms UorAtlas.Prelude.Perm.symThree_order
#print axioms UorAtlas.Prelude.Perm.symThree_stabilizer_length
#print axioms UorAtlas.Prelude.Perm.toFun
#print axioms UorAtlas.Prelude.Perm.toFun_injective
