module
import LexLeanExample.Roots
#print axioms UorAtlas.LexLeanInternal.decl1004
#print axioms UorAtlas.LexLeanInternal.decl1021
#print axioms UorAtlas.LexLeanInternal.decl1093
#print axioms UorAtlas.LexLeanInternal.decl1097
#print axioms UorAtlas.LexLeanInternal.decl1122
#print axioms UorAtlas.LexLeanInternal.decl1128
#print axioms UorAtlas.LexLeanInternal.decl1145
#print axioms UorAtlas.LexLeanInternal.decl117
#print axioms UorAtlas.LexLeanInternal.decl1170
#print axioms UorAtlas.LexLeanInternal.decl1174
#print axioms UorAtlas.LexLeanInternal.decl1183
#print axioms UorAtlas.LexLeanInternal.decl1194
#print axioms UorAtlas.LexLeanInternal.decl1261
#print axioms UorAtlas.LexLeanInternal.decl1292
#print axioms UorAtlas.LexLeanInternal.decl1296
#print axioms UorAtlas.LexLeanInternal.decl134
#print axioms UorAtlas.LexLeanInternal.decl1348
#print axioms UorAtlas.LexLeanInternal.decl1356
#print axioms UorAtlas.LexLeanInternal.decl1358
#print axioms UorAtlas.LexLeanInternal.decl1408
#print axioms UorAtlas.LexLeanInternal.decl1428
#print axioms UorAtlas.LexLeanInternal.decl1456
#print axioms UorAtlas.LexLeanInternal.decl1469
#print axioms UorAtlas.LexLeanInternal.decl148
#print axioms UorAtlas.LexLeanInternal.decl152
#print axioms UorAtlas.LexLeanInternal.decl1542
#print axioms UorAtlas.LexLeanInternal.decl1543
#print axioms UorAtlas.LexLeanInternal.decl1544
#print axioms UorAtlas.LexLeanInternal.decl1581
#print axioms UorAtlas.LexLeanInternal.decl16
#print axioms UorAtlas.LexLeanInternal.decl1613
#print axioms UorAtlas.LexLeanInternal.decl1616
#print axioms UorAtlas.LexLeanInternal.decl1642
#print axioms UorAtlas.LexLeanInternal.decl1669
#print axioms UorAtlas.LexLeanInternal.decl1690
#print axioms UorAtlas.LexLeanInternal.decl216
#print axioms UorAtlas.LexLeanInternal.decl234
#print axioms UorAtlas.LexLeanInternal.decl238
#print axioms UorAtlas.LexLeanInternal.decl244
#print axioms UorAtlas.LexLeanInternal.decl256
#print axioms UorAtlas.LexLeanInternal.decl324
#print axioms UorAtlas.LexLeanInternal.decl342
#print axioms UorAtlas.LexLeanInternal.decl348
#print axioms UorAtlas.LexLeanInternal.decl369
#print axioms UorAtlas.LexLeanInternal.decl38
#print axioms UorAtlas.LexLeanInternal.decl454
#print axioms UorAtlas.LexLeanInternal.decl472
#print axioms UorAtlas.LexLeanInternal.decl473
#print axioms UorAtlas.LexLeanInternal.decl477
#print axioms UorAtlas.LexLeanInternal.decl516
#print axioms UorAtlas.LexLeanInternal.decl535
#print axioms UorAtlas.LexLeanInternal.decl55
#print axioms UorAtlas.LexLeanInternal.decl560
#print axioms UorAtlas.LexLeanInternal.decl568
#print axioms UorAtlas.LexLeanInternal.decl584
#print axioms UorAtlas.LexLeanInternal.decl609
#print axioms UorAtlas.LexLeanInternal.decl649
#print axioms UorAtlas.LexLeanInternal.decl656
#print axioms UorAtlas.LexLeanInternal.decl661
#print axioms UorAtlas.LexLeanInternal.decl729
#print axioms UorAtlas.LexLeanInternal.decl730
#print axioms UorAtlas.LexLeanInternal.decl759
#print axioms UorAtlas.LexLeanInternal.decl780
#print axioms UorAtlas.LexLeanInternal.decl791
#print axioms UorAtlas.LexLeanInternal.decl8
#print axioms UorAtlas.LexLeanInternal.decl815
#print axioms UorAtlas.LexLeanInternal.decl859
#print axioms UorAtlas.LexLeanInternal.decl862
#print axioms UorAtlas.LexLeanInternal.decl865
#print axioms UorAtlas.LexLeanInternal.decl878
#print axioms UorAtlas.LexLeanInternal.decl895
#print axioms UorAtlas.LexLeanInternal.decl924
#print axioms UorAtlas.LexLeanInternal.decl931
#print axioms UorAtlas.LexLeanInternal.decl956
#print axioms UorAtlas.LexLeanInternal.decl957
#print axioms UorAtlas.LexLeanInternal.decl96
#print axioms UorAtlas.LexLeanInternal.decl975
#print axioms UorAtlas.LexLeanInternal.decl980
#print axioms UorAtlas.Roots.A
#print axioms UorAtlas.Roots.AA_apply
#print axioms UorAtlas.Roots.A_apply
#print axioms UorAtlas.Roots.A_diag
#print axioms UorAtlas.Roots.A_of_D13
#print axioms UorAtlas.Roots.A_of_not_D13
#print axioms UorAtlas.Roots.A_spec
#print axioms UorAtlas.Roots.Aint
#print axioms UorAtlas.Roots.Aint_diag
#print axioms UorAtlas.Roots.AmC
#print axioms UorAtlas.Roots.AmC_apply
#print axioms UorAtlas.Roots.AmC_mul_apply
#print axioms UorAtlas.Roots.D10
#print axioms UorAtlas.Roots.D10_iff_MemL
#print axioms UorAtlas.Roots.D11
#print axioms UorAtlas.Roots.D11_iff
#print axioms UorAtlas.Roots.D11_neg
#print axioms UorAtlas.Roots.D11_rep
#print axioms UorAtlas.Roots.D12
#print axioms UorAtlas.Roots.D12_eq_iff
#print axioms UorAtlas.Roots.D12_of_nrm
#print axioms UorAtlas.Roots.D12_rep
#print axioms UorAtlas.Roots.D13
#print axioms UorAtlas.Roots.D19a
#print axioms UorAtlas.Roots.D9
#print axioms UorAtlas.Roots.D9_iff_MemD
#print axioms UorAtlas.Roots.K
#print axioms UorAtlas.Roots.Link
#print axioms UorAtlas.Roots.Link.below
#print axioms UorAtlas.Roots.Link.below.casesOn
#print axioms UorAtlas.Roots.Link.below.rec
#print axioms UorAtlas.Roots.Link.below.refl
#print axioms UorAtlas.Roots.Link.below.tail
#print axioms UorAtlas.Roots.Link.brecOn
#print axioms UorAtlas.Roots.Link.casesOn
#print axioms UorAtlas.Roots.Link.rec
#print axioms UorAtlas.Roots.Link.recOn
#print axioms UorAtlas.Roots.Link.refl
#print axioms UorAtlas.Roots.Link.symm
#print axioms UorAtlas.Roots.Link.tail
#print axioms UorAtlas.Roots.Link.trans
#print axioms UorAtlas.Roots.NonOrth
#print axioms UorAtlas.Roots.NonOrth.instDecidable
#print axioms UorAtlas.Roots.NonOrth.symm
#print axioms UorAtlas.Roots.R240
#print axioms UorAtlas.Roots.R240.eq_1
#print axioms UorAtlas.Roots.T5
#print axioms UorAtlas.Roots.T58x
#print axioms UorAtlas.Roots.T6
#print axioms UorAtlas.Roots.T7
#print axioms UorAtlas.Roots.T8
#print axioms UorAtlas.Roots.T9
#print axioms UorAtlas.Roots.T9a
#print axioms UorAtlas.Roots.V65a
#print axioms UorAtlas.Roots.V65b
#print axioms UorAtlas.Roots.adjN
#print axioms UorAtlas.Roots.adjN_diag
#print axioms UorAtlas.Roots.adjN_le_one
#print axioms UorAtlas.Roots.adjRaw
#print axioms UorAtlas.Roots.adjRaw_comm
#print axioms UorAtlas.Roots.adjRaw_le_one
#print axioms UorAtlas.Roots.allFin
#print axioms UorAtlas.Roots.allFin.match_1
#print axioms UorAtlas.Roots.allFin_of
#print axioms UorAtlas.Roots.allFin_succ
#print axioms UorAtlas.Roots.allFin_true
#print axioms UorAtlas.Roots.allLt
#print axioms UorAtlas.Roots.allLt_succ
#print axioms UorAtlas.Roots.allLt_true
#print axioms UorAtlas.Roots.boxEven0
#print axioms UorAtlas.Roots.boxEven1
#print axioms UorAtlas.Roots.boxEven2
#print axioms UorAtlas.Roots.boxEven3
#print axioms UorAtlas.Roots.boxEven4
#print axioms UorAtlas.Roots.boxEven5
#print axioms UorAtlas.Roots.boxEven6
#print axioms UorAtlas.Roots.boxEven7
#print axioms UorAtlas.Roots.boxEven8
#print axioms UorAtlas.Roots.boxEven_all
#print axioms UorAtlas.Roots.boxOdd
#print axioms UorAtlas.Roots.chk
#print axioms UorAtlas.Roots.chk.eq_1
#print axioms UorAtlas.Roots.chkEven
#print axioms UorAtlas.Roots.chk_of_root
#print axioms UorAtlas.Roots.codeOf
#print axioms UorAtlas.Roots.common
#print axioms UorAtlas.Roots.commonN
#print axioms UorAtlas.Roots.commonN_eq
#print axioms UorAtlas.Roots.commonN_lt
#print axioms UorAtlas.Roots.common_eq
#print axioms UorAtlas.Roots.coord_bound
#print axioms UorAtlas.Roots.decEven
#print axioms UorAtlas.Roots.decOdd
#print axioms UorAtlas.Roots.deg
#print axioms UorAtlas.Roots.deg_cast
#print axioms UorAtlas.Roots.det
#print axioms UorAtlas.Roots.det.match_1
#print axioms UorAtlas.Roots.detSim
#print axioms UorAtlas.Roots.dot8
#print axioms UorAtlas.Roots.dot8_eq
#print axioms UorAtlas.Roots.dotTri
#print axioms UorAtlas.Roots.dot_rep_pos
#print axioms UorAtlas.Roots.dot_sign
#print axioms UorAtlas.Roots.exists_decEven
#print axioms UorAtlas.Roots.exists_decOdd
#print axioms UorAtlas.Roots.findCode
#print axioms UorAtlas.Roots.gram
#print axioms UorAtlas.Roots.gramCheck
#print axioms UorAtlas.Roots.gram_exact
#print axioms UorAtlas.Roots.graphComp
#print axioms UorAtlas.Roots.graphFacts
#print axioms UorAtlas.Roots.idx8
#print axioms UorAtlas.Roots.idx8_val
#print axioms UorAtlas.Roots.isD10
#print axioms UorAtlas.Roots.isD10.eq_1
#print axioms UorAtlas.Roots.isD10_iff
#print axioms UorAtlas.Roots.isD11
#print axioms UorAtlas.Roots.isD11.eq_1
#print axioms UorAtlas.Roots.isD11_iff
#print axioms UorAtlas.Roots.isD9
#print axioms UorAtlas.Roots.isD9.eq_1
#print axioms UorAtlas.Roots.isD9_iff
#print axioms UorAtlas.Roots.isum_add
#print axioms UorAtlas.Roots.isum_const
#print axioms UorAtlas.Roots.isum_ite
#print axioms UorAtlas.Roots.isum_ite'
#print axioms UorAtlas.Roots.isum_mul_right
#print axioms UorAtlas.Roots.link0
#print axioms UorAtlas.Roots.master
#print axioms UorAtlas.Roots.mid_eq_24
#print axioms UorAtlas.Roots.minor
#print axioms UorAtlas.Roots.mul_self_nonneg
#print axioms UorAtlas.Roots.nib
#print axioms UorAtlas.Roots.nrm
#print axioms UorAtlas.Roots.nrm.eq_1
#print axioms UorAtlas.Roots.nrm_eq
#print axioms UorAtlas.Roots.nrm_neg
#print axioms UorAtlas.Roots.nrm_rep
#print axioms UorAtlas.Roots.packBase
#print axioms UorAtlas.Roots.pk
#print axioms UorAtlas.Roots.pk_add
#print axioms UorAtlas.Roots.pk_digit
#print axioms UorAtlas.Roots.pk_inj
#print axioms UorAtlas.Roots.pk_lt
#print axioms UorAtlas.Roots.pk_smul
#print axioms UorAtlas.Roots.pk_succ
#print axioms UorAtlas.Roots.pk_sumN
#print axioms UorAtlas.Roots.pk_zeroFun
#print axioms UorAtlas.Roots.posRef
#print axioms UorAtlas.Roots.rep
#print axioms UorAtlas.Roots.repFind
#print axioms UorAtlas.Roots.repIsRoot
#print axioms UorAtlas.Roots.repN
#print axioms UorAtlas.Roots.repPos
#print axioms UorAtlas.Roots.repTable
#print axioms UorAtlas.Roots.repWords
#print axioms UorAtlas.Roots.rep_D12
#print axioms UorAtlas.Roots.rowPk
#print axioms UorAtlas.Roots.simRoots
#print axioms UorAtlas.Roots.simWords
#print axioms UorAtlas.Roots.sqPk
#print axioms UorAtlas.Roots.sqPk_eq
#print axioms UorAtlas.Roots.sum8
#print axioms UorAtlas.Roots.sum8_eq
#print axioms UorAtlas.Roots.sumInt8_sub_one
#print axioms UorAtlas.Roots.sumInt_negate
#print axioms UorAtlas.Roots.sumInt_nonneg
#print axioms UorAtlas.Roots.sumInt_sub_one
#print axioms UorAtlas.Roots.sumInt_term_le
#print axioms UorAtlas.Roots.sumN
#print axioms UorAtlas.Roots.sumN_front
#print axioms UorAtlas.Roots.sumN_le_of_le_one
#print axioms UorAtlas.Roots.sumN_succ
#print axioms UorAtlas.Roots.sumNat_cast
#print axioms UorAtlas.Roots.sumNat_eq_sumN
#print axioms UorAtlas.Roots.tgtPk
#print axioms UorAtlas.Roots.tgt_lt
#print axioms UorAtlas.Roots.trA
#print axioms UorAtlas.Roots.trA2
#print axioms UorAtlas.Roots.trA2_eq
#print axioms UorAtlas.Roots.trA_eq
#print axioms UorAtlas.Roots.trI
#print axioms UorAtlas.Roots.trI_eq
#print axioms UorAtlas.Roots.vneg_neg
#print axioms UorAtlas.Roots.wordAt
