module
import LexLeanExample.Prelude.Linear
#print axioms UorAtlas.LexLeanInternal.decl1000
#print axioms UorAtlas.LexLeanInternal.decl1020
#print axioms UorAtlas.LexLeanInternal.decl1229
#print axioms UorAtlas.LexLeanInternal.decl1463
#print axioms UorAtlas.LexLeanInternal.decl1494
#print axioms UorAtlas.LexLeanInternal.decl1549
#print axioms UorAtlas.LexLeanInternal.decl1552
#print axioms UorAtlas.LexLeanInternal.decl1626
#print axioms UorAtlas.LexLeanInternal.decl1714
#print axioms UorAtlas.LexLeanInternal.decl187
#print axioms UorAtlas.LexLeanInternal.decl246
#print axioms UorAtlas.LexLeanInternal.decl35
#print axioms UorAtlas.LexLeanInternal.decl365
#print axioms UorAtlas.LexLeanInternal.decl596
#print axioms UorAtlas.LexLeanInternal.decl724
#print axioms UorAtlas.LexLeanInternal.decl828
#print axioms UorAtlas.Prelude.Linear.M1
#print axioms UorAtlas.Prelude.Linear.M2
#print axioms UorAtlas.Prelude.Linear.M3
#print axioms UorAtlas.Prelude.Linear.M4
#print axioms UorAtlas.Prelude.Linear.Mat
#print axioms UorAtlas.Prelude.Linear.Mat.apply
#print axioms UorAtlas.Prelude.Linear.Mat.apply_apply
#print axioms UorAtlas.Prelude.Linear.Mat.apply_id
#print axioms UorAtlas.Prelude.Linear.Mat.apply_mul
#print axioms UorAtlas.Prelude.Linear.Mat.apply_neg_apply
#print axioms UorAtlas.Prelude.Linear.Mat.id
#print axioms UorAtlas.Prelude.Linear.Mat.id_apply
#print axioms UorAtlas.Prelude.Linear.Mat.id_mul_apply
#print axioms UorAtlas.Prelude.Linear.Mat.instDecidableEq
#print axioms UorAtlas.Prelude.Linear.Mat.map
#print axioms UorAtlas.Prelude.Linear.Mat.map_mul_apply
#print axioms UorAtlas.Prelude.Linear.Mat.mul
#print axioms UorAtlas.Prelude.Linear.Mat.mul_apply
#print axioms UorAtlas.Prelude.Linear.Mat.mul_assoc_apply
#print axioms UorAtlas.Prelude.Linear.Mat.mul_id_apply
#print axioms UorAtlas.Prelude.Linear.Mat.neg
#print axioms UorAtlas.Prelude.Linear.Mat.transpose
#print axioms UorAtlas.Prelude.Linear.Mat.transpose_mul
#print axioms UorAtlas.Prelude.Linear.Mat.transpose_transpose
#print axioms UorAtlas.Prelude.Linear.Vec
#print axioms UorAtlas.Prelude.Linear.Vec.add_apply
#print axioms UorAtlas.Prelude.Linear.Vec.inner
#print axioms UorAtlas.Prelude.Linear.Vec.inner_add_left
#print axioms UorAtlas.Prelude.Linear.Vec.inner_add_right
#print axioms UorAtlas.Prelude.Linear.Vec.inner_comm
#print axioms UorAtlas.Prelude.Linear.Vec.inner_map
#print axioms UorAtlas.Prelude.Linear.Vec.inner_neg_left
#print axioms UorAtlas.Prelude.Linear.Vec.inner_neg_right
#print axioms UorAtlas.Prelude.Linear.Vec.inner_smul_left
#print axioms UorAtlas.Prelude.Linear.Vec.inner_smul_right
#print axioms UorAtlas.Prelude.Linear.Vec.instAddCommGroup
#print axioms UorAtlas.Prelude.Linear.Vec.instDecidableEq
#print axioms UorAtlas.Prelude.Linear.Vec.map
#print axioms UorAtlas.Prelude.Linear.Vec.mul_sum
#print axioms UorAtlas.Prelude.Linear.Vec.neg_apply
#print axioms UorAtlas.Prelude.Linear.Vec.smul
#print axioms UorAtlas.Prelude.Linear.Vec.sum
#print axioms UorAtlas.Prelude.Linear.Vec.sum.match_1
#print axioms UorAtlas.Prelude.Linear.Vec.sumInt
#print axioms UorAtlas.Prelude.Linear.Vec.sumInt.match_1
#print axioms UorAtlas.Prelude.Linear.Vec.sumInt_eq_sum
#print axioms UorAtlas.Prelude.Linear.Vec.sumNat
#print axioms UorAtlas.Prelude.Linear.Vec.sumNat.match_1
#print axioms UorAtlas.Prelude.Linear.Vec.sumNat_add
#print axioms UorAtlas.Prelude.Linear.Vec.sumNat_congr
#print axioms UorAtlas.Prelude.Linear.Vec.sumNat_const
#print axioms UorAtlas.Prelude.Linear.Vec.sum_add
#print axioms UorAtlas.Prelude.Linear.Vec.sum_congr
#print axioms UorAtlas.Prelude.Linear.Vec.sum_const
#print axioms UorAtlas.Prelude.Linear.Vec.sum_exchange
#print axioms UorAtlas.Prelude.Linear.Vec.sum_ite_eq
#print axioms UorAtlas.Prelude.Linear.Vec.sum_ite_eq'
#print axioms UorAtlas.Prelude.Linear.Vec.sum_mul
#print axioms UorAtlas.Prelude.Linear.Vec.sum_neg
#print axioms UorAtlas.Prelude.Linear.Vec.sum_nil
#print axioms UorAtlas.Prelude.Linear.Vec.sum_split
#print axioms UorAtlas.Prelude.Linear.Vec.sum_succ
#print axioms UorAtlas.Prelude.Linear.Vec.sum_zero
#print axioms UorAtlas.Prelude.Linear.Vec.zero_apply
#print axioms UorAtlas.Prelude.Linear.add_add_add_comm
#print axioms UorAtlas.Prelude.Linear.add_left_comm
#print axioms UorAtlas.Prelude.Linear.add_right_cancel
#print axioms UorAtlas.Prelude.Linear.dot
#print axioms UorAtlas.Prelude.Linear.dot_add_left
#print axioms UorAtlas.Prelude.Linear.dot_add_right
#print axioms UorAtlas.Prelude.Linear.dot_comm
#print axioms UorAtlas.Prelude.Linear.dot_eq_inner
#print axioms UorAtlas.Prelude.Linear.dot_neg_left
#print axioms UorAtlas.Prelude.Linear.dot_neg_right
#print axioms UorAtlas.Prelude.Linear.dot_smul_left
#print axioms UorAtlas.Prelude.Linear.dot_smul_right
#print axioms UorAtlas.Prelude.Linear.hom_map_sum
#print axioms UorAtlas.Prelude.Linear.hom_map_zero
#print axioms UorAtlas.Prelude.Linear.neg_add
#print axioms UorAtlas.Prelude.Linear.neg_mul
#print axioms UorAtlas.Prelude.Linear.neg_zero
#print axioms UorAtlas.Prelude.Linear.nsmul
#print axioms UorAtlas.Prelude.Linear.nsmul.match_1
#print axioms UorAtlas.Prelude.Linear.right_distrib
