module
import LexLeanExample.ClosureOrbitTransport
#print axioms UorAtlas.Blocks.D46a.V.eq_1
#print axioms UorAtlas.Blocks.D46a.mk.congr_simp
#print axioms UorAtlas.Blocks.frame0.eq_1
#print axioms UorAtlas.Blocks.frame1.eq_1
#print axioms UorAtlas.Closure.ContainedBlock
#print axioms UorAtlas.Closure.HasBlockCount
#print axioms UorAtlas.Closure.HasBlockCount.image
#print axioms UorAtlas.Closure.T24
#print axioms UorAtlas.Closure.T25
#print axioms UorAtlas.Closure.T25x
#print axioms UorAtlas.Closure.T27
#print axioms UorAtlas.Closure.W0_two_frames
#print axioms UorAtlas.Closure.actP_subset
#print axioms UorAtlas.Closure.atl_mem_atlasSupports
#print axioms UorAtlas.Closure.blockIdsIn
#print axioms UorAtlas.Closure.blockIdsIn.eq_1
#print axioms UorAtlas.Closure.blockIdsIn_nodup
#print axioms UorAtlas.Closure.blockIncluded
#print axioms UorAtlas.Closure.blockIncluded.eq_1
#print axioms UorAtlas.Closure.blockIncluded_true_iff
#print axioms UorAtlas.Closure.blockSetsIn
#print axioms UorAtlas.Closure.blockSetsIn_nodup
#print axioms UorAtlas.Closure.candidate_atl
#print axioms UorAtlas.Closure.candidate_tight
#print axioms UorAtlas.Closure.frameSupport.eq_1
#print axioms UorAtlas.Closure.frameSupport_card
#print axioms UorAtlas.Closure.frameSupport_eq
#print axioms UorAtlas.Closure.mem_blockIdsIn
#print axioms UorAtlas.Closure.mem_blockSetsIn
#print axioms UorAtlas.Closure.orbit_equals_candidates
#print axioms UorAtlas.Closure.orbit_mem_atlasSupports
#print axioms UorAtlas.Closure.pairSupport.eq_1
#print axioms UorAtlas.Closure.two_frames_candidate
#print axioms UorAtlas.Closure.witness_block_count
#print axioms UorAtlas.Group.W0.eq_1
#print axioms UorAtlas.LexLeanInternal.decl1023
#print axioms UorAtlas.LexLeanInternal.decl1317
#print axioms UorAtlas.LexLeanInternal.decl1547
#print axioms UorAtlas.LexLeanInternal.decl440
#print axioms UorAtlas.LexLeanInternal.decl476
#print axioms UorAtlas.LexLeanInternal.decl917
