module
import LexLeanExample.Atlas
#print axioms UorAtlas.Blocks.D17.mk.congr_simp
#print axioms UorAtlas.Blocks.V.eq_1
#print axioms UorAtlas.Closure.BlockAutCover
#print axioms UorAtlas.Closure.D19_presentationImage
#print axioms UorAtlas.Closure.HasOrderSigned
#print axioms UorAtlas.Closure.T26
#print axioms UorAtlas.Closure.T26a
#print axioms UorAtlas.Closure.T26b
#print axioms UorAtlas.Closure.T26x
#print axioms UorAtlas.Closure.T39
#print axioms UorAtlas.Closure.T52
#print axioms UorAtlas.Closure.T53
#print axioms UorAtlas.Closure.V_canonicalPresentation
#print axioms UorAtlas.Closure.V_presentationImage
#print axioms UorAtlas.Closure.V_reindexPresentation
#print axioms UorAtlas.Closure.blockAutCover_fibres
#print axioms UorAtlas.Closure.blockAutCover_order
#print axioms UorAtlas.Closure.blockAutSign
#print axioms UorAtlas.Closure.blockAutSign_fibre
#print axioms UorAtlas.Closure.canonicalPresentation
#print axioms UorAtlas.Closure.canonicalPresentation.eq_1
#print axioms UorAtlas.Closure.codeMap4
#print axioms UorAtlas.Closure.codeMap4.eq_1
#print axioms UorAtlas.Closure.codeMap4_permCode4
#print axioms UorAtlas.Closure.codePerm4
#print axioms UorAtlas.Closure.codePerm4.eq_1
#print axioms UorAtlas.Closure.codePerm4_permCode4
#print axioms UorAtlas.Closure.conjugate_apply
#print axioms UorAtlas.Closure.disjoint_of_union_disjoint
#print axioms UorAtlas.Closure.edges_image
#print axioms UorAtlas.Closure.fixesBlock_conjugate_iff
#print axioms UorAtlas.Closure.inter_empty_comm
#print axioms UorAtlas.Closure.mem_presentationBlocks
#print axioms UorAtlas.Closure.mem_symFourList
#print axioms UorAtlas.Closure.permCode4
#print axioms UorAtlas.Closure.permCode4_lt
#print axioms UorAtlas.Closure.presentationBlocks
#print axioms UorAtlas.Closure.presentationBlocks.eq_1
#print axioms UorAtlas.Closure.presentationBlocks_length
#print axioms UorAtlas.Closure.presentationBlocks_nodup
#print axioms UorAtlas.Closure.presentationImage
#print axioms UorAtlas.Closure.presentationImage.eq_1
#print axioms UorAtlas.Closure.presentationIndex
#print axioms UorAtlas.Closure.presentationIndex.eq_1
#print axioms UorAtlas.Closure.presentationIndex_bijective
#print axioms UorAtlas.Closure.presentationIndex_spec
#print axioms UorAtlas.Closure.presentation_blkOf
#print axioms UorAtlas.Closure.presentation_blk_inj
#print axioms UorAtlas.Closure.presentation_blk_ne
#print axioms UorAtlas.Closure.presentation_block_contained
#print axioms UorAtlas.Closure.presentation_complete
#print axioms UorAtlas.Closure.presentation_fibre_24
#print axioms UorAtlas.Closure.presentation_of_atl
#print axioms UorAtlas.Closure.presentations_reindex
#print axioms UorAtlas.Closure.reindexPresentation
#print axioms UorAtlas.Closure.reindex_free
#print axioms UorAtlas.Closure.reindexedPartner
#print axioms UorAtlas.Closure.reindexedPartner.eq_1
#print axioms UorAtlas.Closure.reindexedPartner_involutive
#print axioms UorAtlas.Closure.reindexedPartner_ne
#print axioms UorAtlas.Closure.stabPres_conjugate_iff
#print axioms UorAtlas.Closure.stabPres_reindex_iff
#print axioms UorAtlas.Closure.stab_order_image
#print axioms UorAtlas.Closure.symFourList
#print axioms UorAtlas.Closure.symFourList.eq_1
#print axioms UorAtlas.Closure.symFourList_length
#print axioms UorAtlas.Closure.symFourList_nodup
#print axioms UorAtlas.Closure.union4_actPres
#print axioms UorAtlas.Closure.union4_reindex
#print axioms UorAtlas.Group.actPres.eq_1
#print axioms UorAtlas.Group.blkOf.eq_1
#print axioms UorAtlas.Group.reindex.eq_1
#print axioms UorAtlas.LexLeanInternal.decl10
#print axioms UorAtlas.LexLeanInternal.decl1120
#print axioms UorAtlas.LexLeanInternal.decl1316
#print axioms UorAtlas.LexLeanInternal.decl1417
#print axioms UorAtlas.LexLeanInternal.decl1460
#print axioms UorAtlas.LexLeanInternal.decl1553
#print axioms UorAtlas.LexLeanInternal.decl1579
#print axioms UorAtlas.LexLeanInternal.decl1615
#print axioms UorAtlas.LexLeanInternal.decl1631
#print axioms UorAtlas.LexLeanInternal.decl1680
#print axioms UorAtlas.LexLeanInternal.decl215
#print axioms UorAtlas.LexLeanInternal.decl330
#print axioms UorAtlas.LexLeanInternal.decl390
#print axioms UorAtlas.LexLeanInternal.decl391
#print axioms UorAtlas.LexLeanInternal.decl549
#print axioms UorAtlas.LexLeanInternal.decl602
#print axioms UorAtlas.LexLeanInternal.decl717
#print axioms UorAtlas.LexLeanInternal.decl719
#print axioms UorAtlas.LexLeanInternal.decl789
#print axioms UorAtlas.LexLeanInternal.decl90
#print axioms UorAtlas.LexLeanInternal.decl960
#print axioms UorAtlas.LexLeanInternal.decl989
