//! Repository gates (SPEC.md §9.2, §27).
//!
//! `cargo xtask <task>`; `just vv` runs the whole normative acceptance gate.
//! Each task enforces named rules and says which promise broke when it
//! fails.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use camino::Utf8PathBuf;

mod audit;
mod codegen;
mod spec_links;

/// A gate failure, reported with the rule it broke.
pub type Fail = Box<dyn std::error::Error>;

fn main() -> ExitCode {
    let task = std::env::args().nth(1).unwrap_or_else(|| "help".to_owned());
    let write = std::env::args().any(|argument| argument == "--write");
    let root = repo_model::repo_root();

    let result = match task.as_str() {
        "validate-model" => codegen::check_model(&root, write),
        "validate-spec-links" => spec_links::validate(&root),
        "verify-examples" => verify_examples(&root),
        "check-golden" => check_golden(&root, write),
        "check-reproducibility" => check_reproducibility(&root),
        "release-check" => match repo_model::release::check(&root) {
            Ok(()) => Ok(()),
            Err(unmet) => Err(format!(
                "RP-12: the release is refused; unmet criteria:\n  {}",
                unmet.join("\n  ")
            )
            .into()),
        },
        "validate" => codegen::check_model(&root, false).and_then(|()| spec_links::validate(&root)),
        _ => {
            eprintln!(
                "cargo xtask <task>\n\
                 \n\
                 validate-model          R1, R2, R4, R5, R6, R8: model, documents, meta-gate, audits\n\
                 validate-spec-links     RP-07: the §31 table and the register are bijective\n\
                 verify-examples         §28.6: every example formats, locks, checks, builds, verifies\n\
                 check-golden            §28.3: build outputs equal the committed oracles\n\
                 check-reproducibility   §28.4: two clean builds in distinct paths are byte-identical\n\
                 release-check           RP-12: refuse release until §30.3/§30.4 are fully satisfied\n\
                 validate                validate-model then validate-spec-links\n\
                 \n\
                 --write                 validate-model / check-golden: rewrite the generated bytes"
            );
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("gate failed: {error}");
            ExitCode::FAILURE
        }
    }
}

fn example_dirs(root: &Path) -> Result<Vec<PathBuf>, Fail> {
    let mut dirs = Vec::new();
    for entry in std::fs::read_dir(root.join("examples"))? {
        let path = entry?.path();
        if path.is_dir() {
            dirs.push(path);
        }
    }
    dirs.sort();
    if dirs.is_empty() {
        return Err(
            "EX-08: the examples directory is empty; the gate has nothing to verify".into(),
        );
    }
    Ok(dirs)
}

fn utf8(path: &Path) -> Result<Utf8PathBuf, Fail> {
    Utf8PathBuf::from_path_buf(path.to_path_buf())
        .map_err(|bad| format!("non-UTF-8 path {}", bad.display()).into())
}

fn engine_for(dir: &Path) -> Result<lexlean::Engine, Fail> {
    let config = utf8(&dir.join("lexlean.toml"))?;
    lexlean::Engine::load(&config).map_err(|error| format!("{}: {error}", dir.display()).into())
}

/// §28.6: every example directory is discovered and runs `fmt --check`,
/// `lock --check`, `check`, `build`, and `verify`.
fn verify_examples(root: &Path) -> Result<(), Fail> {
    for dir in example_dirs(root)? {
        let name = dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let engine = engine_for(&dir)?;
        engine
            .format(lexlean::FormatRequest {
                selection: lexlean::Selection::Entrypoints,
                check_only: true,
            })
            .map_err(|error| format!("{name}: fmt --check: {error}"))?;
        engine
            .lock(lexlean::LockRequest {
                check_only: true,
                allow_network: false,
            })
            .map_err(|error| format!("{name}: lock --check: {error}"))?;
        engine
            .check(lexlean::CheckRequest {
                selection: lexlean::Selection::Entrypoints,
            })
            .map_err(|error| format!("{name}: check: {error}"))?;
        engine
            .build(lexlean::BuildRequest {
                selection: lexlean::Selection::Entrypoints,
            })
            .map_err(|error| format!("{name}: build: {error}"))?;
        let verified = engine
            .verify(lexlean::VerifyRequest {
                selection: lexlean::Selection::Entrypoints,
            })
            .map_err(|error| format!("{name}: verify: {error}"))?;
        println!(
            "verify-examples: {name} verified (attestation {})",
            verified.attestation_id.to_hex()
        );
    }
    Ok(())
}

fn rendered_files(dir: &Path) -> Result<Vec<(String, Vec<u8>)>, Fail> {
    let config = utf8(&dir.join("lexlean.toml"))?;
    let project = lexlean::project::Project::load(&config)
        .map_err(|error| format!("{}: {error}", dir.display()))?;
    let (lock, packages) = lexlean::lock::read_current_lock(&project)
        .map_err(|diagnostics| format!("{}: stale lock: {diagnostics:?}", dir.display()))?;
    let checked =
        lexlean::link::check_project(&project, &lexlean::Selection::Entrypoints, &lock, packages)
            .map_err(|error| format!("{}: {error}", dir.display()))?;
    let rendered = lexlean::api::render_build(&project, &checked)
        .map_err(|error| format!("{}: {error}", dir.display()))?;
    Ok(rendered.files)
}

/// §28.3: golden outputs change only through the explicit write recipe.
fn check_golden(root: &Path, write: bool) -> Result<(), Fail> {
    for dir in example_dirs(root)? {
        let name = dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let files = rendered_files(&dir)?;
        let expected_root = dir.join("expected").join("build");
        if write {
            if expected_root.exists() {
                std::fs::remove_dir_all(&expected_root)?;
            }
            for (relative, bytes) in &files {
                let destination = expected_root.join(relative);
                if let Some(parent) = destination.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(destination, bytes)?;
            }
            println!(
                "check-golden: wrote {} oracle files for {name}",
                files.len()
            );
            continue;
        }
        for (relative, bytes) in &files {
            let oracle = expected_root.join(relative);
            let committed = std::fs::read(&oracle).map_err(|error| {
                format!("R10: {name}: missing oracle {relative}: {error}; run `just golden-write`")
            })?;
            if committed != *bytes {
                return Err(format!(
                    "R10: {name}: {relative} differs from its committed oracle; a semantic change needs `just golden-write` and review (§28.3)"
                )
                .into());
            }
        }
        // Every committed oracle corresponds to a generated file.
        for entry in walkdir::WalkDir::new(&expected_root).into_iter().flatten() {
            if !entry.file_type().is_file() {
                continue;
            }
            let relative = entry
                .path()
                .strip_prefix(&expected_root)
                .unwrap_or(entry.path())
                .to_string_lossy()
                .replace('\\', "/");
            if !files.iter().any(|(path, _)| *path == relative) {
                return Err(format!(
                    "R10: {name}: oracle {relative} matches no generated artifact"
                )
                .into());
            }
        }
        println!(
            "check-golden: {name}: {} artifacts equal their oracles (R10)",
            files.len()
        );
    }
    Ok(())
}

fn copy_example(from: &Path, to: &Path) -> Result<(), Fail> {
    for entry in walkdir::WalkDir::new(from).into_iter().flatten() {
        let relative = entry.path().strip_prefix(from).unwrap_or(entry.path());
        let text = relative.to_string_lossy();
        if text.starts_with(".lexlean") || text.starts_with("expected") || text.is_empty() {
            continue;
        }
        let destination = to.join(relative);
        if entry.file_type().is_dir() {
            std::fs::create_dir_all(&destination)?;
        } else if entry.file_type().is_file() {
            if let Some(parent) = destination.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::copy(entry.path(), &destination)?;
        }
    }
    Ok(())
}

/// §28.4, AR-13: two clean builds in distinct absolute directories are
/// byte-identical for every platform-independent artifact.
fn check_reproducibility(root: &Path) -> Result<(), Fail> {
    for dir in example_dirs(root)? {
        let name = dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let first = tempfile::Builder::new()
            .prefix("lexlean-repro-a-")
            .tempdir()?;
        let second = tempfile::Builder::new()
            .prefix("lexlean-repro-b-")
            .tempdir()?;
        copy_example(&dir, first.path())?;
        copy_example(&dir, second.path())?;
        let files_a = rendered_files(first.path())?;
        let files_b = rendered_files(second.path())?;
        if files_a.len() != files_b.len() {
            return Err(format!("R10: {name}: the two builds emit different file sets").into());
        }
        for ((path_a, bytes_a), (path_b, bytes_b)) in files_a.iter().zip(&files_b) {
            if path_a != path_b || bytes_a != bytes_b {
                return Err(format!(
                    "R10: {name}: {path_a} differs between two clean builds in distinct directories (AR-13)"
                )
                .into());
            }
        }
        println!(
            "check-reproducibility: {name}: {} artifacts byte-identical across directories (R10)",
            files_a.len()
        );
    }
    Ok(())
}
