//! Repository gates (SPEC.md §9.2, §27).
//!
//! `cargo xtask <task>`; `just vv` runs the whole normative acceptance gate.
//! Each task enforces named rules and says which promise broke when it
//! fails.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use camino::Utf8PathBuf;

mod audit;
mod codegen;
mod spec_links;

/// A gate failure, reported with the rule it broke.
pub type Fail = Box<dyn std::error::Error>;

fn main() -> ExitCode {
    let task = std::env::args().nth(1).unwrap_or_else(|| "help".to_owned());
    let write = std::env::args().any(|argument| argument == "--write");
    let root = repo_model::repo_root();

    let result = match task.as_str() {
        "validate-model" => codegen::check_model(&root, write),
        "validate-spec-links" => spec_links::validate(&root),
        "verify-examples" => verify_examples(&root, write),
        "check-golden" => check_golden(&root, write),
        "check-reproducibility" => check_reproducibility(&root),
        "check-fixtures" => check_fixtures(&root, write),
        "release-check" => release_check(&root),
        "validate" => codegen::check_model(&root, false).and_then(|()| spec_links::validate(&root)),
        _ => {
            eprintln!(
                "cargo xtask <task>\n\
                 \n\
                 validate-model          R1, R2, R4, R5, R6, R8: model, documents, meta-gate, audits\n\
                 validate-spec-links     RP-07: the §31 table and the register are bijective\n\
                 verify-examples         §28.6: every example formats, locks, checks, builds, verifies;\n\
                                         normalized verification records equal expected/verify (§29.5)\n\
                 check-golden            §28.3: build outputs equal the committed oracles\n\
                 check-reproducibility   §28.4: two clean builds in distinct paths are byte-identical\n\
                 check-fixtures          §28.2: every fixture's CLI run equals its expected/ files\n\
                 release-check           RP-12: refuse release until §30.3/§30.4 are fully satisfied\n\
                 validate                validate-model then validate-spec-links\n\
                 \n\
                 --write                 validate-model / check-golden / check-fixtures / verify-examples:\n\
                                         rewrite the generated bytes"
            );
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("gate failed: {error}");
            ExitCode::FAILURE
        }
    }
}

fn example_dirs(root: &Path) -> Result<Vec<PathBuf>, Fail> {
    let mut dirs = Vec::new();
    for entry in std::fs::read_dir(root.join("examples"))? {
        let path = entry?.path();
        if path.is_dir() {
            dirs.push(path);
        }
    }
    dirs.sort();
    if dirs.is_empty() {
        return Err(
            "EX-08: the examples directory is empty; the gate has nothing to verify".into(),
        );
    }
    Ok(dirs)
}

fn utf8(path: &Path) -> Result<Utf8PathBuf, Fail> {
    Utf8PathBuf::from_path_buf(path.to_path_buf())
        .map_err(|bad| format!("non-UTF-8 path {}", bad.display()).into())
}

fn engine_for(dir: &Path) -> Result<lexlean::Engine, Fail> {
    let config = utf8(&dir.join("lexlean.toml"))?;
    lexlean::Engine::load(&config).map_err(|error| format!("{}: {error}", dir.display()).into())
}

/// §28.6: every example directory is discovered and runs `fmt --check`,
/// `lock --check`, `check`, `build`, and `verify`; when the example commits
/// `expected/verify/`, the normalized verification records (audit output,
/// probe and audit modules, process records with the platform-bound fields
/// normalized) must equal it, and `--write` regenerates them.
fn verify_examples(root: &Path, write: bool) -> Result<(), Fail> {
    for dir in example_dirs(root)? {
        let name = dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let engine = engine_for(&dir)?;
        engine
            .format(lexlean::FormatRequest {
                selection: lexlean::Selection::Entrypoints,
                check_only: true,
            })
            .map_err(|error| format!("{name}: fmt --check: {error}"))?;
        engine
            .lock(lexlean::LockRequest {
                check_only: true,
                allow_network: false,
            })
            .map_err(|error| format!("{name}: lock --check: {error}"))?;
        engine
            .check(lexlean::CheckRequest {
                selection: lexlean::Selection::Entrypoints,
            })
            .map_err(|error| format!("{name}: check: {error}"))?;
        engine
            .build(lexlean::BuildRequest {
                selection: lexlean::Selection::Entrypoints,
            })
            .map_err(|error| format!("{name}: build: {error}"))?;
        let verified = engine
            .verify(lexlean::VerifyRequest {
                selection: lexlean::Selection::Entrypoints,
            })
            .map_err(|error| format!("{name}: verify: {error}"))?;
        println!(
            "verify-examples: {name} verified (attestation {})",
            verified.attestation_id.to_hex()
        );

        let records = normalized_verify_records(verified.root.as_std_path())?;
        let expected_root = dir.join("expected").join("verify");
        if write {
            if expected_root.exists() {
                std::fs::remove_dir_all(&expected_root)?;
            }
            for (relative, bytes) in &records {
                let destination = expected_root.join(relative);
                if let Some(parent) = destination.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(destination, bytes)?;
            }
            println!(
                "verify-examples: wrote {} normalized verification records for {name}",
                records.len()
            );
            continue;
        }
        if !expected_root.is_dir() {
            println!(
                "verify-examples: {name} commits no expected/verify; run `cargo xtask verify-examples --write` to record the normalized verification records (§29.5)"
            );
            continue;
        }
        compare_tree(&name, "expected/verify", &expected_root, &records)?;
        println!(
            "verify-examples: {name}: {} normalized verification records equal expected/verify (§29.5)",
            records.len()
        );
    }
    Ok(())
}

/// The verification records that are platform independent after
/// normalization (§22.7, §29.5): the audit output, the probe and audit
/// modules, and every process record with the executable digest replaced.
fn normalized_verify_records(verified: &Path) -> Result<Vec<(String, Vec<u8>)>, Fail> {
    let mut out = Vec::new();
    for entry in walkdir::WalkDir::new(verified).into_iter().flatten() {
        if !entry.file_type().is_file() {
            continue;
        }
        let relative = entry
            .path()
            .strip_prefix(verified)
            .unwrap_or(entry.path())
            .to_string_lossy()
            .replace('\\', "/");
        let is_process = relative == "probe/process.json"
            || relative == "audit/process.json"
            || relative.starts_with("process/");
        let is_module = (relative.starts_with("probe/") || relative.starts_with("audit/"))
            && relative.ends_with(".lean");
        if relative == "audit/output.txt" || is_module {
            out.push((relative, std::fs::read(entry.path())?));
        } else if is_process {
            let value: serde_json::Value = serde_json::from_slice(&std::fs::read(entry.path())?)
                .map_err(|error| format!("{relative}: {error}"))?;
            let normalized = normalize_process_record(value);
            let mut bytes = serde_json::to_vec(&normalized)?;
            bytes.push(b'\n');
            out.push((relative, bytes));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

/// Replace the platform-bound fields of a process record: the executable
/// digest, and any argv token still naming a host path outside the
/// normalized roots.
fn normalize_process_record(mut value: serde_json::Value) -> serde_json::Value {
    if let Some(object) = value.as_object_mut() {
        if object.contains_key("executable_sha256") {
            object.insert(
                "executable_sha256".to_owned(),
                serde_json::Value::String("$EXECUTABLE_SHA256".to_owned()),
            );
        }
        if let Some(serde_json::Value::Array(argv)) = object.get_mut("argv") {
            for token in argv.iter_mut() {
                if let serde_json::Value::String(text) = token {
                    if text.contains("$TOOLCHAIN") {
                        *text = "$TOOLCHAIN".to_owned();
                    }
                }
            }
        }
    }
    value
}

/// Compare a generated `(relative, bytes)` set with a committed tree, both
/// directions.
fn compare_tree(
    name: &str,
    label: &str,
    expected_root: &Path,
    files: &[(String, Vec<u8>)],
) -> Result<(), Fail> {
    for (relative, bytes) in files {
        let oracle = expected_root.join(relative);
        let committed = std::fs::read(&oracle).map_err(|error| {
            format!("R10: {name}: missing oracle {label}/{relative}: {error}; a reviewed rewrite is the only way to add one (§28.3)")
        })?;
        if committed != *bytes {
            return Err(format!(
                "R10: {name}: {label}/{relative} differs from its committed oracle; a semantic change needs an explicit rewrite and review (§28.3)"
            )
            .into());
        }
    }
    for entry in walkdir::WalkDir::new(expected_root).into_iter().flatten() {
        if !entry.file_type().is_file() {
            continue;
        }
        let relative = entry
            .path()
            .strip_prefix(expected_root)
            .unwrap_or(entry.path())
            .to_string_lossy()
            .replace('\\', "/");
        if !files.iter().any(|(path, _)| *path == relative) {
            return Err(format!(
                "R10: {name}: oracle {label}/{relative} matches no generated artifact"
            )
            .into());
        }
    }
    Ok(())
}

/// Copy an example into a fresh temporary directory, run a real `build`,
/// and return the published `.lexlean/build/<id>/` tree as
/// `(relative, bytes)` plus the temporary root (kept alive by the caller).
fn published_build(dir: &Path) -> Result<(tempfile::TempDir, Vec<(String, Vec<u8>)>), Fail> {
    let temp = tempfile::Builder::new()
        .prefix("lexlean-build-")
        .tempdir()?;
    copy_example(dir, temp.path())?;
    let engine = engine_for(temp.path())?;
    let built = engine
        .build(lexlean::BuildRequest {
            selection: lexlean::Selection::Entrypoints,
        })
        .map_err(|error| format!("{}: build: {error}", dir.display()))?;
    let build_id = built
        .build_id
        .ok_or("a successful build has a build ID (§21.5)")?;
    let config = utf8(&temp.path().join("lexlean.toml"))?;
    let project = lexlean::project::Project::load(&config)
        .map_err(|error| format!("{}: {error}", dir.display()))?;
    let published = temp
        .path()
        .join(&project.config.build_root)
        .join("build")
        .join(build_id.to_hex());
    if !published.is_dir() {
        return Err(format!(
            "AR-09: the build published nothing at {}",
            published.display()
        )
        .into());
    }
    let root_text = temp.path().to_string_lossy().into_owned();
    let mut files = Vec::new();
    for entry in walkdir::WalkDir::new(&published).into_iter().flatten() {
        if !entry.file_type().is_file() {
            continue;
        }
        let relative = entry
            .path()
            .strip_prefix(&published)
            .unwrap_or(entry.path())
            .to_string_lossy()
            .replace('\\', "/");
        let bytes = std::fs::read(entry.path())?;
        if String::from_utf8_lossy(&bytes).contains(&root_text) {
            return Err(
                format!("AR-07: {relative} embeds the absolute checkout path {root_text}").into(),
            );
        }
        files.push((relative, bytes));
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));
    Ok((temp, files))
}

/// §28.3: the published build tree of every example equals its committed
/// oracle byte for byte; golden outputs change only through `--write`.
fn check_golden(root: &Path, write: bool) -> Result<(), Fail> {
    for dir in example_dirs(root)? {
        let name = dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let (_temp, files) = published_build(&dir)?;
        let expected_root = dir.join("expected").join("build");
        if write {
            if expected_root.exists() {
                std::fs::remove_dir_all(&expected_root)?;
            }
            for (relative, bytes) in &files {
                let destination = expected_root.join(relative);
                if let Some(parent) = destination.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(destination, bytes)?;
            }
            println!(
                "check-golden: wrote {} oracle files for {name}",
                files.len()
            );
            continue;
        }
        compare_tree(&name, "expected/build", &expected_root, &files)?;
        println!(
            "check-golden: {name}: {} published artifacts equal their oracles (R10)",
            files.len()
        );
    }
    Ok(())
}

fn copy_example(from: &Path, to: &Path) -> Result<(), Fail> {
    for entry in walkdir::WalkDir::new(from).into_iter().flatten() {
        let relative = entry.path().strip_prefix(from).unwrap_or(entry.path());
        let text = relative.to_string_lossy();
        if text.starts_with(".lexlean") || text.starts_with("expected") || text.is_empty() {
            continue;
        }
        let destination = to.join(relative);
        if entry.file_type().is_dir() {
            std::fs::create_dir_all(&destination)?;
        } else if entry.file_type().is_file() {
            if let Some(parent) = destination.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::copy(entry.path(), &destination)?;
        }
    }
    Ok(())
}

/// §28.4, AR-13: two clean `build`s in distinct absolute directories
/// publish byte-identical platform-independent trees.
fn check_reproducibility(root: &Path) -> Result<(), Fail> {
    for dir in example_dirs(root)? {
        let name = dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let (temp_a, files_a) = published_build(&dir)?;
        let (temp_b, files_b) = published_build(&dir)?;
        if temp_a.path() == temp_b.path() {
            return Err("the two build directories must be distinct".into());
        }
        let names_a: Vec<&String> = files_a.iter().map(|(path, _)| path).collect();
        let names_b: Vec<&String> = files_b.iter().map(|(path, _)| path).collect();
        if names_a != names_b {
            return Err(format!(
                "R10: {name}: the two builds publish different file sets: {names_a:?} vs {names_b:?}"
            )
            .into());
        }
        for ((path_a, bytes_a), (_, bytes_b)) in files_a.iter().zip(&files_b) {
            if bytes_a != bytes_b {
                return Err(format!(
                    "R10: {name}: {path_a} differs between two clean builds in distinct directories (AR-13)"
                )
                .into());
            }
        }
        println!(
            "check-reproducibility: {name}: {} published artifacts byte-identical across {} and {} (R10)",
            files_a.len(),
            temp_a.path().display(),
            temp_b.path().display()
        );
    }
    Ok(())
}

/// RP-12: the release gate, plus the crate packaging round trip that needs
/// cargo: the packaged crate builds standalone offline and reports the same
/// four-line identity as the in-repository binary (§30.3).
fn release_check(root: &Path) -> Result<(), Fail> {
    let mut unmet: Vec<String> = match repo_model::release::check(root) {
        Ok(()) => Vec::new(),
        Err(unmet) => unmet,
    };
    let utf8_root = utf8(root)?;
    let mut in_repo = Vec::new();
    let mut in_repo_err = Vec::new();
    let exit = lexlean::cli::run(
        &["lexlean".to_owned(), "--version".to_owned()],
        &utf8_root,
        &mut in_repo,
        &mut in_repo_err,
    );
    if exit != 0 {
        unmet.push("crate-package: the in-repository binary does not report --version".to_owned());
    }
    match repo_conformance::support::packaged_crate_version(&utf8_root) {
        Ok(packaged) if packaged.as_bytes() == in_repo.as_slice() => {
            println!("release-check: the packaged crate builds standalone with the same identity:\n{packaged}");
        }
        Ok(packaged) => unmet.push(format!(
            "crate-package: the packaged crate reports\n{packaged}but the repository binary reports\n{}",
            String::from_utf8_lossy(&in_repo)
        )),
        Err(error) => unmet.push(format!("crate-package: {error}")),
    }
    if unmet.is_empty() {
        println!("release-check: every §30.3 artifact and §30.4 criterion holds");
        Ok(())
    } else {
        Err(format!(
            "RP-12: the release is refused; unmet criteria:\n  {}",
            unmet.join("\n  ")
        )
        .into())
    }
}

/// §28.2: every fixture under `tests/fixtures` and `tests/negative` runs
/// through the CLI entry point and equals its committed `expected/` files;
/// `--write` is the only path that rewrites them (§28.3).
fn check_fixtures(root: &Path, write: bool) -> Result<(), Fail> {
    let utf8_root = utf8(root)?;
    let fixtures = repo_conformance::fixtures::discover(&utf8_root);
    if fixtures.is_empty() {
        return Err(
            "§28.2: no fixture directory contains a case.toml; the gate has nothing to check"
                .into(),
        );
    }
    let mut count = 0usize;
    for dir in &fixtures {
        let relative = dir.strip_prefix(&utf8_root).unwrap_or(dir);
        if write {
            repo_conformance::fixtures::write(dir)?;
            println!("check-fixtures: wrote {relative}/expected");
        } else {
            repo_conformance::fixtures::check(dir)?;
        }
        count += 1;
    }
    if !write {
        println!("check-fixtures: {count} fixtures equal their expected files (§28.2)");
    }
    Ok(())
}
