module
import SemanticFixture.KernelReductionDefinitions
#print axioms SemanticFixture.KernelReductionDefinitions.importedAppend
#print axioms SemanticFixture.KernelReductionDefinitions.importedLength
