module
import SemanticFixture.Portable
#print axioms SemanticFixture.Portable.PortableContainers
#print axioms SemanticFixture.Portable.andUInt64
#print axioms SemanticFixture.Portable.appendBytes
#print axioms SemanticFixture.Portable.byteAt
#print axioms SemanticFixture.Portable.byteFixture
#print axioms SemanticFixture.Portable.byteLength
#print axioms SemanticFixture.Portable.checkedAddInt64
#print axioms SemanticFixture.Portable.checkedMultiplyInt64
#print axioms SemanticFixture.Portable.checkedNegateInt64
#print axioms SemanticFixture.Portable.checkedQuotientInt64
#print axioms SemanticFixture.Portable.checkedSubtractInt64
#print axioms SemanticFixture.Portable.compareByteStrings
#print axioms SemanticFixture.Portable.convertInt64
#print axioms SemanticFixture.Portable.decodeUtf8
#print axioms SemanticFixture.Portable.encodeUtf8
#print axioms SemanticFixture.Portable.formatInt64
#print axioms SemanticFixture.Portable.isZeroInt64
#print axioms SemanticFixture.Portable.joinStrings
#print axioms SemanticFixture.Portable.maximumUInt16
#print axioms SemanticFixture.Portable.maximumUInt32
#print axioms SemanticFixture.Portable.maximumUInt64
#print axioms SemanticFixture.Portable.maximumUInt8
#print axioms SemanticFixture.Portable.minimumInt16
#print axioms SemanticFixture.Portable.minimumInt32
#print axioms SemanticFixture.Portable.minimumInt64
#print axioms SemanticFixture.Portable.minimumInt8
#print axioms SemanticFixture.Portable.multiplyInt
#print axioms SemanticFixture.Portable.negateInt
#print axioms SemanticFixture.Portable.notUInt64
#print axioms SemanticFixture.Portable.orUInt64
#print axioms SemanticFixture.Portable.parseInt64
#print axioms SemanticFixture.Portable.quotientInt
#print axioms SemanticFixture.Portable.remainderInt
#print axioms SemanticFixture.Portable.shiftRightUInt64
#print axioms SemanticFixture.Portable.shiftUInt64
#print axioms SemanticFixture.Portable.sliceBytes
#print axioms SemanticFixture.Portable.splitBounded
#print axioms SemanticFixture.Portable.subtractInt
#print axioms SemanticFixture.Portable.unboundedInteger
#print axioms SemanticFixture.Portable.unicodeFixture
#print axioms SemanticFixture.Portable.xorUInt64
